// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	WatchUser   string `sokel:"watch_user,optional" label:"监听的 HN 用户名"`
	WatchItems  string `sokel:"watch_items,optional" label:"额外监听的帖子"`
	WatchQuery  string `sokel:"watch_query,optional" label:"监听的关键词"`
	WatchDays   string `sokel:"watch_days,optional" label:"跟踪多少天内的帖子" default:"14"`
	PollSeconds string `sokel:"poll_seconds,optional" label:"轮询间隔（秒）" default:"120"`
	Proxy       string `sokel:"proxy,optional" label:"出站代理"`
	WatchCursor string `sokel:"watch_cursor,optional" label:"轮询游标"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:  "watch_user",
			Label: "监听的 HN 用户名",
			Type:  contract.ParamType("text"),
			Desc:  "你的 HN 账号。它最近发的帖子下有新评论、或有人回复它的评论时触发「有新评论」；留空 = 不监听",
		},
		{
			Name:  "watch_items",
			Label: "额外监听的帖子",
			Type:  contract.ParamType("text"),
			Desc:  "帖子 id 或地址，多个用逗号分隔。别人替你发的帖子、或你想跟进的讨论放这里",
		},
		{
			Name:  "watch_query",
			Label: "监听的关键词",
			Type:  contract.ParamType("text"),
			Desc:  "出现这个词的新帖子或新评论触发「关键词命中」，如项目名或 github.com/你的/仓库；留空 = 不监听",
		},
		{
			Name:    "watch_days",
			Label:   "跟踪多少天内的帖子",
			Type:    contract.ParamType("text"),
			Default: "14",
			Desc:    "默认 14：你两周前发的帖子还会有人评论，再早的基本沉了",
		},
		{
			Name:    "poll_seconds",
			Label:   "轮询间隔（秒）",
			Type:    contract.ParamType("text"),
			Default: "120",
			Desc:    "默认 120，最短 60。HN 的接口免费，但别把它当实时推送用",
		},
		{
			Name:  "proxy",
			Label: "出站代理",
			Type:  contract.ParamType("text"),
			Desc:  "如 http://127.0.0.1:7897；部署环境直连不了 news.ycombinator.com 时必填",
		},
		{
			Name:  "watch_cursor",
			Label: "轮询游标",
			Type:  contract.ParamType("text"),
			Desc:  "事件源自动维护，勿手填",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
