// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/hackernews/schema"
)

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
}

type HnItemGetIn struct {
	ID string `json:"id" sokel:"id"`
}

type HnItemGetOut struct {
	Item schema.Item `json:"item" sokel:"item"`
}

type HnListIn struct {
	List  string `json:"list" sokel:"list"`
	Limit int    `json:"limit" sokel:"limit"`
}

type HnListOut struct {
	Items []schema.Item `json:"items" sokel:"items"`
	Count int           `json:"count" sokel:"count"`
}

type HnSearchIn struct {
	Query      string `json:"query" sokel:"query"`
	Kind       string `json:"kind" sokel:"kind"`
	SinceHours int    `json:"since_hours" sokel:"since_hours"`
	Limit      int    `json:"limit" sokel:"limit"`
}

type HnSearchOut struct {
	Items []schema.Item `json:"items" sokel:"items"`
	Count int           `json:"count" sokel:"count"`
}

type HnThreadCommentsIn struct {
	ID    string `json:"id" sokel:"id"`
	Since string `json:"since" sokel:"since"`
}

type HnThreadCommentsOut struct {
	Items []schema.Item `json:"items" sokel:"items"`
	Count int           `json:"count" sokel:"count"`
	Title string        `json:"title" sokel:"title"`
}
