// Code generated by sokel-gen. DO NOT EDIT.
//
// The authentication method is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// authMeta is this plugin's authentication declaration, exactly as declared.
func authMeta() contract.AuthMeta {
	return contract.AuthMeta{
		Kind:     contract.AuthOAuth,
		Provider: "linkedin",
		Scopes:   []string{"openid", "profile", "w_member_social"},
	}
}

// RegisterAuth declares how the credential is obtained and takes the implementation.
// The parameter list follows the declared steps: missing one is a compile error, not a panel
// that silently stalls at runtime.
func RegisterAuth(h plugin.AuthHost) {
	h.SetAuthFlow(authMeta(), plugin.AuthHandlers{})
}
