// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
	Name    string `json:"name" sokel:"name"`
}

type LiPostCreateIn struct {
	Text       string         `json:"text" sokel:"text"`
	Images     []*plugin.File `json:"images" sokel:"images"`
	ImageAlts  []string       `json:"image_alts" sokel:"image_alts"`
	Visibility string         `json:"visibility" sokel:"visibility"`
}

type LiPostCreateOut struct {
	ID  string `json:"id" sokel:"id"`
	URL string `json:"url" sokel:"url"`
}

type LiPostDeleteIn struct {
	PostID string `json:"post_id" sokel:"post_id"`
}

type LiPostDeleteOut struct {
	Deleted bool `json:"deleted" sokel:"deleted"`
}
