// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	Proxy     string `sokel:"proxy,optional" label:"出站代理"`
	UserAgent string `sokel:"user_agent,optional" label:"User-Agent"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:  "proxy",
			Label: "出站代理",
			Type:  contract.ParamType("text"),
			Desc:  "形如 `http://user:pass@host:port` 或 `socks5://host:1080`。**部署在机房/云主机上时基本是必需的**：YouTube 会用 429 或「确认你不是机器人」挡掉数据中心 IP，住宅代理是目前唯一稳定的解法",
		},
		{
			Name:  "user_agent",
			Label: "User-Agent",
			Type:  contract.ParamType("text"),
			Desc:  "留空用一个常见的桌面 Chrome UA",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
