// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/youtube-transcript/schema"
)

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
}

type TranscriptFetchIn struct {
	Video              string `json:"video" sokel:"video"`
	Languages          string `json:"languages" sokel:"languages"`
	Prefer             string `json:"prefer" sokel:"prefer"`
	TranslateTo        string `json:"translate_to" sokel:"translate_to"`
	PreserveFormatting bool   `json:"preserve_formatting" sokel:"preserve_formatting"`
}

type TranscriptFetchOut struct {
	VideoID      string           `json:"video_id" sokel:"video_id"`
	Text         string           `json:"text" sokel:"text"`
	Snippets     []schema.Snippet `json:"snippets" sokel:"snippets"`
	Count        int              `json:"count" sokel:"count"`
	Language     string           `json:"language" sokel:"language"`
	LanguageCode string           `json:"language_code" sokel:"language_code"`
	IsGenerated  bool             `json:"is_generated" sokel:"is_generated"`
	Translated   bool             `json:"translated" sokel:"translated"`
	DurationSec  float64          `json:"duration_sec" sokel:"duration_sec"`
}

type TranscriptListIn struct {
	Video string `json:"video" sokel:"video"`
}

type TranscriptListOut struct {
	VideoID     string             `json:"video_id" sokel:"video_id"`
	Transcripts []schema.TrackInfo `json:"transcripts" sokel:"transcripts"`
	Count       int                `json:"count" sokel:"count"`
	HasManual   bool               `json:"has_manual" sokel:"has_manual"`
}
