// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	AccessKeyID     string `sokel:"access_key_id" label:"AccessKey ID"`
	AccessKeySecret string `sokel:"access_key_secret" label:"AccessKey Secret" secret:"true"`
	Region          string `sokel:"region,optional" label:"默认 Region"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "access_key_id",
			Label:    "AccessKey ID",
			Type:     contract.ParamType("text"),
			Required: true,
			Desc:     "RAM 控制台创建的 AccessKey（建议专建一个最小权限的 RAM 用户，策略样例见使用说明）",
		},
		{
			Name:     "access_key_secret",
			Label:    "AccessKey Secret",
			Type:     contract.ParamType("secret"),
			Required: true,
			Desc:     "只在插件内部签名，不进节点与日志",
		},
		{
			Name:  "region",
			Label: "默认 Region",
			Type:  contract.ParamType("text"),
			Desc:  "如 cn-hangzhou；SLS/云监控/RDS 列表默认查这个 region",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
