// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/aliyun/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnAckClusters registers the implementation of "ack_clusters".
func OnAckClusters(h plugin.Host, fn func(plugin.Ctx, *AckClustersIn) (*AckClustersOut, error)) {
	h.Register(contract.OperationOf(&schema.AckClusters{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in AckClustersIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnAckKubeconfig registers the implementation of "ack_kubeconfig".
func OnAckKubeconfig(h plugin.Host, fn func(plugin.Ctx, *AckKubeconfigIn) (*AckKubeconfigOut, error)) {
	h.Register(contract.OperationOf(&schema.AckKubeconfig{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in AckKubeconfigIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCall registers the implementation of "call".
func OnCall(h plugin.Host, fn func(plugin.Ctx, *CallIn) (*CallOut, error)) {
	h.Register(contract.OperationOf(&schema.Call{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CallIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCmsMetric registers the implementation of "cms_metric".
func OnCmsMetric(h plugin.Host, fn func(plugin.Ctx, *CmsMetricIn) (*CmsMetricOut, error)) {
	h.Register(contract.OperationOf(&schema.CmsMetric{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CmsMetricIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDNSAddRecord registers the implementation of "dns_add_record".
func OnDNSAddRecord(h plugin.Host, fn func(plugin.Ctx, *DNSAddRecordIn) (*DNSAddRecordOut, error)) {
	h.Register(contract.OperationOf(&schema.DnsAddRecord{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DNSAddRecordIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDNSDeleteRecord registers the implementation of "dns_delete_record".
func OnDNSDeleteRecord(h plugin.Host, fn func(plugin.Ctx, *DNSDeleteRecordIn) (*DNSDeleteRecordOut, error)) {
	h.Register(contract.OperationOf(&schema.DnsDeleteRecord{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DNSDeleteRecordIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDNSRecords registers the implementation of "dns_records".
func OnDNSRecords(h plugin.Host, fn func(plugin.Ctx, *DNSRecordsIn) (*DNSRecordsOut, error)) {
	h.Register(contract.OperationOf(&schema.DnsRecords{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DNSRecordsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDNSUpdateRecord registers the implementation of "dns_update_record".
func OnDNSUpdateRecord(h plugin.Host, fn func(plugin.Ctx, *DNSUpdateRecordIn) (*DNSUpdateRecordOut, error)) {
	h.Register(contract.OperationOf(&schema.DnsUpdateRecord{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DNSUpdateRecordIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPush registers the implementation of "push".
func OnPush(h plugin.Host, fn func(plugin.Ctx, *PushIn) (*PushOut, error)) {
	h.Register(contract.OperationOf(&schema.Push{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PushIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnRdsInstanceDetail registers the implementation of "rds_instance_detail".
func OnRdsInstanceDetail(h plugin.Host, fn func(plugin.Ctx, *RdsInstanceDetailIn) (*RdsInstanceDetailOut, error)) {
	h.Register(contract.OperationOf(&schema.RdsInstanceDetail{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in RdsInstanceDetailIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnRdsInstances registers the implementation of "rds_instances".
func OnRdsInstances(h plugin.Host, fn func(plugin.Ctx, *RdsInstancesIn) (*RdsInstancesOut, error)) {
	h.Register(contract.OperationOf(&schema.RdsInstances{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in RdsInstancesIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnRdsSlowLogs registers the implementation of "rds_slow_logs".
func OnRdsSlowLogs(h plugin.Host, fn func(plugin.Ctx, *RdsSlowLogsIn) (*RdsSlowLogsOut, error)) {
	h.Register(contract.OperationOf(&schema.RdsSlowLogs{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in RdsSlowLogsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSendMail registers the implementation of "send_mail".
func OnSendMail(h plugin.Host, fn func(plugin.Ctx, *SendMailIn) (*SendMailOut, error)) {
	h.Register(contract.OperationOf(&schema.SendMail{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SendMailIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSlsListLogstores registers the implementation of "sls_list_logstores".
func OnSlsListLogstores(h plugin.Host, fn func(plugin.Ctx, *SlsListLogstoresIn) (*SlsListLogstoresOut, error)) {
	h.Register(contract.OperationOf(&schema.SlsListLogstores{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SlsListLogstoresIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSlsQuery registers the implementation of "sls_query".
func OnSlsQuery(h plugin.Host, fn func(plugin.Ctx, *SlsQueryIn) (*SlsQueryOut, error)) {
	h.Register(contract.OperationOf(&schema.SlsQuery{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SlsQueryIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
