// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/aliyun/schema"
)

type AckClustersIn struct {
}

type AckClustersOut struct {
	Clusters []schema.AckCluster `json:"clusters" sokel:"clusters"`
	Count    int                 `json:"count" sokel:"count"`
}

type AckKubeconfigIn struct {
	ClusterID string `json:"cluster_id" sokel:"cluster_id"`
	Private   bool   `json:"private" sokel:"private"`
}

type AckKubeconfigOut struct {
	Kubeconfig string `json:"kubeconfig" sokel:"kubeconfig"`
}

type CallIn struct {
	Endpoint string         `json:"endpoint" sokel:"endpoint"`
	Action   string         `json:"action" sokel:"action"`
	Version  string         `json:"version" sokel:"version"`
	Params   map[string]any `json:"params" sokel:"params"`
}

type CallOut struct {
	Data any `json:"data" sokel:"data"`
}

type CmsMetricIn struct {
	Namespace  string `json:"namespace" sokel:"namespace"`
	Metric     string `json:"metric" sokel:"metric"`
	InstanceID string `json:"instance_id" sokel:"instance_id"`
	Minutes    int    `json:"minutes" sokel:"minutes"`
	Period     string `json:"period" sokel:"period"`
}

type CmsMetricOut struct {
	Points []any   `json:"points" sokel:"points"`
	Latest float64 `json:"latest" sokel:"latest"`
	Count  int     `json:"count" sokel:"count"`
}

type DNSAddRecordIn struct {
	Domain string `json:"domain" sokel:"domain"`
	Rr     string `json:"rr" sokel:"rr"`
	Type   string `json:"type" sokel:"type"`
	Value  string `json:"value" sokel:"value"`
	TTL    int    `json:"ttl" sokel:"ttl"`
}

type DNSAddRecordOut struct {
	RecordID string `json:"record_id" sokel:"record_id"`
}

type DNSDeleteRecordIn struct {
	RecordID string `json:"record_id" sokel:"record_id"`
}

type DNSDeleteRecordOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type DNSRecordsIn struct {
	Domain string `json:"domain" sokel:"domain"`
	Rr     string `json:"rr" sokel:"rr"`
	Type   string `json:"type" sokel:"type"`
}

type DNSRecordsOut struct {
	Records []schema.DnsRecord `json:"records" sokel:"records"`
	Count   int                `json:"count" sokel:"count"`
}

type DNSUpdateRecordIn struct {
	RecordID string `json:"record_id" sokel:"record_id"`
	Rr       string `json:"rr" sokel:"rr"`
	Type     string `json:"type" sokel:"type"`
	Value    string `json:"value" sokel:"value"`
	TTL      int    `json:"ttl" sokel:"ttl"`
}

type DNSUpdateRecordOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK       bool   `json:"ok" sokel:"ok"`
	Identity string `json:"identity" sokel:"identity"`
	Message  string `json:"message" sokel:"message"`
}

type PushIn struct {
	AppKey      string         `json:"app_key" sokel:"app_key"`
	Target      string         `json:"target" sokel:"target"`
	TargetValue string         `json:"target_value" sokel:"target_value"`
	DeviceType  string         `json:"device_type" sokel:"device_type"`
	PushType    string         `json:"push_type" sokel:"push_type"`
	Title       string         `json:"title" sokel:"title"`
	Body        string         `json:"body" sokel:"body"`
	IosEnv      string         `json:"ios_env" sokel:"ios_env"`
	Extras      map[string]any `json:"extras" sokel:"extras"`
}

type PushOut struct {
	MessageID string `json:"message_id" sokel:"message_id"`
}

type RdsInstanceDetailIn struct {
	InstanceID string `json:"instance_id" sokel:"instance_id"`
}

type RdsInstanceDetailOut struct {
	Status         string  `json:"status" sokel:"status"`
	DiskGb         int     `json:"disk_gb" sokel:"disk_gb"`
	DiskUsedGb     float64 `json:"disk_used_gb" sokel:"disk_used_gb"`
	MaxConnections int     `json:"max_connections" sokel:"max_connections"`
	MemoryMb       int     `json:"memory_mb" sokel:"memory_mb"`
	MaintainTime   string  `json:"maintain_time" sokel:"maintain_time"`
	Raw            any     `json:"raw" sokel:"raw"`
}

type RdsInstancesIn struct {
	Region string `json:"region" sokel:"region"`
}

type RdsInstancesOut struct {
	Instances []schema.RdsInstance `json:"instances" sokel:"instances"`
	Count     int                  `json:"count" sokel:"count"`
}

type RdsSlowLogsIn struct {
	InstanceID string `json:"instance_id" sokel:"instance_id"`
	Days       int    `json:"days" sokel:"days"`
}

type RdsSlowLogsOut struct {
	SlowSqls []schema.RdsSlowSQL `json:"slow_sqls" sokel:"slow_sqls"`
	Count    int                 `json:"count" sokel:"count"`
}

type SendMailIn struct {
	AccountName string `json:"account_name" sokel:"account_name"`
	FromAlias   string `json:"from_alias" sokel:"from_alias"`
	To          string `json:"to" sokel:"to"`
	Subject     string `json:"subject" sokel:"subject"`
	HTML        string `json:"html" sokel:"html"`
	Text        string `json:"text" sokel:"text"`
	ReplyTo     string `json:"reply_to" sokel:"reply_to"`
}

type SendMailOut struct {
	EnvID string `json:"env_id" sokel:"env_id"`
}

type SlsListLogstoresIn struct {
	Project string `json:"project" sokel:"project"`
}

type SlsListLogstoresOut struct {
	Logstores []string `json:"logstores" sokel:"logstores"`
}

type SlsQueryIn struct {
	Project  string `json:"project" sokel:"project"`
	Logstore string `json:"logstore" sokel:"logstore"`
	Query    string `json:"query" sokel:"query"`
	Minutes  int    `json:"minutes" sokel:"minutes"`
	From     string `json:"from" sokel:"from"`
	To       string `json:"to" sokel:"to"`
	Limit    int    `json:"limit" sokel:"limit"`
}

type SlsQueryOut struct {
	Logs     []any `json:"logs" sokel:"logs"`
	Count    int   `json:"count" sokel:"count"`
	Complete bool  `json:"complete" sokel:"complete"`
}
