// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	AppID     string `sokel:"app_id" label:"AppID"`
	AppSecret string `sokel:"app_secret" label:"AppSecret" secret:"true"`
	Proxy     string `sokel:"proxy,optional" label:"出站代理"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "app_id",
			Label:    "AppID",
			Type:     contract.ParamType("text"),
			Required: true,
			Desc:     "公众号后台「设置与开发 → 基本配置」里的开发者 ID",
		},
		{
			Name:     "app_secret",
			Label:    "AppSecret",
			Type:     contract.ParamType("secret"),
			Required: true,
			Desc:     "同一页的开发者密码。**只在生成时显示一次**，丢了只能重置（重置会让旧的立刻失效）",
		},
		{
			Name:  "proxy",
			Label: "出站代理",
			Type:  contract.ParamType("text"),
			Desc:  "一般不用填（微信在境内）。填了要注意：**白名单认的是出口 IP**，走代理后出口是代理的 IP",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
