// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/wechat-mp/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMpDraftAdd registers the implementation of "mp_draft_add".
func OnMpDraftAdd(h plugin.Host, fn func(plugin.Ctx, *MpDraftAddIn) (*MpDraftAddOut, error)) {
	h.Register(contract.OperationOf(&schema.DraftAdd{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MpDraftAddIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMpImageUpload registers the implementation of "mp_image_upload".
func OnMpImageUpload(h plugin.Host, fn func(plugin.Ctx, *MpImageUploadIn) (*MpImageUploadOut, error)) {
	h.Register(contract.OperationOf(&schema.ImageUpload{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MpImageUploadIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMpPublish registers the implementation of "mp_publish".
func OnMpPublish(h plugin.Host, fn func(plugin.Ctx, *MpPublishIn) (*MpPublishOut, error)) {
	h.Register(contract.OperationOf(&schema.Publish{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MpPublishIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
