// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK         bool   `json:"ok" sokel:"ok"`
	Message    string `json:"message" sokel:"message"`
	DraftCount int    `json:"draft_count" sokel:"draft_count"`
}

type MpDraftAddIn struct {
	Title            string `json:"title" sokel:"title"`
	Content          string `json:"content" sokel:"content"`
	ThumbMediaID     string `json:"thumb_media_id" sokel:"thumb_media_id"`
	Author           string `json:"author" sokel:"author"`
	Digest           string `json:"digest" sokel:"digest"`
	ContentSourceURL string `json:"content_source_url" sokel:"content_source_url"`
	OpenComment      bool   `json:"open_comment" sokel:"open_comment"`
	OnlyFansComment  bool   `json:"only_fans_comment" sokel:"only_fans_comment"`
}

type MpDraftAddOut struct {
	MediaID string `json:"media_id" sokel:"media_id"`
}

type MpImageUploadIn struct {
	File    *plugin.File `json:"file" sokel:"file"`
	Purpose string       `json:"purpose" sokel:"purpose"`
}

type MpImageUploadOut struct {
	MediaID string `json:"media_id" sokel:"media_id"`
	URL     string `json:"url" sokel:"url"`
}

type MpPublishIn struct {
	MediaID string `json:"media_id" sokel:"media_id"`
	Wait    bool   `json:"wait" sokel:"wait"`
}

type MpPublishOut struct {
	PublishID  string `json:"publish_id" sokel:"publish_id"`
	ArticleURL string `json:"article_url" sokel:"article_url"`
	Status     string `json:"status" sokel:"status"`
	MsgDataID  string `json:"msg_data_id" sokel:"msg_data_id"`
}
