// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	XueqiuCookie string `sokel:"xueqiu_cookie,optional" label:"雪球 Cookie（可选）" secret:"true"`
	UserAgent    string `sokel:"user_agent,optional" label:"User-Agent"`
	Proxy        string `sokel:"proxy,optional" label:"出站代理"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:  "xueqiu_cookie",
			Label: "雪球 Cookie（可选）",
			Type:  contract.ParamType("secret"),
			Desc:  "插件默认自己去首页取匿名令牌；被风控挡住时，把浏览器里的整条 Cookie 粘进来",
		},
		{
			Name:  "user_agent",
			Label: "User-Agent",
			Type:  contract.ParamType("text"),
			Desc:  "留空用常见的桌面 Chrome UA",
		},
		{
			Name:  "proxy",
			Label: "出站代理",
			Type:  contract.ParamType("text"),
			Desc:  "取境外源时可能需要",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
