// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/feed/schema"
)

type FeedFetchIn struct {
	Source      string `json:"source" sokel:"source"`
	Target      string `json:"target" sokel:"target"`
	Cursor      string `json:"cursor" sokel:"cursor"`
	MaxItems    int    `json:"max_items" sokel:"max_items"`
	SkipReposts bool   `json:"skip_reposts" sokel:"skip_reposts"`
}

type FeedFetchOut struct {
	Items      []schema.Item `json:"items" sokel:"items"`
	NextCursor string        `json:"next_cursor" sokel:"next_cursor"`
	HasMore    bool          `json:"has_more" sokel:"has_more"`
	Count      int           `json:"count" sokel:"count"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
}
