// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	DeveloperToken string `sokel:"developer_token" label:"Developer token" secret:"true"`
	Proxy          string `sokel:"proxy,optional" label:"出站代理"`
	WatchPosts     string `sokel:"watch_posts,optional" label:"监听的产品"`
	WatchMyPosts   string `sokel:"watch_my_posts,optional" label:"监听我做的产品" default:"on"`
	PollSeconds    string `sokel:"poll_seconds,optional" label:"轮询间隔（秒）" default:"180"`
	WatchCursor    string `sokel:"watch_cursor,optional" label:"轮询游标"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "developer_token",
			Label:    "Developer token",
			Type:     contract.ParamType("secret"),
			Required: true,
			Desc:     "api.producthunt.com/v2/oauth/applications 建一个应用，页面下方的 Developer Token（不会过期，代表你自己的账号）",
		},
		{
			Name:  "proxy",
			Label: "出站代理",
			Type:  contract.ParamType("text"),
			Desc:  "如 http://127.0.0.1:7897；部署环境连不上 producthunt.com 时必填",
		},
		{
			Name:  "watch_posts",
			Label: "监听的产品",
			Type:  contract.ParamType("text"),
			Desc:  "slug 或产品页地址，多个用逗号分隔：这些产品下有新评论或新回复时触发「有新评论」",
		},
		{
			Name:    "watch_my_posts",
			Label:   "监听我做的产品",
			Type:    contract.ParamType("select"),
			Default: "on",
			Desc:    "on = token 所属账号作为制作者的最近 10 个产品也一起监听",
			Options: []contract.Option{{Value: "on", Label: "on"}, {Value: "off", Label: "off"}},
		},
		{
			Name:    "poll_seconds",
			Label:   "轮询间隔（秒）",
			Type:    contract.ParamType("text"),
			Default: "180",
			Desc:    "默认 180，最短 60（PH 按查询复杂度限流，15 分钟一个额度）",
		},
		{
			Name:  "watch_cursor",
			Label: "轮询游标",
			Type:  contract.ParamType("text"),
			Desc:  "事件源自动维护，勿手填",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
