// Code generated by sokel-gen. DO NOT EDIT.
//
// Event payload types and trigger functions are generated from the schema declaration.
// Change an event there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/producthunt/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// CommentReceivedEvent is the payload of the "有新评论" event.
type CommentReceivedEvent struct {
	CommentID   string `json:"comment_id" sokel:"comment_id"`
	Body        string `json:"body" sokel:"body"`
	URL         string `json:"url" sokel:"url"`
	VotesCount  int    `json:"votes_count" sokel:"votes_count"`
	ParentID    string `json:"parent_id" sokel:"parent_id"`
	IsReplyToMe bool   `json:"is_reply_to_me" sokel:"is_reply_to_me"`
	Username    string `json:"username" sokel:"username"`
	PostID      string `json:"post_id" sokel:"post_id"`
	PostName    string `json:"post_name" sokel:"post_name"`
	PostURL     string `json:"post_url" sokel:"post_url"`
	CreatedAt   string `json:"created_at" sokel:"created_at"`
}

// DeclareEvents hands this plugin's event contracts to the host.
//
// Common-field consistency was checked at **generation time** (each one must exist in every
// event with the same type), so this cannot fail here — a real problem showed up at
// go generate.
func DeclareEvents(h plugin.EventHost) {
	events := []contract.Event{
		contract.EventOf(&schema.CommentReceived{}),
	}
	for _, e := range events {
		h.DeclareEvent(e)
	}
	names := []string{"comment_id", "body", "url", "post_name", "created_at"}
	fields, _ := contract.ValidateCommonFields(events, names)
	h.DeclareEventsCommon(fields, names)
}

// TriggerCommentReceived pushes one "有新评论" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerCommentReceived(ctx plugin.SourceCtx, eventID string, p *CommentReceivedEvent) error {
	return ctx.Trigger("comment_received", eventID, p)
}
