// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/producthunt/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPhComments registers the implementation of "ph_comments".
func OnPhComments(h plugin.Host, fn func(plugin.Ctx, *PhCommentsIn) (*PhCommentsOut, error)) {
	h.Register(contract.OperationOf(&schema.Comments{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PhCommentsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPhLeaderboard registers the implementation of "ph_leaderboard".
func OnPhLeaderboard(h plugin.Host, fn func(plugin.Ctx, *PhLeaderboardIn) (*PhLeaderboardOut, error)) {
	h.Register(contract.OperationOf(&schema.Leaderboard{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PhLeaderboardIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPhPostGet registers the implementation of "ph_post_get".
func OnPhPostGet(h plugin.Host, fn func(plugin.Ctx, *PhPostGetIn) (*PhPostGetOut, error)) {
	h.Register(contract.OperationOf(&schema.PostGet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PhPostGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
