// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/producthunt/schema"
)

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK       bool   `json:"ok" sokel:"ok"`
	Message  string `json:"message" sokel:"message"`
	Username string `json:"username" sokel:"username"`
}

type PhCommentsIn struct {
	Post  string `json:"post" sokel:"post"`
	Limit int    `json:"limit" sokel:"limit"`
}

type PhCommentsOut struct {
	Items []schema.Comment `json:"items" sokel:"items"`
	Count int              `json:"count" sokel:"count"`
	Total int              `json:"total" sokel:"total"`
}

type PhLeaderboardIn struct {
	Date  string `json:"date" sokel:"date"`
	Order string `json:"order" sokel:"order"`
	Limit int    `json:"limit" sokel:"limit"`
}

type PhLeaderboardOut struct {
	Items []schema.Post `json:"items" sokel:"items"`
	Count int           `json:"count" sokel:"count"`
}

type PhPostGetIn struct {
	Post string `json:"post" sokel:"post"`
}

type PhPostGetOut struct {
	Post schema.Post `json:"post" sokel:"post"`
}
