// Code generated by sokel-gen. DO NOT EDIT.
//
// Event payload types and trigger functions are generated from the schema declaration.
// Change an event there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/synology/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// FileChangedEvent is the payload of the "文件修改" event.
type FileChangedEvent struct {
	Path  string `json:"path" sokel:"path"`
	Name  string `json:"name" sokel:"name"`
	Ext   string `json:"ext" sokel:"ext"`
	Dir   string `json:"dir" sokel:"dir"`
	Size  int    `json:"size" sokel:"size"`
	Mtime string `json:"mtime" sokel:"mtime"`
}

// FileCreatedEvent is the payload of the "文件新增" event.
// 文件静默 settle 秒且大小稳定后才报——SMB 保存是临时文件+改名，大文件拷贝是持续写入，不等落定会拿到写了一半的文件
type FileCreatedEvent struct {
	Path  string `json:"path" sokel:"path"`
	Name  string `json:"name" sokel:"name"`
	Ext   string `json:"ext" sokel:"ext"`
	Dir   string `json:"dir" sokel:"dir"`
	Size  int    `json:"size" sokel:"size"`
	Mtime string `json:"mtime" sokel:"mtime"`
}

// FileDeletedEvent is the payload of the "文件删除" event.
type FileDeletedEvent struct {
	Path string `json:"path" sokel:"path"`
	Name string `json:"name" sokel:"name"`
	Ext  string `json:"ext" sokel:"ext"`
	Dir  string `json:"dir" sokel:"dir"`
}

// DeclareEvents hands this plugin's event contracts to the host.
//
// Common-field consistency was checked at **generation time** (each one must exist in every
// event with the same type), so this cannot fail here — a real problem showed up at
// go generate.
func DeclareEvents(h plugin.EventHost) {
	events := []contract.Event{
		contract.EventOf(&schema.FileChanged{}),
		contract.EventOf(&schema.FileCreated{}),
		contract.EventOf(&schema.FileDeleted{}),
	}
	for _, e := range events {
		h.DeclareEvent(e)
	}
	names := []string{"path", "name", "ext", "dir"}
	fields, _ := contract.ValidateCommonFields(events, names)
	h.DeclareEventsCommon(fields, names)
}

// TriggerFileChanged pushes one "文件修改" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerFileChanged(ctx plugin.SourceCtx, eventID string, p *FileChangedEvent) error {
	return ctx.Trigger("file_changed", eventID, p)
}

// TriggerFileCreated pushes one "文件新增" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerFileCreated(ctx plugin.SourceCtx, eventID string, p *FileCreatedEvent) error {
	return ctx.Trigger("file_created", eventID, p)
}

// TriggerFileDeleted pushes one "文件删除" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerFileDeleted(ctx plugin.SourceCtx, eventID string, p *FileDeletedEvent) error {
	return ctx.Trigger("file_deleted", eventID, p)
}
