// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/synology/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnDeleteFile registers the implementation of "delete_file".
func OnDeleteFile(h plugin.Host, fn func(plugin.Ctx, *DeleteFileIn) (*DeleteFileOut, error)) {
	h.Register(contract.OperationOf(&schema.DeleteFile{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DeleteFileIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnListDir registers the implementation of "list_dir".
func OnListDir(h plugin.Host, fn func(plugin.Ctx, *ListDirIn) (*ListDirOut, error)) {
	h.Register(contract.OperationOf(&schema.ListDir{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ListDirIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMoveFile registers the implementation of "move_file".
func OnMoveFile(h plugin.Host, fn func(plugin.Ctx, *MoveFileIn) (*MoveFileOut, error)) {
	h.Register(contract.OperationOf(&schema.MoveFile{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MoveFileIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnReadFile registers the implementation of "read_file".
func OnReadFile(h plugin.Host, fn func(plugin.Ctx, *ReadFileIn) (*ReadFileOut, error)) {
	h.Register(contract.OperationOf(&schema.ReadFile{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ReadFileIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
