// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	AndroidAppKey       string `sokel:"android_app_key,optional" label:"Android AppKey"`
	AndroidMasterSecret string `sokel:"android_master_secret,optional" label:"Android Master Secret" secret:"true"`
	IosAppKey           string `sokel:"ios_app_key,optional" label:"iOS AppKey"`
	IosMasterSecret     string `sokel:"ios_master_secret,optional" label:"iOS Master Secret" secret:"true"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:  "android_app_key",
			Label: "Android AppKey",
			Type:  contract.ParamType("text"),
			Desc:  "友盟控制台 Android 应用的 AppKey。只推 iOS 可留空",
		},
		{
			Name:  "android_master_secret",
			Label: "Android Master Secret",
			Type:  contract.ParamType("secret"),
		},
		{
			Name:  "ios_app_key",
			Label: "iOS AppKey",
			Type:  contract.ParamType("text"),
		},
		{
			Name:  "ios_master_secret",
			Label: "iOS Master Secret",
			Type:  contract.ParamType("secret"),
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
