// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/umeng/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnCancel registers the implementation of "cancel".
func OnCancel(h plugin.Host, fn func(plugin.Ctx, *CancelIn) (*CancelOut, error)) {
	h.Register(contract.OperationOf(&schema.Cancel{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CancelIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPush registers the implementation of "push".
func OnPush(h plugin.Host, fn func(plugin.Ctx, *PushIn) (*PushOut, error)) {
	h.Register(contract.OperationOf(&schema.Push{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PushIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnTaskStatus registers the implementation of "task_status".
func OnTaskStatus(h plugin.Host, fn func(plugin.Ctx, *TaskStatusIn) (*TaskStatusOut, error)) {
	h.Register(contract.OperationOf(&schema.TaskStatus{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in TaskStatusIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
