// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

type CancelIn struct {
	Platform string `json:"platform" sokel:"platform"`
	TaskID   string `json:"task_id" sokel:"task_id"`
}

type CancelOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
}

type PushIn struct {
	Platform     string         `json:"platform" sokel:"platform"`
	DeviceTokens string         `json:"device_tokens" sokel:"device_tokens"`
	Title        string         `json:"title" sokel:"title"`
	Body         string         `json:"body" sokel:"body"`
	Extras       map[string]any `json:"extras" sokel:"extras"`
	Production   bool           `json:"production" sokel:"production"`
}

type PushOut struct {
	TaskID string `json:"task_id" sokel:"task_id"`
}

type TaskStatusIn struct {
	Platform string `json:"platform" sokel:"platform"`
	TaskID   string `json:"task_id" sokel:"task_id"`
}

type TaskStatusOut struct {
	Status     int    `json:"status" sokel:"status"`
	StatusText string `json:"status_text" sokel:"status_text"`
	SentCount  int    `json:"sent_count" sokel:"sent_count"`
	OpenCount  int    `json:"open_count" sokel:"open_count"`
}
