// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	InstanceURL string `sokel:"instance_url" label:"实例地址"`
	AccessToken string `sokel:"access_token" label:"访问令牌" secret:"true"`
	Proxy       string `sokel:"proxy,optional" label:"出站代理"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "instance_url",
			Label:    "实例地址",
			Type:     contract.ParamType("text"),
			Required: true,
			Desc:     "你的账号所在实例，如 https://mastodon.social 或 https://m.cmx.im",
		},
		{
			Name:     "access_token",
			Label:    "访问令牌",
			Type:     contract.ParamType("secret"),
			Required: true,
			Desc:     "实例里「偏好设置 → 开发 → 新建应用」，作用域勾 write:statuses、write:media、read:accounts，建完在应用详情页复制「你的访问令牌」",
		},
		{
			Name:  "proxy",
			Label: "出站代理",
			Type:  contract.ParamType("text"),
			Desc:  "如 http://127.0.0.1:7897；部署环境直连不了该实例时必填",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
