// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/mastodon/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMastoStatusCreate registers the implementation of "masto_status_create".
func OnMastoStatusCreate(h plugin.Host, fn func(plugin.Ctx, *MastoStatusCreateIn) (*MastoStatusCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.StatusCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MastoStatusCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMastoStatusDelete registers the implementation of "masto_status_delete".
func OnMastoStatusDelete(h plugin.Host, fn func(plugin.Ctx, *MastoStatusDeleteIn) (*MastoStatusDeleteOut, error)) {
	h.Register(contract.OperationOf(&schema.StatusDelete{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MastoStatusDeleteIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMastoStatusThread registers the implementation of "masto_status_thread".
func OnMastoStatusThread(h plugin.Host, fn func(plugin.Ctx, *MastoStatusThreadIn) (*MastoStatusThreadOut, error)) {
	h.Register(contract.OperationOf(&schema.StatusThread{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MastoStatusThreadIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
