// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	Token   string `sokel:"token" label:"TuShare Token" secret:"true"`
	BaseURL string `sokel:"base_url,optional" label:"服务地址"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "token",
			Label:    "TuShare Token",
			Type:     contract.ParamType("secret"),
			Required: true,
			Desc:     "tushare.pro 个人主页的接口 token。能调哪些接口取决于账号积分",
		},
		{
			Name:  "base_url",
			Label: "服务地址",
			Type:  contract.ParamType("text"),
			Desc:  "留空用官方端点 https://api.tushare.pro",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
