// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	Cookie       string `sokel:"cookie" label:"Cookie" secret:"true"`
	SessionToken string `sokel:"session_token,optional" label:"会话令牌（session_token）" secret:"true"`
	RiskParam    string `sokel:"risk_param,optional" label:"风控参数（md5__1038）"`
	UserAgent    string `sokel:"user_agent,optional" label:"User-Agent"`
	Proxy        string `sokel:"proxy,optional" label:"出站代理"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "cookie",
			Label:    "Cookie",
			Type:     contract.ParamType("secret"),
			Required: true,
			Desc:     "浏览器里登录雪球后，F12 → Network → 任意请求 → 复制整条 Cookie 值粘进来。至少要含 xq_a_token / xqat / xq_id_token / u / device_id",
		},
		{
			Name:  "session_token",
			Label: "会话令牌（session_token）",
			Type:  contract.ParamType("secret"),
			Desc:  "发帖接口要的防重放串。**留空则插件自己去页面上取**；取不到时会在错误里让你手工粘一次（F12 → Network → 发一条帖子 → 请求体里的 session_token）",
		},
		{
			Name:  "risk_param",
			Label: "风控参数（md5__1038）",
			Type:  contract.ParamType("text"),
			Desc:  "网页请求 URL 上挂的那串。**先留空试**——多数情况下不带也能发；若报风控/403，把浏览器里那条完整值粘进来",
		},
		{
			Name:  "user_agent",
			Label: "User-Agent",
			Type:  contract.ParamType("text"),
			Desc:  "留空用一个常见的桌面 Chrome UA。与你取 cookie 的浏览器保持一致更稳",
		},
		{
			Name:  "proxy",
			Label: "出站代理",
			Type:  contract.ParamType("text"),
			Desc:  "部署环境直连不了 xueqiu.com 时填",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
