// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
	UID     string `json:"uid" sokel:"uid"`
	Name    string `json:"name" sokel:"name"`
}

type XqArticleDraftIn struct {
	Title    string         `json:"title" sokel:"title"`
	Content  string         `json:"content" sokel:"content"`
	Images   []*plugin.File `json:"images" sokel:"images"`
	CoverPic string         `json:"cover_pic" sokel:"cover_pic"`
	Private  bool           `json:"private" sokel:"private"`
}

type XqArticleDraftOut struct {
	ID      string `json:"id" sokel:"id"`
	EditURL string `json:"edit_url" sokel:"edit_url"`
}

type XqPostCreateIn struct {
	Text        string         `json:"text" sokel:"text"`
	Images      []*plugin.File `json:"images" sokel:"images"`
	AiDisclose  bool           `json:"ai_disclose" sokel:"ai_disclose"`
	AllowReward bool           `json:"allow_reward" sokel:"allow_reward"`
}

type XqPostCreateOut struct {
	ID  string `json:"id" sokel:"id"`
	URL string `json:"url" sokel:"url"`
}
