// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	Token            string `sokel:"token,optional" label:"内部集成密钥" secret:"true"`
	AccessToken      string `sokel:"access_token,optional" label:"访问令牌（授权注入）" secret:"true"`
	RefreshToken     string `sokel:"refresh_token,optional" label:"刷新令牌（授权注入）" secret:"true"`
	Proxy            string `sokel:"proxy,optional" label:"出站代理"`
	WatchDataSources string `sokel:"watch_data_sources,optional" label:"监听的数据源"`
	PollSeconds      string `sokel:"poll_seconds,optional" label:"轮询间隔（秒）" default:"60"`
	WatchCursor      string `sokel:"watch_cursor,optional" label:"轮询游标"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:  "token",
			Label: "内部集成密钥",
			Type:  contract.ParamType("secret"),
			Desc:  "notion.so/profile/integrations 建一个「内部」集成，「密钥」页复制 ntn_ 开头那串；走 OAuth 授权则留空。**填完还要去 Notion 里把页面「⋯ → 连接」给这个集成**，否则什么都读不到",
		},
		{
			Name:  "access_token",
			Label: "访问令牌（授权注入）",
			Type:  contract.ParamType("secret"),
			Desc:  "点「授权」后自动写入，勿手填",
		},
		{
			Name:  "refresh_token",
			Label: "刷新令牌（授权注入）",
			Type:  contract.ParamType("secret"),
			Desc:  "勿手填",
		},
		{
			Name:  "proxy",
			Label: "出站代理",
			Type:  contract.ParamType("text"),
			Desc:  "如 http://127.0.0.1:7897；部署环境直连不了 Notion 时必填",
		},
		{
			Name:  "watch_data_sources",
			Label: "监听的数据源",
			Type:  contract.ParamType("text"),
			Desc:  "逗号分隔的数据源 id 或链接（数据库链接直接贴即可）；留空 = 不产事件。改完保存即生效，事件源会自动重启",
		},
		{
			Name:    "poll_seconds",
			Label:   "轮询间隔（秒）",
			Type:    contract.ParamType("text"),
			Default: "60",
			Desc:    "默认 60；Notion 限流 3 次/秒，盯的表越多别调得越短",
		},
		{
			Name:  "watch_cursor",
			Label: "轮询游标",
			Type:  contract.ParamType("text"),
			Desc:  "事件源自动维护，勿手填",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
