// Code generated by sokel-gen. DO NOT EDIT.
//
// Event payload types and trigger functions are generated from the schema declaration.
// Change an event there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/notion/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// PageCreatedEvent is the payload of the "新增行" event.
type PageCreatedEvent struct {
	PageID         string         `json:"page_id" sokel:"page_id"`
	DataSourceID   string         `json:"data_source_id" sokel:"data_source_id"`
	URL            string         `json:"url" sokel:"url"`
	Title          string         `json:"title" sokel:"title"`
	CreatedTime    string         `json:"created_time" sokel:"created_time"`
	LastEditedTime string         `json:"last_edited_time" sokel:"last_edited_time"`
	Props          map[string]any `json:"props" sokel:"props"`
}

// PageUpdatedEvent is the payload of the "行被修改" event.
type PageUpdatedEvent struct {
	PageID         string         `json:"page_id" sokel:"page_id"`
	DataSourceID   string         `json:"data_source_id" sokel:"data_source_id"`
	URL            string         `json:"url" sokel:"url"`
	Title          string         `json:"title" sokel:"title"`
	CreatedTime    string         `json:"created_time" sokel:"created_time"`
	LastEditedTime string         `json:"last_edited_time" sokel:"last_edited_time"`
	Props          map[string]any `json:"props" sokel:"props"`
}

// DeclareEvents hands this plugin's event contracts to the host.
//
// Common-field consistency was checked at **generation time** (each one must exist in every
// event with the same type), so this cannot fail here — a real problem showed up at
// go generate.
func DeclareEvents(h plugin.EventHost) {
	events := []contract.Event{
		contract.EventOf(&schema.PageCreated{}),
		contract.EventOf(&schema.PageUpdated{}),
	}
	for _, e := range events {
		h.DeclareEvent(e)
	}
	names := []string{"page_id", "data_source_id"}
	fields, _ := contract.ValidateCommonFields(events, names)
	h.DeclareEventsCommon(fields, names)
}

// TriggerPageCreated pushes one "新增行" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerPageCreated(ctx plugin.SourceCtx, eventID string, p *PageCreatedEvent) error {
	return ctx.Trigger("page_created", eventID, p)
}

// TriggerPageUpdated pushes one "行被修改" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerPageUpdated(ctx plugin.SourceCtx, eventID string, p *PageUpdatedEvent) error {
	return ctx.Trigger("page_updated", eventID, p)
}
