// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/notion/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionBlockAppend registers the implementation of "notion_block_append".
func OnNotionBlockAppend(h plugin.Host, fn func(plugin.Ctx, *NotionBlockAppendIn) (*NotionBlockAppendOut, error)) {
	h.Register(contract.OperationOf(&schema.AppendBlocks{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionBlockAppendIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionBlockChildren registers the implementation of "notion_block_children".
func OnNotionBlockChildren(h plugin.Host, fn func(plugin.Ctx, *NotionBlockChildrenIn) (*NotionBlockChildrenOut, error)) {
	h.Register(contract.OperationOf(&schema.ListBlocks{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionBlockChildrenIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionCommentCreate registers the implementation of "notion_comment_create".
func OnNotionCommentCreate(h plugin.Host, fn func(plugin.Ctx, *NotionCommentCreateIn) (*NotionCommentCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.CreateComment{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionCommentCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionCommentList registers the implementation of "notion_comment_list".
func OnNotionCommentList(h plugin.Host, fn func(plugin.Ctx, *NotionCommentListIn) (*NotionCommentListOut, error)) {
	h.Register(contract.OperationOf(&schema.ListComments{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionCommentListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionDBCreate registers the implementation of "notion_db_create".
func OnNotionDBCreate(h plugin.Host, fn func(plugin.Ctx, *NotionDBCreateIn) (*NotionDBCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.CreateDatabase{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionDBCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionDBList registers the implementation of "notion_db_list".
func OnNotionDBList(h plugin.Host, fn func(plugin.Ctx, *NotionDBListIn) (*NotionDBListOut, error)) {
	h.Register(contract.OperationOf(&schema.ListDataSources{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionDBListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionDBQuery registers the implementation of "notion_db_query".
func OnNotionDBQuery(h plugin.Host, fn func(plugin.Ctx, *NotionDBQueryIn) (*NotionDBQueryOut, error)) {
	h.Register(contract.OperationOf(&schema.QueryDataSource{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionDBQueryIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionDBSchema registers the implementation of "notion_db_schema".
func OnNotionDBSchema(h plugin.Host, fn func(plugin.Ctx, *NotionDBSchemaIn) (*NotionDBSchemaOut, error)) {
	h.Register(contract.OperationOf(&schema.GetSchema{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionDBSchemaIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionDBUpdateSchema registers the implementation of "notion_db_update_schema".
func OnNotionDBUpdateSchema(h plugin.Host, fn func(plugin.Ctx, *NotionDBUpdateSchemaIn) (*NotionDBUpdateSchemaOut, error)) {
	h.Register(contract.OperationOf(&schema.UpdateSchema{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionDBUpdateSchemaIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionFileUpload registers the implementation of "notion_file_upload".
func OnNotionFileUpload(h plugin.Host, fn func(plugin.Ctx, *NotionFileUploadIn) (*NotionFileUploadOut, error)) {
	h.Register(contract.OperationOf(&schema.UploadFile{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionFileUploadIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionPageContent registers the implementation of "notion_page_content".
func OnNotionPageContent(h plugin.Host, fn func(plugin.Ctx, *NotionPageContentIn) (*NotionPageContentOut, error)) {
	h.Register(contract.OperationOf(&schema.UpdateContent{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionPageContentIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionPageCreate registers the implementation of "notion_page_create".
func OnNotionPageCreate(h plugin.Host, fn func(plugin.Ctx, *NotionPageCreateIn) (*NotionPageCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.CreatePage{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionPageCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionPageGet registers the implementation of "notion_page_get".
func OnNotionPageGet(h plugin.Host, fn func(plugin.Ctx, *NotionPageGetIn) (*NotionPageGetOut, error)) {
	h.Register(contract.OperationOf(&schema.GetPage{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionPageGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionPageTrash registers the implementation of "notion_page_trash".
func OnNotionPageTrash(h plugin.Host, fn func(plugin.Ctx, *NotionPageTrashIn) (*NotionPageTrashOut, error)) {
	h.Register(contract.OperationOf(&schema.TrashPage{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionPageTrashIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionPageUpdate registers the implementation of "notion_page_update".
func OnNotionPageUpdate(h plugin.Host, fn func(plugin.Ctx, *NotionPageUpdateIn) (*NotionPageUpdateOut, error)) {
	h.Register(contract.OperationOf(&schema.UpdatePage{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionPageUpdateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionSearch registers the implementation of "notion_search".
func OnNotionSearch(h plugin.Host, fn func(plugin.Ctx, *NotionSearchIn) (*NotionSearchOut, error)) {
	h.Register(contract.OperationOf(&schema.Search{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionSearchIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionUserGet registers the implementation of "notion_user_get".
func OnNotionUserGet(h plugin.Host, fn func(plugin.Ctx, *NotionUserGetIn) (*NotionUserGetOut, error)) {
	h.Register(contract.OperationOf(&schema.GetUser{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionUserGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNotionUserList registers the implementation of "notion_user_list".
func OnNotionUserList(h plugin.Host, fn func(plugin.Ctx, *NotionUserListIn) (*NotionUserListOut, error)) {
	h.Register(contract.OperationOf(&schema.ListUsers{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NotionUserListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
