// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/notion/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK            bool   `json:"ok" sokel:"ok"`
	Name          string `json:"name" sokel:"name"`
	WorkspaceName string `json:"workspace_name" sokel:"workspace_name"`
	Message       string `json:"message" sokel:"message"`
}

type NotionBlockAppendIn struct {
	BlockID string `json:"block_id" sokel:"block_id"`
	Blocks  any    `json:"blocks" sokel:"blocks"`
}

type NotionBlockAppendOut struct {
	Count    int      `json:"count" sokel:"count"`
	BlockIDs []string `json:"block_ids" sokel:"block_ids"`
}

type NotionBlockChildrenIn struct {
	BlockID  string `json:"block_id" sokel:"block_id"`
	MaxItems int    `json:"max_items" sokel:"max_items"`
}

type NotionBlockChildrenOut struct {
	Blocks     any    `json:"blocks" sokel:"blocks"`
	Count      int    `json:"count" sokel:"count"`
	NextCursor string `json:"next_cursor" sokel:"next_cursor"`
}

type NotionCommentCreateIn struct {
	PageID       string `json:"page_id" sokel:"page_id"`
	DiscussionID string `json:"discussion_id" sokel:"discussion_id"`
	Text         string `json:"text" sokel:"text"`
}

type NotionCommentCreateOut struct {
	ID           string `json:"id" sokel:"id"`
	DiscussionID string `json:"discussion_id" sokel:"discussion_id"`
}

type NotionCommentListIn struct {
	BlockID  string `json:"block_id" sokel:"block_id"`
	MaxItems int    `json:"max_items" sokel:"max_items"`
}

type NotionCommentListOut struct {
	Comments []schema.Comment `json:"comments" sokel:"comments"`
	Count    int              `json:"count" sokel:"count"`
}

type NotionDBCreateIn struct {
	ParentPageID string         `json:"parent_page_id" sokel:"parent_page_id"`
	Title        string         `json:"title" sokel:"title"`
	Properties   map[string]any `json:"properties" sokel:"properties"`
}

type NotionDBCreateOut struct {
	DatabaseID   string `json:"database_id" sokel:"database_id"`
	DataSourceID string `json:"data_source_id" sokel:"data_source_id"`
	URL          string `json:"url" sokel:"url"`
}

type NotionDBListIn struct {
	DatabaseID string `json:"database_id" sokel:"database_id"`
}

type NotionDBListOut struct {
	DatabaseID        string                 `json:"database_id" sokel:"database_id"`
	Title             string                 `json:"title" sokel:"title"`
	DataSources       []schema.DataSourceRef `json:"data_sources" sokel:"data_sources"`
	FirstDataSourceID string                 `json:"first_data_source_id" sokel:"first_data_source_id"`
}

type NotionDBQueryIn struct {
	DataSourceID string `json:"data_source_id" sokel:"data_source_id"`
	Filter       any    `json:"filter" sokel:"filter"`
	Sorts        any    `json:"sorts" sokel:"sorts"`
	MaxItems     int    `json:"max_items" sokel:"max_items"`
	StartCursor  string `json:"start_cursor" sokel:"start_cursor"`
}

type NotionDBQueryOut struct {
	Pages      []schema.PageItem `json:"pages" sokel:"pages"`
	Count      int               `json:"count" sokel:"count"`
	HasMore    bool              `json:"has_more" sokel:"has_more"`
	NextCursor string            `json:"next_cursor" sokel:"next_cursor"`
}

type NotionDBSchemaIn struct {
	DataSourceID string `json:"data_source_id" sokel:"data_source_id"`
}

type NotionDBSchemaOut struct {
	DataSourceID string            `json:"data_source_id" sokel:"data_source_id"`
	DatabaseID   string            `json:"database_id" sokel:"database_id"`
	Title        string            `json:"title" sokel:"title"`
	Properties   []schema.PropSpec `json:"properties" sokel:"properties"`
}

type NotionDBUpdateSchemaIn struct {
	DataSourceID string         `json:"data_source_id" sokel:"data_source_id"`
	Title        string         `json:"title" sokel:"title"`
	Properties   map[string]any `json:"properties" sokel:"properties"`
}

type NotionDBUpdateSchemaOut struct {
	DataSourceID string            `json:"data_source_id" sokel:"data_source_id"`
	Properties   []schema.PropSpec `json:"properties" sokel:"properties"`
}

type NotionFileUploadIn struct {
	File     *plugin.File `json:"file" sokel:"file"`
	Filename string       `json:"filename" sokel:"filename"`
}

type NotionFileUploadOut struct {
	FileUploadID string `json:"file_upload_id" sokel:"file_upload_id"`
	Filename     string `json:"filename" sokel:"filename"`
}

type NotionPageContentIn struct {
	PageID     string `json:"page_id" sokel:"page_id"`
	Mode       string `json:"mode" sokel:"mode"`
	Markdown   string `json:"markdown" sokel:"markdown"`
	OldStr     string `json:"old_str" sokel:"old_str"`
	NewStr     string `json:"new_str" sokel:"new_str"`
	ReplaceAll bool   `json:"replace_all" sokel:"replace_all"`
}

type NotionPageContentOut struct {
	ID        string `json:"id" sokel:"id"`
	Markdown  string `json:"markdown" sokel:"markdown"`
	Truncated bool   `json:"truncated" sokel:"truncated"`
}

type NotionPageCreateIn struct {
	ParentType string         `json:"parent_type" sokel:"parent_type"`
	ParentID   string         `json:"parent_id" sokel:"parent_id"`
	Title      string         `json:"title" sokel:"title"`
	Props      map[string]any `json:"props" sokel:"props"`
	Markdown   string         `json:"markdown" sokel:"markdown"`
	Icon       string         `json:"icon" sokel:"icon"`
}

type NotionPageCreateOut struct {
	ID    string `json:"id" sokel:"id"`
	URL   string `json:"url" sokel:"url"`
	Title string `json:"title" sokel:"title"`
}

type NotionPageGetIn struct {
	PageID      string `json:"page_id" sokel:"page_id"`
	WithContent bool   `json:"with_content" sokel:"with_content"`
}

type NotionPageGetOut struct {
	ID             string         `json:"id" sokel:"id"`
	URL            string         `json:"url" sokel:"url"`
	Title          string         `json:"title" sokel:"title"`
	Markdown       string         `json:"markdown" sokel:"markdown"`
	Truncated      bool           `json:"truncated" sokel:"truncated"`
	Props          map[string]any `json:"props" sokel:"props"`
	PropertiesRaw  map[string]any `json:"properties_raw" sokel:"properties_raw"`
	ParentType     string         `json:"parent_type" sokel:"parent_type"`
	ParentID       string         `json:"parent_id" sokel:"parent_id"`
	CreatedTime    string         `json:"created_time" sokel:"created_time"`
	LastEditedTime string         `json:"last_edited_time" sokel:"last_edited_time"`
	InTrash        bool           `json:"in_trash" sokel:"in_trash"`
}

type NotionPageTrashIn struct {
	PageID  string `json:"page_id" sokel:"page_id"`
	Restore bool   `json:"restore" sokel:"restore"`
}

type NotionPageTrashOut struct {
	ID      string `json:"id" sokel:"id"`
	InTrash bool   `json:"in_trash" sokel:"in_trash"`
}

type NotionPageUpdateIn struct {
	PageID string         `json:"page_id" sokel:"page_id"`
	Title  string         `json:"title" sokel:"title"`
	Props  map[string]any `json:"props" sokel:"props"`
	Icon   string         `json:"icon" sokel:"icon"`
}

type NotionPageUpdateOut struct {
	ID  string `json:"id" sokel:"id"`
	URL string `json:"url" sokel:"url"`
}

type NotionSearchIn struct {
	Query    string `json:"query" sokel:"query"`
	Type     string `json:"type" sokel:"type"`
	MaxItems int    `json:"max_items" sokel:"max_items"`
}

type NotionSearchOut struct {
	Items []schema.SearchItem `json:"items" sokel:"items"`
	Count int                 `json:"count" sokel:"count"`
}

type NotionUserGetIn struct {
	UserID string `json:"user_id" sokel:"user_id"`
}

type NotionUserGetOut struct {
	ID        string `json:"id" sokel:"id"`
	Name      string `json:"name" sokel:"name"`
	Type      string `json:"type" sokel:"type"`
	Email     string `json:"email" sokel:"email"`
	AvatarURL string `json:"avatar_url" sokel:"avatar_url"`
}

type NotionUserListIn struct {
	MaxItems int `json:"max_items" sokel:"max_items"`
}

type NotionUserListOut struct {
	Users []schema.User `json:"users" sokel:"users"`
	Count int           `json:"count" sokel:"count"`
}
