package main

// The platform receives the webhook on our behalf (zero-latency events; coexists with the
// polling source in events.go — pick whichever one you need):
// point the GitLab project's Settings -> Webhooks at the platform's /hooks/{token} and check
// Push/MR/Issue/Pipeline.
//
// Signature check: GitLab sends the Secret token verbatim in the X-Gitlab-Token header (not
// HMAC) — just compare it against the credential's webhook_secret; if the credential has no
// secret configured, skip verification (acceptable for self-hosted internal use, documented).
//
// event_id deliberately uses a different namespace than the polling source (webhook events
// use the wh: prefix): when both paths are enabled, the same action triggers once on each —
// the docs say "pick one", we don't force dedup here (webhook payload ids and Events API
// object ids live in different domains; forcing them together would make a fragile mapping).

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/sokel-dev/sokel-plugin-sdk/sokel"
)

func handleWebhook(ctx sokel.WebhookCtx, req *sokel.WebhookRequest) sokel.WebhookResponse {
	secret := strings.TrimSpace(ctx.Credential()["webhook_secret"])
	if secret != "" && req.Header("X-Gitlab-Token") != secret {
		return sokel.Text(401, "invalid token")
	}
	event := req.Header("X-Gitlab-Event")
	var body map[string]any
	if json.Unmarshal(req.Body, &body) != nil {
		return sokel.Text(400, "bad payload")
	}
	proj := nestedStr(body, "project", "path_with_namespace")
	switch event {
	case "Push Hook":
		after, _ := body["after"].(string)
		ref := strings.TrimPrefix(str(body, "ref"), "refs/heads/")
		count := 0
		if v, ok := body["total_commits_count"].(float64); ok {
			count = int(v)
		}
		title := ""
		if arr, ok := body["commits"].([]any); ok && len(arr) > 0 {
			if m, ok := arr[len(arr)-1].(map[string]any); ok {
				title = str(m, "title")
			}
		}
		_ = TriggerCommitPushed(ctx, "wh:"+after, &CommitPushedEvent{
			Project: proj, Ref: ref, CommitID: after, CommitTitle: title,
			CommitCount: count, Author: str(body, "user_username"), Raw: body, Source: "webhook",
		})
	case "Merge Request Hook":
		attrs, _ := body["object_attributes"].(map[string]any)
		iid := num(attrs, "iid")
		action := str(attrs, "action")
		e := fmt.Sprintf("wh:mr:%d:%s:%v", iid, action, attrs["updated_at"])
		switch action {
		case "open":
			_ = TriggerMrOpened(ctx, e, &MrOpenedEvent{Project: proj, Iid: iid,
				Title: str(attrs, "title"), Author: nestedStr(body, "user", "username"), Raw: body, Source: "webhook"})
		case "merge":
			_ = TriggerMrMerged(ctx, e, &MrMergedEvent{Project: proj, Iid: iid,
				Title: str(attrs, "title"), Author: nestedStr(body, "user", "username"), Raw: body, Source: "webhook"})
		}
	case "Issue Hook":
		attrs, _ := body["object_attributes"].(map[string]any)
		if added := addedLabels(body); str(attrs, "action") == "update" && len(added) > 0 {
			// event_id includes updated_at: removing a label and re-adding it is two
			// real events; deduping on iid+label name alone would swallow the second one.
			_ = TriggerIssueLabeled(ctx, fmt.Sprintf("wh:issue-label:%d:%s", num(attrs, "iid"), str(attrs, "updated_at")),
				&IssueLabeledEvent{
					Project: proj, Iid: num(attrs, "iid"), Title: str(attrs, "title"),
					Description: str(attrs, "description"), AddedLabels: added,
					Labels: hookLabels(body, attrs), URL: str(attrs, "url"),
					Author: nestedStr(body, "user", "username"),
				})
		}
		if str(attrs, "action") == "open" {
			_ = TriggerIssueOpened(ctx, fmt.Sprintf("wh:issue:%d", num(attrs, "iid")), &IssueOpenedEvent{
				Project: proj, Iid: num(attrs, "iid"), Title: str(attrs, "title"),
				Description: str(attrs, "description"), Labels: hookLabels(body, attrs),
				URL:    str(attrs, "url"),
				Author: nestedStr(body, "user", "username"), Raw: body, Source: "webhook"})
		}
	case "Note Hook":
		// Comments. Only Issue comments count here -- MR / commit / inline-diff comments all
		// share the same Hook; without filtering, "commenting on an MR" would also dispatch an Issue action.
		attrs, _ := body["object_attributes"].(map[string]any)
		// system == true means a system note generated by actions like label/assignee changes, not something a human said.
		// Without this guard, "adding a label to an Issue" would also dispatch an action.
		sysNote, _ := attrs["system"].(bool)
		if mr, _ := body["merge_request"].(map[string]any); str(attrs, "noteable_type") == "MergeRequest" && !sysNote {
			_ = TriggerMrCommented(ctx, fmt.Sprintf("wh:mrnote:%d", num(attrs, "id")), &MrCommentedEvent{
				Project: proj, Iid: num(mr, "iid"), Title: str(mr, "title"),
				Comment: str(attrs, "note"), Author: nestedStr(body, "user", "username"),
				URL: str(attrs, "url"),
			})
		}
		if str(attrs, "noteable_type") == "Issue" && !sysNote {
			iss, _ := body["issue"].(map[string]any)
			_ = TriggerIssueCommented(ctx, fmt.Sprintf("wh:note:%d", num(attrs, "id")), &IssueCommentedEvent{
				Project: proj, Iid: num(iss, "iid"), Title: str(iss, "title"),
				Comment: str(attrs, "note"), Author: nestedStr(body, "user", "username"),
				URL: str(attrs, "url"),
			})
		}
	case "Pipeline Hook":
		attrs, _ := body["object_attributes"].(map[string]any)
		if str(attrs, "status") == "failed" {
			_ = TriggerPipelineFailed(ctx, fmt.Sprintf("wh:pipe:%d", num(attrs, "id")), &PipelineFailedEvent{
				Project: proj, PipelineID: num(attrs, "id"), Ref: str(attrs, "ref"),
				SHA: str(attrs, "sha"), WebURL: nestedStr(body, "project", "web_url"),
			})
		}
	}
	// Also return 200 for unrecognized event types: GitLab sends a bunch of types depending on
	// project configuration, and we should not make it retry repeatedly.
	return sokel.OK()
}

func nestedStr(m map[string]any, k1, k2 string) string {
	if mm, ok := m[k1].(map[string]any); ok {
		return str(mm, k2)
	}
	return ""
}

// hookLabels reads label names from the Issue Hook. GitLab puts them in two places with
// different shapes: the top-level labels is an array of objects [{title:...}], while
// object_attributes.labels is sometimes the same shape and sometimes absent -- try both, use whichever we get.
func hookLabels(body, attrs map[string]any) []string {
	for _, src := range []any{body["labels"], attrs["labels"]} {
		arr, ok := src.([]any)
		if !ok || len(arr) == 0 {
			continue
		}
		var out []string
		for _, it := range arr {
			switch v := it.(type) {
			case string:
				out = append(out, v)
			case map[string]any:
				if t := str(v, "title"); t != "" {
					out = append(out, t)
				}
			}
		}
		if len(out) > 0 {
			return out
		}
	}
	return nil
}

// addedLabels returns which labels were newly added by this update.
//
// GitLab puts label changes in the previous/current arrays under changes.labels (elements
// are label objects, with the name in title). Only returns non-empty for genuine additions --
// removing a label is also an update, and should not be treated as a "dispatch signal".
func addedLabels(body map[string]any) []string {
	ch, _ := body["changes"].(map[string]any)
	lb, _ := ch["labels"].(map[string]any)
	if lb == nil {
		return nil
	}
	titles := func(v any) map[string]bool {
		out := map[string]bool{}
		arr, _ := v.([]any)
		for _, it := range arr {
			if m, ok := it.(map[string]any); ok {
				if t := str(m, "title"); t != "" {
					out[t] = true
				}
			}
		}
		return out
	}
	prev, cur := titles(lb["previous"]), titles(lb["current"])
	var added []string
	for t := range cur {
		if !prev[t] {
			added = append(added, t)
		}
	}
	sort.Strings(added) // stable order: event_id and outputs should not jitter with map iteration order
	return added
}
