// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	BaseURL       string `sokel:"base_url,optional" label:"GitLab 地址"`
	Token         string `sokel:"token" label:"访问令牌" secret:"true"`
	WebhookSecret string `sokel:"webhook_secret,optional" label:"Webhook Secret" secret:"true"`
	WatchProjects string `sokel:"watch_projects,optional" label:"事件盯哪些项目"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:  "base_url",
			Label: "GitLab 地址",
			Type:  contract.ParamType("text"),
			Desc:  "自建实例填根地址（如 https://git.example.com）；留空 = gitlab.com",
		},
		{
			Name:     "token",
			Label:    "访问令牌",
			Type:     contract.ParamType("secret"),
			Required: true,
			Desc:     "个人访问令牌（用户头像 → Preferences → Access Tokens），scope 至少 api；建议专建一个机器人账号的 token 并按需给 scope",
		},
		{
			Name:  "webhook_secret",
			Label: "Webhook Secret",
			Type:  contract.ParamType("secret"),
			Desc:  "平台代收 webhook 用：GitLab 项目 Settings→Webhooks 里填的 Secret token，两边一致才收（防伪造）。不用 webhook 可留空",
		},
		{
			Name:  "watch_projects",
			Label: "事件盯哪些项目",
			Type:  contract.ParamType("text"),
			Desc:  "path 形态逗号分隔（如 backend/server,infra/deploy）。**填了才启动事件源**：新提交/新 MR/合并/新 Issue/流水线失败 会触发工作流（轮询，约 1 分钟延迟；要零延迟用 GitLab Webhook 指平台的 Webhook 触发器）",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
