// Code generated by sokel-gen. DO NOT EDIT.
//
// Event payload types and trigger functions are generated from the schema declaration.
// Change an event there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/gitlab/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// CommitPushedEvent is the payload of the "有新提交" event.
type CommitPushedEvent struct {
	Project     string `json:"project" sokel:"project"`
	Ref         string `json:"ref" sokel:"ref"`
	CommitID    string `json:"commit_id" sokel:"commit_id"`
	CommitTitle string `json:"commit_title" sokel:"commit_title"`
	CommitCount int    `json:"commit_count" sokel:"commit_count"`
	Author      string `json:"author" sokel:"author"`
	Source      string `json:"source" sokel:"source"`
	Raw         any    `json:"raw" sokel:"raw"`
}

// IssueCommentedEvent is the payload of the "Issue 有新评论" event.
type IssueCommentedEvent struct {
	Project string `json:"project" sokel:"project"`
	Iid     int    `json:"iid" sokel:"iid"`
	Title   string `json:"title" sokel:"title"`
	Comment string `json:"comment" sokel:"comment"`
	Author  string `json:"author" sokel:"author"`
	URL     string `json:"url" sokel:"url"`
}

// IssueLabeledEvent is the payload of the "Issue 被打标签" event.
type IssueLabeledEvent struct {
	Project     string   `json:"project" sokel:"project"`
	Iid         int      `json:"iid" sokel:"iid"`
	Title       string   `json:"title" sokel:"title"`
	Description string   `json:"description" sokel:"description"`
	AddedLabels []string `json:"added_labels" sokel:"added_labels"`
	Labels      []string `json:"labels" sokel:"labels"`
	URL         string   `json:"url" sokel:"url"`
	Author      string   `json:"author" sokel:"author"`
}

// IssueOpenedEvent is the payload of the "新 Issue" event.
type IssueOpenedEvent struct {
	Project     string   `json:"project" sokel:"project"`
	Iid         int      `json:"iid" sokel:"iid"`
	Title       string   `json:"title" sokel:"title"`
	Description string   `json:"description" sokel:"description"`
	Labels      []string `json:"labels" sokel:"labels"`
	URL         string   `json:"url" sokel:"url"`
	Author      string   `json:"author" sokel:"author"`
	Source      string   `json:"source" sokel:"source"`
	Raw         any      `json:"raw" sokel:"raw"`
}

// MrCommentedEvent is the payload of the "MR 有新评论" event.
type MrCommentedEvent struct {
	Project string `json:"project" sokel:"project"`
	Iid     int    `json:"iid" sokel:"iid"`
	Title   string `json:"title" sokel:"title"`
	Comment string `json:"comment" sokel:"comment"`
	Author  string `json:"author" sokel:"author"`
	URL     string `json:"url" sokel:"url"`
}

// MrMergedEvent is the payload of the "MR 被合并" event.
type MrMergedEvent struct {
	Project string `json:"project" sokel:"project"`
	Iid     int    `json:"iid" sokel:"iid"`
	Title   string `json:"title" sokel:"title"`
	Author  string `json:"author" sokel:"author"`
	Source  string `json:"source" sokel:"source"`
	Raw     any    `json:"raw" sokel:"raw"`
}

// MrOpenedEvent is the payload of the "新 MR" event.
type MrOpenedEvent struct {
	Project string `json:"project" sokel:"project"`
	Iid     int    `json:"iid" sokel:"iid"`
	Title   string `json:"title" sokel:"title"`
	Author  string `json:"author" sokel:"author"`
	Source  string `json:"source" sokel:"source"`
	Raw     any    `json:"raw" sokel:"raw"`
}

// PipelineFailedEvent is the payload of the "流水线失败" event.
type PipelineFailedEvent struct {
	Project    string `json:"project" sokel:"project"`
	PipelineID int    `json:"pipeline_id" sokel:"pipeline_id"`
	Ref        string `json:"ref" sokel:"ref"`
	SHA        string `json:"sha" sokel:"sha"`
	WebURL     string `json:"web_url" sokel:"web_url"`
}

// DeclareEvents hands this plugin's event contracts to the host.
//
// Common-field consistency was checked at **generation time** (each one must exist in every
// event with the same type), so this cannot fail here — a real problem showed up at
// go generate.
func DeclareEvents(h plugin.EventHost) {
	events := []contract.Event{
		contract.EventOf(&schema.CommitPushed{}),
		contract.EventOf(&schema.IssueCommented{}),
		contract.EventOf(&schema.IssueLabeled{}),
		contract.EventOf(&schema.IssueOpened{}),
		contract.EventOf(&schema.MrCommented{}),
		contract.EventOf(&schema.MrMerged{}),
		contract.EventOf(&schema.MrOpened{}),
		contract.EventOf(&schema.PipelineFailed{}),
	}
	for _, e := range events {
		h.DeclareEvent(e)
	}
	names := []string{"project"}
	fields, _ := contract.ValidateCommonFields(events, names)
	h.DeclareEventsCommon(fields, names)
}

// TriggerCommitPushed pushes one "有新提交" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerCommitPushed(ctx plugin.SourceCtx, eventID string, p *CommitPushedEvent) error {
	return ctx.Trigger("commit_pushed", eventID, p)
}

// TriggerIssueCommented pushes one "Issue 有新评论" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerIssueCommented(ctx plugin.SourceCtx, eventID string, p *IssueCommentedEvent) error {
	return ctx.Trigger("issue_commented", eventID, p)
}

// TriggerIssueLabeled pushes one "Issue 被打标签" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerIssueLabeled(ctx plugin.SourceCtx, eventID string, p *IssueLabeledEvent) error {
	return ctx.Trigger("issue_labeled", eventID, p)
}

// TriggerIssueOpened pushes one "新 Issue" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerIssueOpened(ctx plugin.SourceCtx, eventID string, p *IssueOpenedEvent) error {
	return ctx.Trigger("issue_opened", eventID, p)
}

// TriggerMrCommented pushes one "MR 有新评论" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerMrCommented(ctx plugin.SourceCtx, eventID string, p *MrCommentedEvent) error {
	return ctx.Trigger("mr_commented", eventID, p)
}

// TriggerMrMerged pushes one "MR 被合并" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerMrMerged(ctx plugin.SourceCtx, eventID string, p *MrMergedEvent) error {
	return ctx.Trigger("mr_merged", eventID, p)
}

// TriggerMrOpened pushes one "新 MR" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerMrOpened(ctx plugin.SourceCtx, eventID string, p *MrOpenedEvent) error {
	return ctx.Trigger("mr_opened", eventID, p)
}

// TriggerPipelineFailed pushes one "流水线失败" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerPipelineFailed(ctx plugin.SourceCtx, eventID string, p *PipelineFailedEvent) error {
	return ctx.Trigger("pipeline_failed", eventID, p)
}
