// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/gitlab/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnBranchesList registers the implementation of "branches_list".
func OnBranchesList(h plugin.Host, fn func(plugin.Ctx, *BranchesListIn) (*BranchesListOut, error)) {
	h.Register(contract.OperationOf(&schema.BranchesList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BranchesListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCall registers the implementation of "call".
func OnCall(h plugin.Host, fn func(plugin.Ctx, *CallIn) (*CallOut, error)) {
	h.Register(contract.OperationOf(&schema.Call{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CallIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCommitsList registers the implementation of "commits_list".
func OnCommitsList(h plugin.Host, fn func(plugin.Ctx, *CommitsListIn) (*CommitsListOut, error)) {
	h.Register(contract.OperationOf(&schema.CommitsList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CommitsListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnFileGet registers the implementation of "file_get".
func OnFileGet(h plugin.Host, fn func(plugin.Ctx, *FileGetIn) (*FileGetOut, error)) {
	h.Register(contract.OperationOf(&schema.FileGet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in FileGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnFileWrite registers the implementation of "file_write".
func OnFileWrite(h plugin.Host, fn func(plugin.Ctx, *FileWriteIn) (*FileWriteOut, error)) {
	h.Register(contract.OperationOf(&schema.FileWrite{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in FileWriteIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIssueCreate registers the implementation of "issue_create".
func OnIssueCreate(h plugin.Host, fn func(plugin.Ctx, *IssueCreateIn) (*IssueCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.IssueCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IssueCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIssueNote registers the implementation of "issue_note".
func OnIssueNote(h plugin.Host, fn func(plugin.Ctx, *IssueNoteIn) (*IssueNoteOut, error)) {
	h.Register(contract.OperationOf(&schema.IssueNote{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IssueNoteIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIssueUpdate registers the implementation of "issue_update".
func OnIssueUpdate(h plugin.Host, fn func(plugin.Ctx, *IssueUpdateIn) (*IssueUpdateOut, error)) {
	h.Register(contract.OperationOf(&schema.IssueUpdate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IssueUpdateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIssuesList registers the implementation of "issues_list".
func OnIssuesList(h plugin.Host, fn func(plugin.Ctx, *IssuesListIn) (*IssuesListOut, error)) {
	h.Register(contract.OperationOf(&schema.IssuesList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IssuesListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnJobLog registers the implementation of "job_log".
func OnJobLog(h plugin.Host, fn func(plugin.Ctx, *JobLogIn) (*JobLogOut, error)) {
	h.Register(contract.OperationOf(&schema.JobLog{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in JobLogIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMrApprove registers the implementation of "mr_approve".
func OnMrApprove(h plugin.Host, fn func(plugin.Ctx, *MrApproveIn) (*MrApproveOut, error)) {
	h.Register(contract.OperationOf(&schema.MrApprove{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MrApproveIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMrChanges registers the implementation of "mr_changes".
func OnMrChanges(h plugin.Host, fn func(plugin.Ctx, *MrChangesIn) (*MrChangesOut, error)) {
	h.Register(contract.OperationOf(&schema.MrChanges{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MrChangesIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMrCreate registers the implementation of "mr_create".
func OnMrCreate(h plugin.Host, fn func(plugin.Ctx, *MrCreateIn) (*MrCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.MrCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MrCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMrDiscussion registers the implementation of "mr_discussion".
func OnMrDiscussion(h plugin.Host, fn func(plugin.Ctx, *MrDiscussionIn) (*MrDiscussionOut, error)) {
	h.Register(contract.OperationOf(&schema.MrDiscussion{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MrDiscussionIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMrList registers the implementation of "mr_list".
func OnMrList(h plugin.Host, fn func(plugin.Ctx, *MrListIn) (*MrListOut, error)) {
	h.Register(contract.OperationOf(&schema.MrList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MrListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMrMerge registers the implementation of "mr_merge".
func OnMrMerge(h plugin.Host, fn func(plugin.Ctx, *MrMergeIn) (*MrMergeOut, error)) {
	h.Register(contract.OperationOf(&schema.MrMerge{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MrMergeIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMrNote registers the implementation of "mr_note".
func OnMrNote(h plugin.Host, fn func(plugin.Ctx, *MrNoteIn) (*MrNoteOut, error)) {
	h.Register(contract.OperationOf(&schema.MrNote{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MrNoteIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMrUpdate registers the implementation of "mr_update".
func OnMrUpdate(h plugin.Host, fn func(plugin.Ctx, *MrUpdateIn) (*MrUpdateOut, error)) {
	h.Register(contract.OperationOf(&schema.MrUpdate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MrUpdateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNoteUpdate registers the implementation of "note_update".
func OnNoteUpdate(h plugin.Host, fn func(plugin.Ctx, *NoteUpdateIn) (*NoteUpdateOut, error)) {
	h.Register(contract.OperationOf(&schema.NoteUpdate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NoteUpdateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPipelineJobs registers the implementation of "pipeline_jobs".
func OnPipelineJobs(h plugin.Host, fn func(plugin.Ctx, *PipelineJobsIn) (*PipelineJobsOut, error)) {
	h.Register(contract.OperationOf(&schema.PipelineJobs{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PipelineJobsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPipelineTrigger registers the implementation of "pipeline_trigger".
func OnPipelineTrigger(h plugin.Host, fn func(plugin.Ctx, *PipelineTriggerIn) (*PipelineTriggerOut, error)) {
	h.Register(contract.OperationOf(&schema.PipelineTrigger{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PipelineTriggerIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPipelinesList registers the implementation of "pipelines_list".
func OnPipelinesList(h plugin.Host, fn func(plugin.Ctx, *PipelinesListIn) (*PipelinesListOut, error)) {
	h.Register(contract.OperationOf(&schema.PipelinesList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PipelinesListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnProjectsList registers the implementation of "projects_list".
func OnProjectsList(h plugin.Host, fn func(plugin.Ctx, *ProjectsListIn) (*ProjectsListOut, error)) {
	h.Register(contract.OperationOf(&schema.ProjectsList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ProjectsListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSearch registers the implementation of "search".
func OnSearch(h plugin.Host, fn func(plugin.Ctx, *SearchIn) (*SearchOut, error)) {
	h.Register(contract.OperationOf(&schema.Search{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SearchIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
