// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	WebhookURL string `sokel:"webhook_url" label:"Webhook 地址" secret:"true"`
	Secret     string `sokel:"secret,optional" label:"签名密钥" secret:"true"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "webhook_url",
			Label:    "Webhook 地址",
			Type:     contract.ParamType("secret"),
			Required: true,
			Desc:     "群设置 → 群机器人 → 添加「自定义机器人」后复制（open.feishu.cn/open-apis/bot/v2/hook/…）。它本身就是钥匙，按密钥保管",
		},
		{
			Name:  "secret",
			Label: "签名密钥",
			Type:  contract.ParamType("secret"),
			Desc:  "机器人安全设置若开了「签名校验」，把密钥粘这里；没开留空",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
