// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
}

type WebhookSendIn struct {
	Text     string         `json:"text" sokel:"text"`
	Title    string         `json:"title" sokel:"title"`
	Markdown string         `json:"markdown" sokel:"markdown"`
	Card     map[string]any `json:"card" sokel:"card"`
	AtAll    bool           `json:"at_all" sokel:"at_all"`
}

type WebhookSendOut struct {
	OK bool `json:"ok" sokel:"ok"`
}
