package main

// SDK client management. **This is the first plugin in the whole codebase to pull in a vendor
// SDK**, so the reasoning deserves spelling out:
//
// Every plugin before this one was plain HTTP — good enough, small dependency surface. Feishu
// is the exception, because it has two things that plain HTTP handles poorly:
//
//   - **Long-lived event subscription (larkws)**: events don't arrive over a public webhook;
//     the plugin actively opens a WebSocket to Feishu, and events are pushed down that
//     connection. No public IP needed, no decrypt/verify step — this is exactly isomorphic to
//     this platform's "plugin makes an outbound connection to the broker" philosophy. But the
//     frame protocol is Feishu's own (protobuf), and implementing it ourselves would be both
//     fragile and not worth it.
//   - **tenant_access_token lifecycle**: obtaining/caching/refreshing on expiry, built into
//     the SDK.
//
// Usage is still kept minimal: REST calls always go through raw `client.Do` (paths/bodies built
// by hand, matching the style of the other plugins, with the `call` fallback operation naturally
// sharing the same channel); the typed modules are only used for multipart uploads (im
// images/files, drive uploads) — exactly where the SDK earns its keep.

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"sync"

	lark "github.com/larksuite/oapi-sdk-go/v3"
	larkcore "github.com/larksuite/oapi-sdk-go/v3/core"

	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
	"github.com/sokel-dev/sokel-plugin-sdk/sokel"
)

// Cred is generated by sokel-gen from schema.Credential (zz_credential.go).

func baseURL(domain string) string {
	switch {
	case domain == "lark":
		return lark.LarkBaseUrl
	case strings.HasPrefix(domain, "http://"), strings.HasPrefix(domain, "https://"):
		// A full URL is passed through as-is: tests pointing at a fake httptest Feishu
		// rely entirely on this; in production the credential is a dropdown so a third
		// value never shows up, but a privately-deployed Feishu (KA's dedicated domain)
		// will also go through this path in the future.
		return strings.TrimRight(domain, "/")
	}
	return lark.FeishuBaseUrl
}

// clientCache caches the SDK client by app_id. The client holds its own token cache internally;
// creating a new one on every call would mean re-exchanging the token every time — handing
// Feishu's rate limiter free ammunition.
var (
	cliMu    sync.Mutex
	cliCache = map[string]*lark.Client{}
)

func clientOf(cred Cred) (*lark.Client, error) {
	appID, secret := strings.TrimSpace(cred.AppID), strings.TrimSpace(cred.AppSecret)
	if appID == "" || secret == "" {
		return nil, fmt.Errorf("凭证缺 app_id/app_secret（开放平台「凭证与基础信息」页）")
	}
	// The key includes a digest of the secret (issue #13 item 3): it used to be cached by
	// app_id|domain, so a user who fixed their secret would still get the client built from
	// the old secret — the health check would stay red forever until the process restarted.
	// The reverse case (the secret gets revoked on Feishu's side) can still coast for about
	// 2 hours on the SDK's token cache; that's an inherent window of the token cache. The
	// health check has been changed to exchange the token directly and isn't affected by
	// this (misc.go opHealthCheck).
	sum := sha256.Sum256([]byte(secret))
	key := appID + "|" + cred.Domain + "|" + hex.EncodeToString(sum[:8])
	cliMu.Lock()
	defer cliMu.Unlock()
	if c, ok := cliCache[key]; ok {
		return c, nil
	}
	c := lark.NewClient(appID, secret,
		lark.WithOpenBaseUrl(baseURL(cred.Domain)),
		lark.WithEnableTokenCache(true),
	)
	cliCache[key] = c
	return c, nil
}

// feishuResp is the Open Platform's uniform response envelope.
type feishuResp struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data json.RawMessage `json:"data"`
}

// callRaw directly calls any Open Platform endpoint. Token injection/refresh is handled by the
// SDK; on return, **a non-zero business code is always turned into an error** — most Feishu
// failures are HTTP 200 + code!=0, and if this weren't caught here every single operation would
// have to check it itself, and missing even one spot means a silent failure.
func callRaw(ctx context.Context, cred Cred, method, path string, body any) (json.RawMessage, error) {
	c, err := clientOf(cred)
	if err != nil {
		return nil, err
	}
	resp, err := c.Do(ctx, &larkcore.ApiReq{
		HttpMethod:                method,
		ApiPath:                   path,
		Body:                      body,
		SupportedAccessTokenTypes: []larkcore.AccessTokenType{larkcore.AccessTokenTypeTenant},
	})
	if err != nil {
		return nil, connErr(err)
	}
	var r feishuResp
	if uerr := json.Unmarshal(resp.RawBody, &r); uerr != nil {
		if resp.StatusCode != http.StatusOK {
			return nil, fmt.Errorf("飞书返回 HTTP %d：%s", resp.StatusCode, clip(resp.RawBody, 200))
		}
		return nil, fmt.Errorf("飞书应答解不开（前 200 字：%s）", clip(resp.RawBody, 200))
	}
	if r.Code != 0 {
		return nil, feishuErr(r.Code, r.Msg)
	}
	if len(r.Data) == 0 {
		// A few legacy endpoints (bot/v3/info) don't wrap fields in a data envelope; the
		// fields are directly at the top level — hand it back as-is.
		return resp.RawBody, nil
	}
	return r.Data, nil
}

// callRawFull is the same as callRaw, but **does not turn a business code into an error** — used
// by the `call` fallback operation: someone calling the documented endpoint directly needs the
// raw code/msg to troubleshoot against the docs, and wrapping it would just get in the way.
func callRawFull(ctx context.Context, cred Cred, method, path string, body any) (*feishuResp, error) {
	c, err := clientOf(cred)
	if err != nil {
		return nil, err
	}
	resp, err := c.Do(ctx, &larkcore.ApiReq{
		HttpMethod: method, ApiPath: path, Body: body,
		SupportedAccessTokenTypes: []larkcore.AccessTokenType{larkcore.AccessTokenTypeTenant},
	})
	if err != nil {
		return nil, connErr(err)
	}
	var r feishuResp
	if uerr := json.Unmarshal(resp.RawBody, &r); uerr != nil {
		return nil, fmt.Errorf("飞书返回 HTTP %d，应答不是 JSON（前 200 字：%s）", resp.StatusCode, clip(resp.RawBody, 200))
	}
	return &r, nil
}

// connErr handles SDK-layer errors (a token-exchange failure happens **before** c.Do, so it
// never goes through feishuErr). The most common cause of a token-exchange failure is a bad
// credential, so the SDK's raw message is translated into a next step.
func connErr(err error) error {
	msg := err.Error()
	if strings.Contains(msg, "code:10003") || strings.Contains(msg, "code:10014") ||
		strings.Contains(msg, "app not found") || strings.Contains(msg, "app secret invalid") {
		return fmt.Errorf("换 tenant_access_token 失败——app_id/app_secret 有误或应用被停用，"+
			"去开放平台「凭证与基础信息」核对（原文：%s）", msg)
	}
	return fmt.Errorf("连接飞书失败: %w", err)
}

// feishuErr translates common business codes into "what to do next." Feishu's msg is English
// aimed at developers, but whoever sees this error is most likely someone configuring a node on
// the canvas.
func feishuErr(code int, msg string) error {
	switch code {
	case 99991663, 99991661, 99991668:
		return fmt.Errorf("飞书拒绝了应用身份（code %d: %s）——app_id/app_secret 有误或应用被停用，去开放平台「凭证与基础信息」核对", code, msg)
	case 99991672, 99991679:
		return fmt.Errorf("应用缺权限（code %d: %s）——去开放平台「权限管理」开通对应权限并**重新发布版本**", code, msg)
	case 230002:
		return fmt.Errorf("bot 不在这个会话里（code %d）——先把机器人拉进群，或确认 chat_id 没填错", code)
	case 230013:
		return fmt.Errorf("bot 能力未启用（code %d）——去开放平台「应用能力」添加「机器人」并发布版本", code)
	case 232009:
		return fmt.Errorf("对方关闭了机器人消息（code %d）", code)
	case 1254050, 1254005:
		return fmt.Errorf("多维表格拒绝访问（code %d: %s）——把表格分享给应用：表格右上角「…」→ 添加文档应用", code, msg)
	}
	return fmt.Errorf("飞书返回业务码 %d：%s", code, msg)
}

func clip(b []byte, n int) string {
	s := strings.TrimSpace(string(b))
	if len(s) > n {
		return s[:n] + "…"
	}
	return s
}

// credOf / credOfSource each fetch the credential once, on the operation side and the event
// source side respectively (the SDK's two ctx shapes).
func credOf(ctx plugin.Ctx) Cred {
	var c Cred
	sokel.BindCredential(ctx, &c)
	return c
}
