// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	AppID     string `sokel:"app_id" label:"App ID"`
	AppSecret string `sokel:"app_secret" label:"App Secret" secret:"true"`
	Domain    string `sokel:"domain,optional" label:"平台"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "app_id",
			Label:    "App ID",
			Type:     contract.ParamType("text"),
			Required: true,
			Desc:     "开放平台「开发者后台 → 凭证与基础信息」里的 App ID（cli_ 开头）",
		},
		{
			Name:     "app_secret",
			Label:    "App Secret",
			Type:     contract.ParamType("secret"),
			Required: true,
			Desc:     "同页的 App Secret。只在插件内部换 tenant_access_token，不进节点与日志",
		},
		{
			Name:    "domain",
			Label:   "平台",
			Type:    contract.ParamType("select"),
			Desc:    "feishu=国内（open.feishu.cn）；lark=国际版（open.larksuite.com）。默认 feishu",
			Options: []contract.Option{{Value: "feishu", Label: "feishu"}, {Value: "lark", Label: "lark"}},
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
