// Code generated by sokel-gen. DO NOT EDIT.
//
// Event payload types and trigger functions are generated from the schema declaration.
// Change an event there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/feishu/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// BotAddedEvent is the payload of the "bot 被拉进群" event.
type BotAddedEvent struct {
	ChatID        string `json:"chat_id" sokel:"chat_id"`
	ChatName      string `json:"chat_name" sokel:"chat_name"`
	InviterOpenID string `json:"inviter_open_id" sokel:"inviter_open_id"`
	Raw           any    `json:"raw" sokel:"raw"`
}

// CardActionEvent is the payload of the "卡片按钮点击" event.
type CardActionEvent struct {
	ChatID         string `json:"chat_id" sokel:"chat_id"`
	MessageID      string `json:"message_id" sokel:"message_id"`
	OperatorOpenID string `json:"operator_open_id" sokel:"operator_open_id"`
	ActionValue    any    `json:"action_value" sokel:"action_value"`
	FormValues     any    `json:"form_values" sokel:"form_values"`
	Raw            any    `json:"raw" sokel:"raw"`
}

// MessageEvent is the payload of the "收到消息" event.
type MessageEvent struct {
	ChatID       string `json:"chat_id" sokel:"chat_id"`
	ChatType     string `json:"chat_type" sokel:"chat_type"`
	MessageID    string `json:"message_id" sokel:"message_id"`
	SenderOpenID string `json:"sender_open_id" sokel:"sender_open_id"`
	MessageType  string `json:"message_type" sokel:"message_type"`
	Text         string `json:"text" sokel:"text"`
	MentionedBot bool   `json:"mentioned_bot" sokel:"mentioned_bot"`
	Raw          any    `json:"raw" sokel:"raw"`
}

// DeclareEvents hands this plugin's event contracts to the host.
//
// Common-field consistency was checked at **generation time** (each one must exist in every
// event with the same type), so this cannot fail here — a real problem showed up at
// go generate.
func DeclareEvents(h plugin.EventHost) {
	events := []contract.Event{
		contract.EventOf(&schema.BotAdded{}),
		contract.EventOf(&schema.CardAction{}),
		contract.EventOf(&schema.MessageReceived{}),
	}
	for _, e := range events {
		h.DeclareEvent(e)
	}
	names := []string{"chat_id"}
	fields, _ := contract.ValidateCommonFields(events, names)
	h.DeclareEventsCommon(fields, names)
}

// TriggerBotAdded pushes one "bot 被拉进群" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerBotAdded(ctx plugin.SourceCtx, eventID string, p *BotAddedEvent) error {
	return ctx.Trigger("bot_added", eventID, p)
}

// TriggerCardAction pushes one "卡片按钮点击" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerCardAction(ctx plugin.SourceCtx, eventID string, p *CardActionEvent) error {
	return ctx.Trigger("card_action", eventID, p)
}

// TriggerMessage pushes one "收到消息" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerMessage(ctx plugin.SourceCtx, eventID string, p *MessageEvent) error {
	return ctx.Trigger("message", eventID, p)
}
