// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/feishu/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnAddChatMembers registers the implementation of "add_chat_members".
func OnAddChatMembers(h plugin.Host, fn func(plugin.Ctx, *AddChatMembersIn) (*AddChatMembersOut, error)) {
	h.Register(contract.OperationOf(&schema.AddChatMembers{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in AddChatMembersIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnBitableCreateRecord registers the implementation of "bitable_create_record".
func OnBitableCreateRecord(h plugin.Host, fn func(plugin.Ctx, *BitableCreateRecordIn) (*BitableCreateRecordOut, error)) {
	h.Register(contract.OperationOf(&schema.BitableCreateRecord{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BitableCreateRecordIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnBitableDeleteRecord registers the implementation of "bitable_delete_record".
func OnBitableDeleteRecord(h plugin.Host, fn func(plugin.Ctx, *BitableDeleteRecordIn) (*BitableDeleteRecordOut, error)) {
	h.Register(contract.OperationOf(&schema.BitableDeleteRecord{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BitableDeleteRecordIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnBitableListRecords registers the implementation of "bitable_list_records".
func OnBitableListRecords(h plugin.Host, fn func(plugin.Ctx, *BitableListRecordsIn) (*BitableListRecordsOut, error)) {
	h.Register(contract.OperationOf(&schema.BitableListRecords{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BitableListRecordsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnBitableUpdateRecord registers the implementation of "bitable_update_record".
func OnBitableUpdateRecord(h plugin.Host, fn func(plugin.Ctx, *BitableUpdateRecordIn) (*BitableUpdateRecordOut, error)) {
	h.Register(contract.OperationOf(&schema.BitableUpdateRecord{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BitableUpdateRecordIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCall registers the implementation of "call".
func OnCall(h plugin.Host, fn func(plugin.Ctx, *CallIn) (*CallOut, error)) {
	h.Register(contract.OperationOf(&schema.Call{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CallIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCreateChat registers the implementation of "create_chat".
func OnCreateChat(h plugin.Host, fn func(plugin.Ctx, *CreateChatIn) (*CreateChatOut, error)) {
	h.Register(contract.OperationOf(&schema.CreateChat{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CreateChatIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDocxAppend registers the implementation of "docx_append".
func OnDocxAppend(h plugin.Host, fn func(plugin.Ctx, *DocxAppendIn) (*DocxAppendOut, error)) {
	h.Register(contract.OperationOf(&schema.DocxAppend{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DocxAppendIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDocxCreate registers the implementation of "docx_create".
func OnDocxCreate(h plugin.Host, fn func(plugin.Ctx, *DocxCreateIn) (*DocxCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.DocxCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DocxCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDriveUpload registers the implementation of "drive_upload".
func OnDriveUpload(h plugin.Host, fn func(plugin.Ctx, *DriveUploadIn) (*DriveUploadOut, error)) {
	h.Register(contract.OperationOf(&schema.DriveUpload{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DriveUploadIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnGetUser registers the implementation of "get_user".
func OnGetUser(h plugin.Host, fn func(plugin.Ctx, *GetUserIn) (*GetUserOut, error)) {
	h.Register(contract.OperationOf(&schema.GetUser{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in GetUserIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnListChats registers the implementation of "list_chats".
func OnListChats(h plugin.Host, fn func(plugin.Ctx, *ListChatsIn) (*ListChatsOut, error)) {
	h.Register(contract.OperationOf(&schema.ListChats{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ListChatsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnRecallMessage registers the implementation of "recall_message".
func OnRecallMessage(h plugin.Host, fn func(plugin.Ctx, *RecallMessageIn) (*RecallMessageOut, error)) {
	h.Register(contract.OperationOf(&schema.RecallMessage{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in RecallMessageIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnReplyMessage registers the implementation of "reply_message".
func OnReplyMessage(h plugin.Host, fn func(plugin.Ctx, *ReplyMessageIn) (*ReplyMessageOut, error)) {
	h.Register(contract.OperationOf(&schema.ReplyMessage{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ReplyMessageIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSendCard registers the implementation of "send_card".
func OnSendCard(h plugin.Host, fn func(plugin.Ctx, *SendCardIn) (*SendCardOut, error)) {
	h.Register(contract.OperationOf(&schema.SendCard{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SendCardIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSendFile registers the implementation of "send_file".
func OnSendFile(h plugin.Host, fn func(plugin.Ctx, *SendFileIn) (*SendFileOut, error)) {
	h.Register(contract.OperationOf(&schema.SendFile{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SendFileIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSendImage registers the implementation of "send_image".
func OnSendImage(h plugin.Host, fn func(plugin.Ctx, *SendImageIn) (*SendImageOut, error)) {
	h.Register(contract.OperationOf(&schema.SendImage{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SendImageIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSendMarkdown registers the implementation of "send_markdown".
func OnSendMarkdown(h plugin.Host, fn func(plugin.Ctx, *SendMarkdownIn) (*SendMarkdownOut, error)) {
	h.Register(contract.OperationOf(&schema.SendMarkdown{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SendMarkdownIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSendText registers the implementation of "send_text".
func OnSendText(h plugin.Host, fn func(plugin.Ctx, *SendTextIn) (*SendTextOut, error)) {
	h.Register(contract.OperationOf(&schema.SendText{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SendTextIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnUploadFile registers the implementation of "upload_file".
func OnUploadFile(h plugin.Host, fn func(plugin.Ctx, *UploadFileIn) (*UploadFileOut, error)) {
	h.Register(contract.OperationOf(&schema.UploadFile{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in UploadFileIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnUploadImage registers the implementation of "upload_image".
func OnUploadImage(h plugin.Host, fn func(plugin.Ctx, *UploadImageIn) (*UploadImageOut, error)) {
	h.Register(contract.OperationOf(&schema.UploadImage{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in UploadImageIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
