// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/feishu/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

type AddChatMembersIn struct {
	ChatID      string   `json:"chat_id" sokel:"chat_id"`
	UserOpenIDs []string `json:"user_open_ids" sokel:"user_open_ids"`
}

type AddChatMembersOut struct {
	InvalidIDs []string `json:"invalid_ids" sokel:"invalid_ids"`
}

type BitableCreateRecordIn struct {
	AppToken string         `json:"app_token" sokel:"app_token"`
	TableID  string         `json:"table_id" sokel:"table_id"`
	Fields   map[string]any `json:"fields" sokel:"fields"`
}

type BitableCreateRecordOut struct {
	RecordID string `json:"record_id" sokel:"record_id"`
}

type BitableDeleteRecordIn struct {
	AppToken string `json:"app_token" sokel:"app_token"`
	TableID  string `json:"table_id" sokel:"table_id"`
	RecordID string `json:"record_id" sokel:"record_id"`
}

type BitableDeleteRecordOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type BitableListRecordsIn struct {
	AppToken  string `json:"app_token" sokel:"app_token"`
	TableID   string `json:"table_id" sokel:"table_id"`
	Filter    string `json:"filter" sokel:"filter"`
	PageSize  int    `json:"page_size" sokel:"page_size"`
	PageToken string `json:"page_token" sokel:"page_token"`
}

type BitableListRecordsOut struct {
	Records   []schema.BitableRecord `json:"records" sokel:"records"`
	Total     int                    `json:"total" sokel:"total"`
	PageToken string                 `json:"page_token" sokel:"page_token"`
	HasMore   bool                   `json:"has_more" sokel:"has_more"`
}

type BitableUpdateRecordIn struct {
	AppToken string         `json:"app_token" sokel:"app_token"`
	TableID  string         `json:"table_id" sokel:"table_id"`
	RecordID string         `json:"record_id" sokel:"record_id"`
	Fields   map[string]any `json:"fields" sokel:"fields"`
}

type BitableUpdateRecordOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type CallIn struct {
	Method string         `json:"method" sokel:"method"`
	Path   string         `json:"path" sokel:"path"`
	Body   map[string]any `json:"body" sokel:"body"`
}

type CallOut struct {
	Code int    `json:"code" sokel:"code"`
	Msg  string `json:"msg" sokel:"msg"`
	Data any    `json:"data" sokel:"data"`
}

type CreateChatIn struct {
	Name        string   `json:"name" sokel:"name"`
	Description string   `json:"description" sokel:"description"`
	UserOpenIDs []string `json:"user_open_ids" sokel:"user_open_ids"`
}

type CreateChatOut struct {
	ChatID string `json:"chat_id" sokel:"chat_id"`
}

type DocxAppendIn struct {
	DocumentID string `json:"document_id" sokel:"document_id"`
	Markdown   string `json:"markdown" sokel:"markdown"`
}

type DocxAppendOut struct {
	BlockCount int `json:"block_count" sokel:"block_count"`
}

type DocxCreateIn struct {
	Title       string `json:"title" sokel:"title"`
	FolderToken string `json:"folder_token" sokel:"folder_token"`
	Markdown    string `json:"markdown" sokel:"markdown"`
}

type DocxCreateOut struct {
	DocumentID string `json:"document_id" sokel:"document_id"`
	URL        string `json:"url" sokel:"url"`
}

type DriveUploadIn struct {
	File        *plugin.File `json:"file" sokel:"file"`
	FolderToken string       `json:"folder_token" sokel:"folder_token"`
}

type DriveUploadOut struct {
	FileToken string `json:"file_token" sokel:"file_token"`
	URL       string `json:"url" sokel:"url"`
}

type GetUserIn struct {
	Email  string `json:"email" sokel:"email"`
	Mobile string `json:"mobile" sokel:"mobile"`
}

type GetUserOut struct {
	OpenID string `json:"open_id" sokel:"open_id"`
	UserID string `json:"user_id" sokel:"user_id"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	BotName string `json:"bot_name" sokel:"bot_name"`
	Message string `json:"message" sokel:"message"`
}

type ListChatsIn struct {
	PageToken string `json:"page_token" sokel:"page_token"`
}

type ListChatsOut struct {
	Chats     []schema.Chat `json:"chats" sokel:"chats"`
	PageToken string        `json:"page_token" sokel:"page_token"`
	HasMore   bool          `json:"has_more" sokel:"has_more"`
}

type RecallMessageIn struct {
	MessageID string `json:"message_id" sokel:"message_id"`
}

type RecallMessageOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type ReplyMessageIn struct {
	MessageID string `json:"message_id" sokel:"message_id"`
	Text      string `json:"text" sokel:"text"`
	Markdown  string `json:"markdown" sokel:"markdown"`
}

type ReplyMessageOut struct {
	MessageID string `json:"message_id" sokel:"message_id"`
	ChatID    string `json:"chat_id" sokel:"chat_id"`
}

type SendCardIn struct {
	ReceiveID     string         `json:"receive_id" sokel:"receive_id"`
	ReceiveIDType string         `json:"receive_id_type" sokel:"receive_id_type"`
	Card          map[string]any `json:"card" sokel:"card"`
}

type SendCardOut struct {
	MessageID string `json:"message_id" sokel:"message_id"`
	ChatID    string `json:"chat_id" sokel:"chat_id"`
}

type SendFileIn struct {
	ReceiveID     string       `json:"receive_id" sokel:"receive_id"`
	ReceiveIDType string       `json:"receive_id_type" sokel:"receive_id_type"`
	File          *plugin.File `json:"file" sokel:"file"`
}

type SendFileOut struct {
	MessageID string `json:"message_id" sokel:"message_id"`
	ChatID    string `json:"chat_id" sokel:"chat_id"`
	FileKey   string `json:"file_key" sokel:"file_key"`
}

type SendImageIn struct {
	ReceiveID     string       `json:"receive_id" sokel:"receive_id"`
	ReceiveIDType string       `json:"receive_id_type" sokel:"receive_id_type"`
	Image         *plugin.File `json:"image" sokel:"image"`
}

type SendImageOut struct {
	MessageID string `json:"message_id" sokel:"message_id"`
	ChatID    string `json:"chat_id" sokel:"chat_id"`
	ImageKey  string `json:"image_key" sokel:"image_key"`
}

type SendMarkdownIn struct {
	ReceiveID     string `json:"receive_id" sokel:"receive_id"`
	ReceiveIDType string `json:"receive_id_type" sokel:"receive_id_type"`
	Title         string `json:"title" sokel:"title"`
	TitleColor    string `json:"title_color" sokel:"title_color"`
	Markdown      string `json:"markdown" sokel:"markdown"`
}

type SendMarkdownOut struct {
	MessageID string `json:"message_id" sokel:"message_id"`
	ChatID    string `json:"chat_id" sokel:"chat_id"`
}

type SendTextIn struct {
	ReceiveID     string `json:"receive_id" sokel:"receive_id"`
	ReceiveIDType string `json:"receive_id_type" sokel:"receive_id_type"`
	Text          string `json:"text" sokel:"text"`
}

type SendTextOut struct {
	MessageID string `json:"message_id" sokel:"message_id"`
	ChatID    string `json:"chat_id" sokel:"chat_id"`
}

type UploadFileIn struct {
	File *plugin.File `json:"file" sokel:"file"`
}

type UploadFileOut struct {
	FileKey string `json:"file_key" sokel:"file_key"`
}

type UploadImageIn struct {
	Image *plugin.File `json:"image" sokel:"image"`
}

type UploadImageOut struct {
	ImageKey string `json:"image_key" sokel:"image_key"`
}
