// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	EsURL     string `sokel:"es_url" label:"Elasticsearch 地址"`
	APIKey    string `sokel:"api_key,optional" label:"API Key" secret:"true"`
	Namespace string `sokel:"namespace,optional" label:"索引命名空间" default:"sokel"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "es_url",
			Label:    "Elasticsearch 地址",
			Type:     contract.ParamType("text"),
			Required: true,
		},
		{
			Name:  "api_key",
			Label: "API Key",
			Type:  contract.ParamType("secret"),
		},
		{
			Name:    "namespace",
			Label:   "索引命名空间",
			Type:    contract.ParamType("text"),
			Default: "sokel",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
