// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/discord/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnDiscordMessageDelete registers the implementation of "discord_message_delete".
func OnDiscordMessageDelete(h plugin.Host, fn func(plugin.Ctx, *DiscordMessageDeleteIn) (*DiscordMessageDeleteOut, error)) {
	h.Register(contract.OperationOf(&schema.MessageDelete{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DiscordMessageDeleteIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDiscordMessageSend registers the implementation of "discord_message_send".
func OnDiscordMessageSend(h plugin.Host, fn func(plugin.Ctx, *DiscordMessageSendIn) (*DiscordMessageSendOut, error)) {
	h.Register(contract.OperationOf(&schema.MessageSend{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DiscordMessageSendIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
