// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

type DiscordMessageDeleteIn struct {
	MessageID string `json:"message_id" sokel:"message_id"`
	ThreadID  string `json:"thread_id" sokel:"thread_id"`
}

type DiscordMessageDeleteOut struct {
	Deleted bool `json:"deleted" sokel:"deleted"`
}

type DiscordMessageSendIn struct {
	Content     string            `json:"content" sokel:"content"`
	Title       string            `json:"title" sokel:"title"`
	Description string            `json:"description" sokel:"description"`
	URL         string            `json:"url" sokel:"url"`
	Color       string            `json:"color" sokel:"color"`
	ImageURL    string            `json:"image_url" sokel:"image_url"`
	Fields      map[string]string `json:"fields" sokel:"fields"`
	Footer      string            `json:"footer" sokel:"footer"`
	Files       []*plugin.File    `json:"files" sokel:"files"`
	Username    string            `json:"username" sokel:"username"`
	ThreadID    string            `json:"thread_id" sokel:"thread_id"`
}

type DiscordMessageSendOut struct {
	ID        string `json:"id" sokel:"id"`
	ChannelID string `json:"channel_id" sokel:"channel_id"`
	URL       string `json:"url" sokel:"url"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
	Channel string `json:"channel" sokel:"channel"`
}
