// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	BaseURL     string `sokel:"base_url" label:"地址"`
	Username    string `sokel:"username,optional" label:"用户名"`
	Password    string `sokel:"password,optional" label:"密码" secret:"true"`
	APIKey      string `sokel:"api_key,optional" label:"API Key" secret:"true"`
	TLSInsecure string `sokel:"tls_insecure,optional" label:"跳过证书校验"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "base_url",
			Label:    "地址",
			Type:     contract.ParamType("text"),
			Required: true,
			Desc:     "集群地址，如 https://es.internal:9200（带协议与端口）。多节点填其中一个即可",
		},
		{
			Name:  "username",
			Label: "用户名",
			Type:  contract.ParamType("text"),
			Desc:  "basic 认证；用 API Key 就留空",
		},
		{
			Name:  "password",
			Label: "密码",
			Type:  contract.ParamType("secret"),
		},
		{
			Name:  "api_key",
			Label: "API Key",
			Type:  contract.ParamType("secret"),
			Desc:  "Kibana → Stack Management → API Keys 生成的 encoded 值。填了它就不用用户名密码",
		},
		{
			Name:    "tls_insecure",
			Label:   "跳过证书校验",
			Type:    contract.ParamType("select"),
			Desc:    "自建集群用自签证书时选 on（连接仍加密，但不校验对端身份）。默认 off",
			Options: []contract.Option{{Value: "off", Label: "off"}, {Value: "on", Label: "on"}},
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
