// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/elasticsearch/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnAliasSwitch registers the implementation of "alias_switch".
func OnAliasSwitch(h plugin.Host, fn func(plugin.Ctx, *AliasSwitchIn) (*AliasSwitchOut, error)) {
	h.Register(contract.OperationOf(&schema.AliasSwitch{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in AliasSwitchIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnBulkIndex registers the implementation of "bulk_index".
func OnBulkIndex(h plugin.Host, fn func(plugin.Ctx, *BulkIndexIn) (*BulkIndexOut, error)) {
	h.Register(contract.OperationOf(&schema.BulkIndex{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BulkIndexIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCall registers the implementation of "call".
func OnCall(h plugin.Host, fn func(plugin.Ctx, *CallIn) (*CallOut, error)) {
	h.Register(contract.OperationOf(&schema.Call{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CallIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnClusterHealth registers the implementation of "cluster_health".
func OnClusterHealth(h plugin.Host, fn func(plugin.Ctx, *ClusterHealthIn) (*ClusterHealthOut, error)) {
	h.Register(contract.OperationOf(&schema.ClusterHealth{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ClusterHealthIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCount registers the implementation of "count".
func OnCount(h plugin.Host, fn func(plugin.Ctx, *CountIn) (*CountOut, error)) {
	h.Register(contract.OperationOf(&schema.Count{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CountIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDeleteByQuery registers the implementation of "delete_by_query".
func OnDeleteByQuery(h plugin.Host, fn func(plugin.Ctx, *DeleteByQueryIn) (*DeleteByQueryOut, error)) {
	h.Register(contract.OperationOf(&schema.DeleteByQuery{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DeleteByQueryIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDocDelete registers the implementation of "doc_delete".
func OnDocDelete(h plugin.Host, fn func(plugin.Ctx, *DocDeleteIn) (*DocDeleteOut, error)) {
	h.Register(contract.OperationOf(&schema.DocDelete{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DocDeleteIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDocGet registers the implementation of "doc_get".
func OnDocGet(h plugin.Host, fn func(plugin.Ctx, *DocGetIn) (*DocGetOut, error)) {
	h.Register(contract.OperationOf(&schema.DocGet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DocGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDocIndex registers the implementation of "doc_index".
func OnDocIndex(h plugin.Host, fn func(plugin.Ctx, *DocIndexIn) (*DocIndexOut, error)) {
	h.Register(contract.OperationOf(&schema.DocIndex{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DocIndexIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDocUpdate registers the implementation of "doc_update".
func OnDocUpdate(h plugin.Host, fn func(plugin.Ctx, *DocUpdateIn) (*DocUpdateOut, error)) {
	h.Register(contract.OperationOf(&schema.DocUpdate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DocUpdateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIndexCreate registers the implementation of "index_create".
func OnIndexCreate(h plugin.Host, fn func(plugin.Ctx, *IndexCreateIn) (*IndexCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.IndexCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IndexCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIndexDelete registers the implementation of "index_delete".
func OnIndexDelete(h plugin.Host, fn func(plugin.Ctx, *IndexDeleteIn) (*IndexDeleteOut, error)) {
	h.Register(contract.OperationOf(&schema.IndexDelete{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IndexDeleteIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIndicesList registers the implementation of "indices_list".
func OnIndicesList(h plugin.Host, fn func(plugin.Ctx, *IndicesListIn) (*IndicesListOut, error)) {
	h.Register(contract.OperationOf(&schema.IndicesList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IndicesListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMappingGet registers the implementation of "mapping_get".
func OnMappingGet(h plugin.Host, fn func(plugin.Ctx, *MappingGetIn) (*MappingGetOut, error)) {
	h.Register(contract.OperationOf(&schema.MappingGet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MappingGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMappingPut registers the implementation of "mapping_put".
func OnMappingPut(h plugin.Host, fn func(plugin.Ctx, *MappingPutIn) (*MappingPutOut, error)) {
	h.Register(contract.OperationOf(&schema.MappingPut{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MappingPutIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnReindex registers the implementation of "reindex".
func OnReindex(h plugin.Host, fn func(plugin.Ctx, *ReindexIn) (*ReindexOut, error)) {
	h.Register(contract.OperationOf(&schema.Reindex{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ReindexIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSearch registers the implementation of "search".
func OnSearch(h plugin.Host, fn func(plugin.Ctx, *SearchIn) (*SearchOut, error)) {
	h.Register(contract.OperationOf(&schema.Search{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SearchIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
