// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/elasticsearch/schema"
)

type AliasSwitchIn struct {
	Alias      string `json:"alias" sokel:"alias"`
	ToIndex    string `json:"to_index" sokel:"to_index"`
	KeepOthers bool   `json:"keep_others" sokel:"keep_others"`
}

type AliasSwitchOut struct {
	OK          bool     `json:"ok" sokel:"ok"`
	RemovedFrom []string `json:"removed_from" sokel:"removed_from"`
}

type BulkIndexIn struct {
	Index     string `json:"index" sokel:"index"`
	Documents []any  `json:"documents" sokel:"documents"`
	IDField   string `json:"id_field" sokel:"id_field"`
	Refresh   bool   `json:"refresh" sokel:"refresh"`
}

type BulkIndexOut struct {
	Indexed int      `json:"indexed" sokel:"indexed"`
	Failed  int      `json:"failed" sokel:"failed"`
	Errors  []string `json:"errors" sokel:"errors"`
	TookMs  int      `json:"took_ms" sokel:"took_ms"`
}

type CallIn struct {
	Method string         `json:"method" sokel:"method"`
	Path   string         `json:"path" sokel:"path"`
	Body   map[string]any `json:"body" sokel:"body"`
}

type CallOut struct {
	Status int `json:"status" sokel:"status"`
	Data   any `json:"data" sokel:"data"`
}

type ClusterHealthIn struct {
}

type ClusterHealthOut struct {
	Status           string `json:"status" sokel:"status"`
	ClusterName      string `json:"cluster_name" sokel:"cluster_name"`
	Nodes            int    `json:"nodes" sokel:"nodes"`
	ActiveShards     int    `json:"active_shards" sokel:"active_shards"`
	UnassignedShards int    `json:"unassigned_shards" sokel:"unassigned_shards"`
}

type CountIn struct {
	Index string         `json:"index" sokel:"index"`
	Query map[string]any `json:"query" sokel:"query"`
	Q     string         `json:"q" sokel:"q"`
}

type CountOut struct {
	Count int `json:"count" sokel:"count"`
}

type DeleteByQueryIn struct {
	Index string         `json:"index" sokel:"index"`
	Query map[string]any `json:"query" sokel:"query"`
}

type DeleteByQueryOut struct {
	Deleted int `json:"deleted" sokel:"deleted"`
	TookMs  int `json:"took_ms" sokel:"took_ms"`
}

type DocDeleteIn struct {
	Index   string `json:"index" sokel:"index"`
	ID      string `json:"id" sokel:"id"`
	Refresh bool   `json:"refresh" sokel:"refresh"`
}

type DocDeleteOut struct {
	Deleted bool `json:"deleted" sokel:"deleted"`
}

type DocGetIn struct {
	Index string `json:"index" sokel:"index"`
	ID    string `json:"id" sokel:"id"`
}

type DocGetOut struct {
	Found   bool           `json:"found" sokel:"found"`
	Source  map[string]any `json:"source" sokel:"source"`
	Version int            `json:"version" sokel:"version"`
}

type DocIndexIn struct {
	Index    string         `json:"index" sokel:"index"`
	Document map[string]any `json:"document" sokel:"document"`
	ID       string         `json:"id" sokel:"id"`
	Refresh  bool           `json:"refresh" sokel:"refresh"`
}

type DocIndexOut struct {
	ID      string `json:"id" sokel:"id"`
	Result  string `json:"result" sokel:"result"`
	Version int    `json:"version" sokel:"version"`
}

type DocUpdateIn struct {
	Index   string         `json:"index" sokel:"index"`
	ID      string         `json:"id" sokel:"id"`
	Doc     map[string]any `json:"doc" sokel:"doc"`
	Upsert  bool           `json:"upsert" sokel:"upsert"`
	Refresh bool           `json:"refresh" sokel:"refresh"`
}

type DocUpdateOut struct {
	Result  string `json:"result" sokel:"result"`
	Version int    `json:"version" sokel:"version"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK           bool   `json:"ok" sokel:"ok"`
	Version      string `json:"version" sokel:"version"`
	Distribution string `json:"distribution" sokel:"distribution"`
	ClusterName  string `json:"cluster_name" sokel:"cluster_name"`
	Status       string `json:"status" sokel:"status"`
	Message      string `json:"message" sokel:"message"`
}

type IndexCreateIn struct {
	Name     string         `json:"name" sokel:"name"`
	Mappings map[string]any `json:"mappings" sokel:"mappings"`
	Settings map[string]any `json:"settings" sokel:"settings"`
}

type IndexCreateOut struct {
	Created bool `json:"created" sokel:"created"`
	Existed bool `json:"existed" sokel:"existed"`
}

type IndexDeleteIn struct {
	Name string `json:"name" sokel:"name"`
}

type IndexDeleteOut struct {
	Deleted bool `json:"deleted" sokel:"deleted"`
}

type IndicesListIn struct {
	Pattern string `json:"pattern" sokel:"pattern"`
}

type IndicesListOut struct {
	Indices []schema.IndexInfo `json:"indices" sokel:"indices"`
	Count   int                `json:"count" sokel:"count"`
}

type MappingGetIn struct {
	Index string `json:"index" sokel:"index"`
}

type MappingGetOut struct {
	Mappings map[string]any `json:"mappings" sokel:"mappings"`
}

type MappingPutIn struct {
	Index      string         `json:"index" sokel:"index"`
	Properties map[string]any `json:"properties" sokel:"properties"`
}

type MappingPutOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type ReindexIn struct {
	Source string         `json:"source" sokel:"source"`
	Dest   string         `json:"dest" sokel:"dest"`
	Query  map[string]any `json:"query" sokel:"query"`
	Async  bool           `json:"async" sokel:"async"`
}

type ReindexOut struct {
	Created  int    `json:"created" sokel:"created"`
	Failures int    `json:"failures" sokel:"failures"`
	Task     string `json:"task" sokel:"task"`
	TookMs   int    `json:"took_ms" sokel:"took_ms"`
}

type SearchIn struct {
	Index        string         `json:"index" sokel:"index"`
	Query        map[string]any `json:"query" sokel:"query"`
	Q            string         `json:"q" sokel:"q"`
	Size         int            `json:"size" sokel:"size"`
	From         int            `json:"from" sokel:"from"`
	Sort         []string       `json:"sort" sokel:"sort"`
	SourceFields []string       `json:"source_fields" sokel:"source_fields"`
	Aggs         map[string]any `json:"aggs" sokel:"aggs"`
	ExactTotal   bool           `json:"exact_total" sokel:"exact_total"`
}

type SearchOut struct {
	Total             int            `json:"total" sokel:"total"`
	TotalIsLowerBound bool           `json:"total_is_lower_bound" sokel:"total_is_lower_bound"`
	Hits              []schema.Hit   `json:"hits" sokel:"hits"`
	Count             int            `json:"count" sokel:"count"`
	Aggregations      map[string]any `json:"aggregations" sokel:"aggregations"`
	TookMs            int            `json:"took_ms" sokel:"took_ms"`
}
