// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	Identifier  string `sokel:"identifier" label:"账号"`
	AppPassword string `sokel:"app_password" label:"应用专用密码" secret:"true"`
	PdsURL      string `sokel:"pds_url,optional" label:"服务地址"`
	Proxy       string `sokel:"proxy,optional" label:"出站代理"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "identifier",
			Label:    "账号",
			Type:     contract.ParamType("text"),
			Required: true,
			Desc:     "完整 handle（如 acme.bsky.social）或邮箱",
		},
		{
			Name:     "app_password",
			Label:    "应用专用密码",
			Type:     contract.ParamType("secret"),
			Required: true,
			Desc:     "Bluesky 设置 → Privacy and Security → App Passwords 里生成，形如 xxxx-xxxx-xxxx-xxxx。**别用登录密码**：应用密码可单独撤销，且拿不到改密码/删账号这类权限",
		},
		{
			Name:  "pds_url",
			Label: "服务地址",
			Type:  contract.ParamType("text"),
			Desc:  "留空用 https://bsky.social；自建 PDS 才需要改",
		},
		{
			Name:  "proxy",
			Label: "出站代理",
			Type:  contract.ParamType("text"),
			Desc:  "如 http://127.0.0.1:7897；部署环境直连不了 bsky.social 时必填",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
