// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/bluesky/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnBskyPostCreate registers the implementation of "bsky_post_create".
func OnBskyPostCreate(h plugin.Host, fn func(plugin.Ctx, *BskyPostCreateIn) (*BskyPostCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.PostCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BskyPostCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnBskyPostDelete registers the implementation of "bsky_post_delete".
func OnBskyPostDelete(h plugin.Host, fn func(plugin.Ctx, *BskyPostDeleteIn) (*BskyPostDeleteOut, error)) {
	h.Register(contract.OperationOf(&schema.PostDelete{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BskyPostDeleteIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnBskyPostThread registers the implementation of "bsky_post_thread".
func OnBskyPostThread(h plugin.Host, fn func(plugin.Ctx, *BskyPostThreadIn) (*BskyPostThreadOut, error)) {
	h.Register(contract.OperationOf(&schema.PostThread{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BskyPostThreadIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
