// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

type BskyPostCreateIn struct {
	Text        string         `json:"text" sokel:"text"`
	ReplyToURI  string         `json:"reply_to_uri" sokel:"reply_to_uri"`
	Images      []*plugin.File `json:"images" sokel:"images"`
	ImageAlts   []string       `json:"image_alts" sokel:"image_alts"`
	LinkCardURL string         `json:"link_card_url" sokel:"link_card_url"`
	Langs       string         `json:"langs" sokel:"langs"`
}

type BskyPostCreateOut struct {
	URI string `json:"uri" sokel:"uri"`
	Cid string `json:"cid" sokel:"cid"`
	URL string `json:"url" sokel:"url"`
}

type BskyPostDeleteIn struct {
	URI string `json:"uri" sokel:"uri"`
}

type BskyPostDeleteOut struct {
	Deleted bool `json:"deleted" sokel:"deleted"`
}

type BskyPostThreadIn struct {
	Texts      []string       `json:"texts" sokel:"texts"`
	ReplyToURI string         `json:"reply_to_uri" sokel:"reply_to_uri"`
	Images     []*plugin.File `json:"images" sokel:"images"`
	IntervalMs int            `json:"interval_ms" sokel:"interval_ms"`
	Langs      string         `json:"langs" sokel:"langs"`
}

type BskyPostThreadOut struct {
	Uris    []string `json:"uris" sokel:"uris"`
	RootURI string   `json:"root_uri" sokel:"root_uri"`
	RootURL string   `json:"root_url" sokel:"root_url"`
	Count   int      `json:"count" sokel:"count"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
	Handle  string `json:"handle" sokel:"handle"`
}
