// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	SmsAppid   string `sokel:"sms_appid,optional" label:"国内短信 AppID"`
	SmsAppkey  string `sokel:"sms_appkey,optional" label:"国内短信 AppKey" secret:"true"`
	IntlAppid  string `sokel:"intl_appid,optional" label:"国际短信 AppID"`
	IntlAppkey string `sokel:"intl_appkey,optional" label:"国际短信 AppKey" secret:"true"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:  "sms_appid",
			Label: "国内短信 AppID",
			Type:  contract.ParamType("text"),
			Desc:  "控制台「短信」应用的 AppID（纯数字）。只用国际短信可留空",
		},
		{
			Name:  "sms_appkey",
			Label: "国内短信 AppKey",
			Type:  contract.ParamType("secret"),
		},
		{
			Name:  "intl_appid",
			Label: "国际短信 AppID",
			Type:  contract.ParamType("text"),
			Desc:  "控制台「国际短信」应用的 AppID。只用国内短信可留空",
		},
		{
			Name:  "intl_appkey",
			Label: "国际短信 AppKey",
			Type:  contract.ParamType("secret"),
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
