// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/submail/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnBalance registers the implementation of "balance".
func OnBalance(h plugin.Host, fn func(plugin.Ctx, *BalanceIn) (*BalanceOut, error)) {
	h.Register(contract.OperationOf(&schema.Balance{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BalanceIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIntlSend registers the implementation of "intl_send".
func OnIntlSend(h plugin.Host, fn func(plugin.Ctx, *IntlSendIn) (*IntlSendOut, error)) {
	h.Register(contract.OperationOf(&schema.IntlSend{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IntlSendIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIntlXsend registers the implementation of "intl_xsend".
func OnIntlXsend(h plugin.Host, fn func(plugin.Ctx, *IntlXsendIn) (*IntlXsendOut, error)) {
	h.Register(contract.OperationOf(&schema.IntlXsend{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IntlXsendIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSmsLog registers the implementation of "sms_log".
func OnSmsLog(h plugin.Host, fn func(plugin.Ctx, *SmsLogIn) (*SmsLogOut, error)) {
	h.Register(contract.OperationOf(&schema.SmsLog{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SmsLogIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSmsSend registers the implementation of "sms_send".
func OnSmsSend(h plugin.Host, fn func(plugin.Ctx, *SmsSendIn) (*SmsSendOut, error)) {
	h.Register(contract.OperationOf(&schema.SmsSend{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SmsSendIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSmsXsend registers the implementation of "sms_xsend".
func OnSmsXsend(h plugin.Host, fn func(plugin.Ctx, *SmsXsendIn) (*SmsXsendOut, error)) {
	h.Register(contract.OperationOf(&schema.SmsXsend{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SmsXsendIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
