// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

type BalanceIn struct {
}

type BalanceOut struct {
	Balance       int     `json:"balance" sokel:"balance"`
	Transactional int     `json:"transactional" sokel:"transactional"`
	IntlBalance   float64 `json:"intl_balance" sokel:"intl_balance"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
}

type IntlSendIn struct {
	To      string `json:"to" sokel:"to"`
	Content string `json:"content" sokel:"content"`
}

type IntlSendOut struct {
	SendID string `json:"send_id" sokel:"send_id"`
	Fee    int    `json:"fee" sokel:"fee"`
}

type IntlXsendIn struct {
	To      string         `json:"to" sokel:"to"`
	Project string         `json:"project" sokel:"project"`
	Vars    map[string]any `json:"vars" sokel:"vars"`
}

type IntlXsendOut struct {
	SendID string `json:"send_id" sokel:"send_id"`
	Fee    int    `json:"fee" sokel:"fee"`
}

type SmsLogIn struct {
	SendID string `json:"send_id" sokel:"send_id"`
	To     string `json:"to" sokel:"to"`
	Days   int    `json:"days" sokel:"days"`
}

type SmsLogOut struct {
	Logs  []any `json:"logs" sokel:"logs"`
	Count int   `json:"count" sokel:"count"`
}

type SmsSendIn struct {
	To      string `json:"to" sokel:"to"`
	Content string `json:"content" sokel:"content"`
}

type SmsSendOut struct {
	SendID string `json:"send_id" sokel:"send_id"`
	Fee    int    `json:"fee" sokel:"fee"`
}

type SmsXsendIn struct {
	To      string         `json:"to" sokel:"to"`
	Project string         `json:"project" sokel:"project"`
	Vars    map[string]any `json:"vars" sokel:"vars"`
}

type SmsXsendOut struct {
	SendID string `json:"send_id" sokel:"send_id"`
	Fee    int    `json:"fee" sokel:"fee"`
}
