// Code generated by gen-schema. DO NOT EDIT.
//
// TuShare 接口 181–221 的契约。改这里没用——改 catalog/tushare-apis.json 或生成器，
// 然后 go run ./cmd/gen-schema && go generate ./...

package schema

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/contract/field"
)

// ApiStkSurv 机构调研表（stk_surv）
// 目录：股票数据/特色数据/机构调研数据
type ApiStkSurv struct{}

func (ApiStkSurv) Meta() contract.Meta {
	return contract.Meta{ID: "stk_surv", Label: "机构调研表", Desc: "获取上市公司机构调研记录数据 限量：单次最大获取400条数据，可循环或分页提取 积分：用户积5000积分可使用 输入参数 名称 类型 必选 描述 ts_code str N 股票代码 trade_date str N 调研日期 start_date str N 调研开始日期 end_date str N 调研结束日期 输出参数 名称 类型 默认显示 描述 ts_code str Y 股票代码 name str Y 股票名称 surv_date str Y 调研日期 fund_visitors str Y 机构参与人员 rece_place str Y 接待地点 rece_mode str Y", TimeoutSec: 90}
}

func (ApiStkSurv) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码").Desc("股票代码").Optional(),
		field.String("trade_date").Label("调研日期").Desc("调研日期").Optional(),
		field.String("start_date").Label("调研开始日期").Desc("调研开始日期").Optional(),
		field.String("end_date").Label("调研结束日期").Desc("调研结束日期").Optional(),
	}
}

func (ApiStkSurv) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []StkSurvRecord{}).Label("机构调研表"),
		field.Int("count").Label("本批条数"),
	}
}

// StkSurvRecord 机构调研表 的一条记录。
type StkSurvRecord struct {
	Ts_code       string `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	Name          string `json:"name" sokel:"name" label:"股票名称"`
	Surv_date     string `json:"surv_date" sokel:"surv_date" label:"调研日期"`
	Fund_visitors string `json:"fund_visitors" sokel:"fund_visitors" label:"机构参与人员"`
	Rece_place    string `json:"rece_place" sokel:"rece_place" label:"接待地点"`
	Rece_mode     string `json:"rece_mode" sokel:"rece_mode" label:"接待方式"`
	Rece_org      string `json:"rece_org" sokel:"rece_org" label:"接待的公司"`
	Org_type      string `json:"org_type" sokel:"org_type" label:"接待公司类型"`
	Comp_rece     string `json:"comp_rece" sokel:"comp_rece" label:"上市公司接待人员"`
	Content       string `json:"content" sokel:"content" label:"调研内容"`
}

// ApiStkWeekMonthAdj 股票周/月线行情(复权--每日更新)（stk_week_month_adj）
// 目录：股票数据/行情数据/周/月线复权行情(每日更新)
type ApiStkWeekMonthAdj struct{}

func (ApiStkWeekMonthAdj) Meta() contract.Meta {
	return contract.Meta{ID: "stk_week_month_adj", Label: "股票周/月线行情(复权--每日更新)", Desc: "股票周/月线行情(复权--每日更新) 限量：单次最大6000,可使用交易日期循环提取，总量不限制 积分：用户需要至少2000积分才可以调取，具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 ts_code str N TS代码 trade_date str N 交易日期（格式：YYYYMMDD，每周或每月最后一天的日期） start_date str N 开始交易日期 end_date str N 结束交易日期 freq str Y 频率week周，month月 **输出参数** 名称 类型 默认显示 描述 ts_code str Y 股票代码 trade_date str Y 交易", TimeoutSec: 90}
}

func (ApiStkWeekMonthAdj) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("TS代码").Desc("TS代码").Optional(),
		field.String("trade_date").Label("交易日期（格式：YYYYMMDD，每周或每月最后一天的日期）").Desc("交易日期（格式：YYYYMMDD，每周或每月最后一天的日期）").Optional(),
		field.String("start_date").Label("开始交易日期").Desc("开始交易日期").Optional(),
		field.String("end_date").Label("结束交易日期").Desc("结束交易日期").Optional(),
		field.String("freq").Label("频率week周，month月").Desc("频率week周，month月"),
	}
}

func (ApiStkWeekMonthAdj) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []StkWeekMonthAdjRecord{}).Label("股票周/月线行情(复权--每日更新)"),
		field.Int("count").Label("本批条数"),
	}
}

// StkWeekMonthAdjRecord 股票周/月线行情(复权--每日更新) 的一条记录。
type StkWeekMonthAdjRecord struct {
	Ts_code    string  `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	Trade_date string  `json:"trade_date" sokel:"trade_date" label:"交易日期（每周五或者月末日期）"`
	End_date   string  `json:"end_date" sokel:"end_date" label:"计算截至日期"`
	Freq       string  `json:"freq" sokel:"freq" label:"频率(周week,月month)"`
	Open       float64 `json:"open" sokel:"open" label:"(周/月)开盘价"`
	High       float64 `json:"high" sokel:"high" label:"(周/月)最高价"`
	Low        float64 `json:"low" sokel:"low" label:"(周/月)最低价"`
	Close      float64 `json:"close" sokel:"close" label:"(周/月)收盘价"`
	Pre_close  float64 `json:"pre_close" sokel:"pre_close" label:"上一(周/月)收盘价【除权价，前复权】"`
	Open_qfq   float64 `json:"open_qfq" sokel:"open_qfq" label:"前复权(周/月)开盘价"`
	High_qfq   float64 `json:"high_qfq" sokel:"high_qfq" label:"前复权(周/月)最高价"`
	Low_qfq    float64 `json:"low_qfq" sokel:"low_qfq" label:"前复权(周/月)最低价"`
	Close_qfq  float64 `json:"close_qfq" sokel:"close_qfq" label:"前复权(周/月)收盘价"`
	Open_hfq   float64 `json:"open_hfq" sokel:"open_hfq" label:"后复权(周/月)开盘价"`
	High_hfq   float64 `json:"high_hfq" sokel:"high_hfq" label:"后复权(周/月)最高价"`
	Low_hfq    float64 `json:"low_hfq" sokel:"low_hfq" label:"后复权(周/月)最低价"`
	Close_hfq  float64 `json:"close_hfq" sokel:"close_hfq" label:"后复权(周/月)收盘价"`
	Vol        float64 `json:"vol" sokel:"vol" label:"(周/月)成交量"`
	Amount     float64 `json:"amount" sokel:"amount" label:"(周/月)成交额"`
	Change     float64 `json:"change" sokel:"change" label:"(周/月)涨跌额"`
	Pct_chg    float64 `json:"pct_chg" sokel:"pct_chg" label:"(周/月)涨跌幅 【基于除权后的昨收计算的涨跌幅：（今收-除权昨收）/除权昨收 】"`
}

// ApiStkWeeklyMonthly 股票周/月线行情(每日更新)（stk_weekly_monthly）
// 目录：股票数据/行情数据/周/月线行情(每日更新)
type ApiStkWeeklyMonthly struct{}

func (ApiStkWeeklyMonthly) Meta() contract.Meta {
	return contract.Meta{ID: "stk_weekly_monthly", Label: "股票周/月线行情(每日更新)", Desc: "股票周/月线行情(每日更新) 限量：单次最大6000,可使用交易日期循环提取，总量不限制 积分：用户需要至少2000积分才可以调取，具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 ts_code str N TS代码 trade_date str N 交易日期(格式：YYYYMMDD，每周或每月最后一天的日期） start_date str N 开始交易日期 end_date str N 结束交易日期 freq str Y 频率week周，month月 输出参数 名称 类型 默认显示 描述 ts_code str Y 股票代码 trade_date str Y 交易日期 end_d", TimeoutSec: 90}
}

func (ApiStkWeeklyMonthly) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("TS代码").Desc("TS代码").Optional(),
		field.String("trade_date").Label("交易日期(格式：YYYYMMDD，每周或每月最后一天的日期）").Desc("交易日期(格式：YYYYMMDD，每周或每月最后一天的日期）").Optional(),
		field.String("start_date").Label("开始交易日期").Desc("开始交易日期").Optional(),
		field.String("end_date").Label("结束交易日期").Desc("结束交易日期").Optional(),
		field.String("freq").Label("频率week周，month月").Desc("频率week周，month月"),
	}
}

func (ApiStkWeeklyMonthly) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []StkWeeklyMonthlyRecord{}).Label("股票周/月线行情(每日更新)"),
		field.Int("count").Label("本批条数"),
	}
}

// StkWeeklyMonthlyRecord 股票周/月线行情(每日更新) 的一条记录。
type StkWeeklyMonthlyRecord struct {
	Ts_code    string  `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	Trade_date string  `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	End_date   string  `json:"end_date" sokel:"end_date" label:"计算截至日期"`
	Freq       string  `json:"freq" sokel:"freq" label:"频率(周week,月month)"`
	Open       float64 `json:"open" sokel:"open" label:"(周/月)开盘价"`
	High       float64 `json:"high" sokel:"high" label:"(周/月)最高价"`
	Low        float64 `json:"low" sokel:"low" label:"(周/月)最低价"`
	Close      float64 `json:"close" sokel:"close" label:"(周/月)收盘价"`
	Pre_close  float64 `json:"pre_close" sokel:"pre_close" label:"上一(周/月)收盘价"`
	Vol        float64 `json:"vol" sokel:"vol" label:"(周/月)成交量"`
	Amount     float64 `json:"amount" sokel:"amount" label:"(周/月)成交额"`
	Change     float64 `json:"change" sokel:"change" label:"(周/月)涨跌额"`
	Pct_chg    float64 `json:"pct_chg" sokel:"pct_chg" label:"(周/月)涨跌幅(未复权,如果是复权请用 通用行情接口)"`
}

// ApiStockBasic 股票基础信息（stock_basic）
// 目录：股票数据/基础数据/股票列表
type ApiStockBasic struct{}

func (ApiStockBasic) Meta() contract.Meta {
	return contract.Meta{ID: "stock_basic", Label: "股票基础信息", Desc: "获取基础信息数据，包括股票代码、名称、上市日期、退市日期等 限量：每次最多返回6000行数据（覆盖全市场A股，会随股票总数增长而增加） 权限：2000积分起，每分钟请求50次。此接口是基础信息，调取一次就可以拉取完，建议保存倒本地存储后使用 输入参数 名称 类型 必选 描述 ts_code str N TS股票代码( 格式说明 ) name str N 名称 market str N 市场类别 （主板/创业板/科创板/CDR/北交所） list_status str N 上市状态 L上市 D退市 P暂停上市 G 未交易，默认是L exchange str N 交易所 SSE上交所 SZSE深交", TimeoutSec: 90}
}

func (ApiStockBasic) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("TS股票代码( 格式说明 )").Desc("TS股票代码( 格式说明 )").Optional(),
		field.String("name").Label("名称").Desc("名称").Optional(),
		field.String("market").Label("市场类别 （主板/创业板/科创板/CDR/北交所）").Desc("市场类别 （主板/创业板/科创板/CDR/北交所）").Optional(),
		field.String("list_status").Label("上市状态 L上市 D退市 P暂停上市 G 未交易，默认是L").Desc("上市状态 L上市 D退市 P暂停上市 G 未交易，默认是L").Optional(),
		field.String("exchange").Label("交易所 SSE上交所 SZSE深交所 BSE北交所").Desc("交易所 SSE上交所 SZSE深交所 BSE北交所").Optional(),
		field.String("is_hs").Label("是否沪深港通标的，N否 H沪股通 S深股通").Desc("是否沪深港通标的，N否 H沪股通 S深股通").Optional(),
	}
}

func (ApiStockBasic) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []StockBasicRecord{}).Label("股票基础信息"),
		field.Int("count").Label("本批条数"),
	}
}

// StockBasicRecord 股票基础信息 的一条记录。
type StockBasicRecord struct {
	Ts_code      string `json:"ts_code" sokel:"ts_code" label:"TS代码"`
	Symbol       string `json:"symbol" sokel:"symbol" label:"股票代码"`
	Name         string `json:"name" sokel:"name" label:"股票名称"`
	Area         string `json:"area" sokel:"area" label:"地域"`
	Industry     string `json:"industry" sokel:"industry" label:"所属行业"`
	Fullname     string `json:"fullname" sokel:"fullname" label:"股票全称"`
	Enname       string `json:"enname" sokel:"enname" label:"英文全称"`
	Cnspell      string `json:"cnspell" sokel:"cnspell" label:"拼音缩写"`
	Market       string `json:"market" sokel:"market" label:"市场类型（主板/创业板/科创板/CDR）"`
	Exchange     string `json:"exchange" sokel:"exchange" label:"交易所代码"`
	Curr_type    string `json:"curr_type" sokel:"curr_type" label:"交易货币"`
	List_status  string `json:"list_status" sokel:"list_status" label:"上市状态 L上市 D退市 G过会未交易 P暂停上市"`
	List_date    string `json:"list_date" sokel:"list_date" label:"上市日期"`
	Delist_date  string `json:"delist_date" sokel:"delist_date" label:"退市日期"`
	Is_hs        string `json:"is_hs" sokel:"is_hs" label:"是否沪深港通标的，N否 H沪股通 S深股通"`
	Act_name     string `json:"act_name" sokel:"act_name" label:"实控人名称"`
	Act_ent_type string `json:"act_ent_type" sokel:"act_ent_type" label:"实控人企业性质"`
}

// ApiStockCompany 上市公司基本信息（stock_company）
// 目录：股票数据/基础数据/上市公司基本信息
type ApiStockCompany struct{}

func (ApiStockCompany) Meta() contract.Meta {
	return contract.Meta{ID: "stock_company", Label: "上市公司基本信息", Desc: "获取上市公司基础信息，单次提取4500条，可以根据交易所分批提取 积分：用户需要至少120积分才可以调取，具体请参阅 积分获取办法 输入参数 名称 类型 必须 描述 ts_code str N 股票代码 exchange str N 交易所代码 ，SSE上交所 SZSE深交所 BSE北交所 输出参数 名称 类型 默认显示 描述 ts_code str Y 股票代码 com_name str Y 公司全称 com_id str Y 统一社会信用代码 exchange str Y 交易所代码 chairman str Y 法人代表 manager str Y 总经理 secretary str Y", TimeoutSec: 90}
}

func (ApiStockCompany) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码").Desc("股票代码").Optional(),
		field.String("exchange").Label("交易所代码 ，SSE上交所 SZSE深交所 BSE北交所").Desc("交易所代码 ，SSE上交所 SZSE深交所 BSE北交所").Optional(),
	}
}

func (ApiStockCompany) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []StockCompanyRecord{}).Label("上市公司基本信息"),
		field.Int("count").Label("本批条数"),
	}
}

// StockCompanyRecord 上市公司基本信息 的一条记录。
type StockCompanyRecord struct {
	Ts_code        string  `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	Com_name       string  `json:"com_name" sokel:"com_name" label:"公司全称"`
	Com_id         string  `json:"com_id" sokel:"com_id" label:"统一社会信用代码"`
	Exchange       string  `json:"exchange" sokel:"exchange" label:"交易所代码"`
	Chairman       string  `json:"chairman" sokel:"chairman" label:"法人代表"`
	Manager        string  `json:"manager" sokel:"manager" label:"总经理"`
	Secretary      string  `json:"secretary" sokel:"secretary" label:"董秘"`
	Reg_capital    float64 `json:"reg_capital" sokel:"reg_capital" label:"注册资本(万元)"`
	Setup_date     string  `json:"setup_date" sokel:"setup_date" label:"注册日期"`
	Province       string  `json:"province" sokel:"province" label:"所在省份"`
	City           string  `json:"city" sokel:"city" label:"所在城市"`
	Introduction   string  `json:"introduction" sokel:"introduction" label:"公司介绍"`
	Website        string  `json:"website" sokel:"website" label:"公司主页"`
	Email          string  `json:"email" sokel:"email" label:"电子邮件"`
	Office         string  `json:"office" sokel:"office" label:"办公室"`
	Employees      int64   `json:"employees" sokel:"employees" label:"员工人数"`
	Main_business  string  `json:"main_business" sokel:"main_business" label:"主要业务及产品"`
	Business_scope string  `json:"business_scope" sokel:"business_scope" label:"经营范围"`
}

// ApiStockHsgt 沪深港通股票列表（stock_hsgt）
// 目录：股票数据/基础数据/沪深港通股票列表
type ApiStockHsgt struct{}

func (ApiStockHsgt) Meta() contract.Meta {
	return contract.Meta{ID: "stock_hsgt", Label: "沪深港通股票列表", Desc: "获取沪深港通股票列表 权限：3000积分起 提示：每天上午9:20更新，单次请求最大返回2000行数据，可根据类型循环提取,本接口数据从20250812开始 输入参数 名称 类型 必选 描述 ts_code str N 股票代码 trade_date str N 交易日期（格式：YYYYMMDD） type str Y 类型（参考下表） start_date str N 开始时间 end_date str N 结束时间 类型说明如下： 类型 类型名称 HK_SZ 深股通(港>深) SZ_HK 港股通(深>港) HK_SH 沪股通(港>沪) SH_HK 港股通(沪>港) 输出参数 名称 类型 默", TimeoutSec: 90}
}

func (ApiStockHsgt) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码").Desc("股票代码").Optional(),
		field.String("trade_date").Label("交易日期（格式：YYYYMMDD）").Desc("交易日期（格式：YYYYMMDD）").Optional(),
		field.String("type").Label("类型（参考下表）").Desc("类型（参考下表）"),
		field.String("start_date").Label("开始时间").Desc("开始时间").Optional(),
		field.String("end_date").Label("结束时间").Desc("结束时间").Optional(),
	}
}

func (ApiStockHsgt) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []StockHsgtRecord{}).Label("沪深港通股票列表"),
		field.Int("count").Label("本批条数"),
	}
}

// StockHsgtRecord 沪深港通股票列表 的一条记录。
type StockHsgtRecord struct {
	Ts_code    string `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	Trade_date string `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Type       string `json:"type" sokel:"type" label:"类型"`
	Name       string `json:"name" sokel:"name" label:"股票名称"`
	Type_name  string `json:"type_name" sokel:"type_name" label:"类型名称"`
}

// ApiStockSt ST股票列表（stock_st）
// 目录：股票数据/基础数据/ST股票列表
type ApiStockSt struct{}

func (ApiStockSt) Meta() contract.Meta {
	return contract.Meta{ID: "stock_st", Label: "ST股票列表", Desc: "获取ST股票列表，可根据交易日期获取历史上每天的ST列表 权限：3000积分起 提示：每天上午9:20更新，单次请求最大返回1000行数据，可循环提取,本接口数据从20170101开始,太早历史无法补齐 输入参数 名称 类型 必选 描述 ts_code str N 股票代码 trade_date str N 交易日期（格式：YYYYMMDD下同） start_date str N 开始时间 end_date str N 结束时间 输出参数 名称 类型 默认显示 描述 ts_code str Y 股票代码 name str Y 股票名称 trade_date str Y 交易日期 type st", TimeoutSec: 90}
}

func (ApiStockSt) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码").Desc("股票代码").Optional(),
		field.String("trade_date").Label("交易日期（格式：YYYYMMDD下同）").Desc("交易日期（格式：YYYYMMDD下同）").Optional(),
		field.String("start_date").Label("开始时间").Desc("开始时间").Optional(),
		field.String("end_date").Label("结束时间").Desc("结束时间").Optional(),
	}
}

func (ApiStockSt) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []StockStRecord{}).Label("ST股票列表"),
		field.Int("count").Label("本批条数"),
	}
}

// StockStRecord ST股票列表 的一条记录。
type StockStRecord struct {
	Ts_code    string `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	Name       string `json:"name" sokel:"name" label:"股票名称"`
	Trade_date string `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Type       string `json:"type" sokel:"type" label:"类型"`
	Type_name  string `json:"type_name" sokel:"type_name" label:"类型名称"`
}

// ApiSuspendD 每日停复牌信息（suspend_d）
// 目录：股票数据/行情数据/每日停复牌信息
type ApiSuspendD struct{}

func (ApiSuspendD) Meta() contract.Meta {
	return contract.Meta{ID: "suspend_d", Label: "每日停复牌信息", Desc: "按日期方式获取股票每日停复牌信息 输入参数 名称 类型 必选 描述 ts_code str N 股票代码(可输入多值) trade_date str N 交易日日期 start_date str N 停复牌查询开始日期 end_date str N 停复牌查询结束日期 suspend_type str N 停复牌类型：S-停牌,R-复牌 输出参数 名称 类型 默认显示 描述 ts_code str Y TS代码 trade_date str Y 停复牌日期（覆盖从停牌到覆盖期间的连续日期） suspend_timing str Y 日内停牌时间段（日内停牌才有值，否则为空值） suspend_", TimeoutSec: 90}
}

func (ApiSuspendD) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码(可输入多值)").Desc("股票代码(可输入多值)").Optional(),
		field.String("trade_date").Label("交易日日期").Desc("交易日日期").Optional(),
		field.String("start_date").Label("停复牌查询开始日期").Desc("停复牌查询开始日期").Optional(),
		field.String("end_date").Label("停复牌查询结束日期").Desc("停复牌查询结束日期").Optional(),
		field.String("suspend_type").Label("停复牌类型：S-停牌,R-复牌").Desc("停复牌类型：S-停牌,R-复牌").Optional(),
	}
}

func (ApiSuspendD) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []SuspendDRecord{}).Label("每日停复牌信息"),
		field.Int("count").Label("本批条数"),
	}
}

// SuspendDRecord 每日停复牌信息 的一条记录。
type SuspendDRecord struct {
	Ts_code        string `json:"ts_code" sokel:"ts_code" label:"TS代码"`
	Trade_date     string `json:"trade_date" sokel:"trade_date" label:"停复牌日期（覆盖从停牌到覆盖期间的连续日期）"`
	Suspend_timing string `json:"suspend_timing" sokel:"suspend_timing" label:"日内停牌时间段（日内停牌才有值，否则为空值）"`
	Suspend_type   string `json:"suspend_type" sokel:"suspend_type" label:"停复牌类型：S-停牌，R-复牌"`
}

// ApiSwDaily 申万行业日线行情（sw_daily）
// 目录：指数专题/申万日线行情
type ApiSwDaily struct{}

func (ApiSwDaily) Meta() contract.Meta {
	return contract.Meta{ID: "sw_daily", Label: "申万行业日线行情", Desc: "获取申万行业日线行情（默认是申万2021版行情） 限量：单次最大4000行数据，可通过指数代码和日期参数循环提取，5000积分可调取 输入参数 名称 类型 必选 描述 ts_code str N 行业代码 trade_date str N 交易日期 start_date str N 开始日期 end_date str N 结束日期 输出参数 名称 类型 默认显示 描述 ts_code str Y 指数代码 trade_date str Y 交易日期 name str Y 指数名称 open float Y 开盘点位 low float Y 最低点位 high float Y 最高点位 clos", TimeoutSec: 90}
}

func (ApiSwDaily) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("行业代码").Desc("行业代码").Optional(),
		field.String("trade_date").Label("交易日期").Desc("交易日期").Optional(),
		field.String("start_date").Label("开始日期").Desc("开始日期").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
	}
}

func (ApiSwDaily) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []SwDailyRecord{}).Label("申万行业日线行情"),
		field.Int("count").Label("本批条数"),
	}
}

// SwDailyRecord 申万行业日线行情 的一条记录。
type SwDailyRecord struct {
	Ts_code    string  `json:"ts_code" sokel:"ts_code" label:"指数代码"`
	Trade_date string  `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Name       string  `json:"name" sokel:"name" label:"指数名称"`
	Open       float64 `json:"open" sokel:"open" label:"开盘点位"`
	Low        float64 `json:"low" sokel:"low" label:"最低点位"`
	High       float64 `json:"high" sokel:"high" label:"最高点位"`
	Close      float64 `json:"close" sokel:"close" label:"收盘点位"`
	Change     float64 `json:"change" sokel:"change" label:"涨跌点位"`
	Pct_change float64 `json:"pct_change" sokel:"pct_change" label:"涨跌幅"`
	Vol        float64 `json:"vol" sokel:"vol" label:"成交量（万股）"`
	Amount     float64 `json:"amount" sokel:"amount" label:"成交额（万元）"`
	Pe         float64 `json:"pe" sokel:"pe" label:"市盈率"`
	Pb         float64 `json:"pb" sokel:"pb" label:"市净率"`
	Float_mv   float64 `json:"float_mv" sokel:"float_mv" label:"流通市值（万元）"`
	Total_mv   float64 `json:"total_mv" sokel:"total_mv" label:"总市值（万元）"`
}

// ApiSwMins SW历史分钟（sw_mins）
// 目录：指数专题/SW历史分钟
type ApiSwMins struct{}

func (ApiSwMins) Meta() contract.Meta {
	return contract.Meta{ID: "sw_mins", Label: "SW历史分钟", Desc: "获取申万指数历史分钟数据 限量：单次最大5000条，可根据代码或日期循环提取 积分：本接口是单独的权限，具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 ts_code str Y 指数代码 freq str Y 分钟频度（1min/5min/15min/30min/60min） start_date datetime N 开始日期 格式：2023-08-25 09:00:00 end_date datetime N 结束时间 格式：2023-08-25 19:00:00 输出参数 名称 类型 默认显示 描述 ts_code str Y 指数代码 trade_time str Y 交", TimeoutSec: 90}
}

func (ApiSwMins) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("指数代码").Desc("指数代码"),
		field.String("freq").Label("分钟频度（1min/5min/15min/30min/60min）").Desc("分钟频度（1min/5min/15min/30min/60min）"),
		field.String("start_date").Label("开始日期 格式：2023-08-25 09:00:00").Desc("开始日期 格式：2023-08-25 09:00:00（类型 datetime）").Optional(),
		field.String("end_date").Label("结束时间 格式：2023-08-25 19:00:00").Desc("结束时间 格式：2023-08-25 19:00:00（类型 datetime）").Optional(),
	}
}

func (ApiSwMins) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []SwMinsRecord{}).Label("SW历史分钟"),
		field.Int("count").Label("本批条数"),
	}
}

// SwMinsRecord SW历史分钟 的一条记录。
type SwMinsRecord struct {
	Ts_code    string  `json:"ts_code" sokel:"ts_code" label:"指数代码"`
	Trade_time string  `json:"trade_time" sokel:"trade_time" label:"交易时间"`
	Open       float64 `json:"open" sokel:"open" label:"开盘点数"`
	Close      float64 `json:"close" sokel:"close" label:"收盘点数"`
	High       float64 `json:"high" sokel:"high" label:"最高点数"`
	Low        float64 `json:"low" sokel:"low" label:"最低点数"`
	Amount     float64 `json:"amount" sokel:"amount" label:"成交金额（元）"`
	Vol        float64 `json:"vol" sokel:"vol" label:"成交量（股）"`
}

// ApiSzDailyInfo 深圳市场每日交易概况（sz_daily_info）
// 目录：指数专题/深圳市场每日交易情况
type ApiSzDailyInfo struct{}

func (ApiSzDailyInfo) Meta() contract.Meta {
	return contract.Meta{ID: "sz_daily_info", Label: "深圳市场每日交易概况", Desc: "获取深圳市场每日交易概况 限量：单次最大2000，可循环获取，总量不限制 权限：用户积2000积分可调取， 频次有限制，积分越高每分钟调取频次越高，5000积分以上频次相对较高，积分获取方法请参阅 积分获取办法 输入参数 名称 类型 必选 描述 trade_date str N 交易日期（YYYYMMDD格式，下同） ts_code str N 板块代码 start_date str N 开始日期 end_date str N 结束日期 ts_code主要包括： 板块代码（TS_CODE） 板块说明 数据开始日期 股票 深圳市场股票总和 20080102 主板A股 深圳主板A股情况 20080", TimeoutSec: 90}
}

func (ApiSzDailyInfo) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("trade_date").Label("交易日期（YYYYMMDD格式，下同）").Desc("交易日期（YYYYMMDD格式，下同）").Optional(),
		field.String("ts_code").Label("板块代码").Desc("板块代码").Optional(),
		field.String("start_date").Label("开始日期").Desc("开始日期").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
	}
}

func (ApiSzDailyInfo) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []SzDailyInfoRecord{}).Label("深圳市场每日交易概况"),
		field.Int("count").Label("本批条数"),
	}
}

// SzDailyInfoRecord 深圳市场每日交易概况 的一条记录。
type SzDailyInfoRecord struct {
	Trade_date  string  `json:"trade_date" sokel:"trade_date" label:"trade_date"`
	Ts_code     string  `json:"ts_code" sokel:"ts_code" label:"市场类型"`
	Count       int64   `json:"count" sokel:"count" label:"股票个数"`
	Amount      float64 `json:"amount" sokel:"amount" label:"成交金额"`
	Vol         string  `json:"vol" sokel:"vol" label:"成交量"`
	Total_share float64 `json:"total_share" sokel:"total_share" label:"总股本"`
	Total_mv    float64 `json:"total_mv" sokel:"total_mv" label:"总市值"`
	Float_share float64 `json:"float_share" sokel:"float_share" label:"流通股票"`
	Float_mv    float64 `json:"float_mv" sokel:"float_mv" label:"流通市值"`
}

// ApiTdxDaily TDX板块行情（tdx_daily）
// 目录：股票数据/打板专题数据/TDX概念板块行情
type ApiTdxDaily struct{}

func (ApiTdxDaily) Meta() contract.Meta {
	return contract.Meta{ID: "tdx_daily", Label: "TDX板块行情", Desc: "获取各板块行情，包括成交和估值等数据 限量：单次提取最大3000条数据，可根据板块代码和日期参数循环提取 权限：用户积累6000积分可调取，具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 ts_code str N 板块代码：xxxxxx.TDX trade_date str N 交易日期，格式YYYYMMDD,下同 start_date str N 开始日期 end_date str N 结束日期 输出参数 名称 类型 默认显示 描述 ts_code str Y 板块代码 trade_date str Y 交易日期 close float Y 收盘点位 open float Y", TimeoutSec: 90}
}

func (ApiTdxDaily) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("板块代码：xxxxxx.TDX").Desc("板块代码：xxxxxx.TDX").Optional(),
		field.String("trade_date").Label("交易日期，格式YYYYMMDD,下同").Desc("交易日期，格式YYYYMMDD,下同").Optional(),
		field.String("start_date").Label("开始日期").Desc("开始日期").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
	}
}

func (ApiTdxDaily) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []TdxDailyRecord{}).Label("TDX板块行情"),
		field.Int("count").Label("本批条数"),
	}
}

// TdxDailyRecord TDX板块行情 的一条记录。
type TdxDailyRecord struct {
	Ts_code        string  `json:"ts_code" sokel:"ts_code" label:"板块代码"`
	Trade_date     string  `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Close          float64 `json:"close" sokel:"close" label:"收盘点位"`
	Open           float64 `json:"open" sokel:"open" label:"开盘点位"`
	High           float64 `json:"high" sokel:"high" label:"最高点位"`
	Low            float64 `json:"low" sokel:"low" label:"最低点位"`
	Pre_close      float64 `json:"pre_close" sokel:"pre_close" label:"昨日收盘点"`
	Change         float64 `json:"change" sokel:"change" label:"涨跌点位"`
	Pct_change     float64 `json:"pct_change" sokel:"pct_change" label:"涨跌幅%"`
	Vol            float64 `json:"vol" sokel:"vol" label:"成交量（手）"`
	Amount         float64 `json:"amount" sokel:"amount" label:"成交额（万元）, 对于期货指数，该字段存储持仓量"`
	Rise           string  `json:"rise" sokel:"rise" label:"收盘涨速%"`
	Vol_ratio      float64 `json:"vol_ratio" sokel:"vol_ratio" label:"量比"`
	Turnover_rate  float64 `json:"turnover_rate" sokel:"turnover_rate" label:"换手%"`
	Swing          float64 `json:"swing" sokel:"swing" label:"振幅%"`
	Up_num         int64   `json:"up_num" sokel:"up_num" label:"上涨家数"`
	Down_num       int64   `json:"down_num" sokel:"down_num" label:"下跌家数"`
	Limit_up_num   int64   `json:"limit_up_num" sokel:"limit_up_num" label:"涨停家数"`
	Limit_down_num int64   `json:"limit_down_num" sokel:"limit_down_num" label:"跌停家数"`
	Lu_days        int64   `json:"lu_days" sokel:"lu_days" label:"连涨天数"`
	F3day          float64 `json:"3day" sokel:"f3day" label:"3日涨幅%"`
	F5day          float64 `json:"5day" sokel:"f5day" label:"5日涨幅%"`
	F10day         float64 `json:"10day" sokel:"f10day" label:"10日涨幅%"`
	F20day         float64 `json:"20day" sokel:"f20day" label:"20日涨幅%"`
	F60day         float64 `json:"60day" sokel:"f60day" label:"60日涨幅%"`
	Mtd            float64 `json:"mtd" sokel:"mtd" label:"月初至今%"`
	Ytd            float64 `json:"ytd" sokel:"ytd" label:"年初至今%"`
	F1year         float64 `json:"1year" sokel:"f1year" label:"一年涨幅%"`
	Pe             string  `json:"pe" sokel:"pe" label:"市盈率"`
	Pb             string  `json:"pb" sokel:"pb" label:"市净率"`
	Float_mv       float64 `json:"float_mv" sokel:"float_mv" label:"流通市值(亿)"`
	Ab_total_mv    float64 `json:"ab_total_mv" sokel:"ab_total_mv" label:"AB股总市值（亿）"`
	Float_share    float64 `json:"float_share" sokel:"float_share" label:"流通股(亿)"`
	Total_share    float64 `json:"total_share" sokel:"total_share" label:"总股本(亿)"`
	Bm_buy_net     float64 `json:"bm_buy_net" sokel:"bm_buy_net" label:"主买净额(元)"`
	Bm_buy_ratio   float64 `json:"bm_buy_ratio" sokel:"bm_buy_ratio" label:"主买占比%"`
	Bm_net         float64 `json:"bm_net" sokel:"bm_net" label:"主力净额"`
	Bm_ratio       float64 `json:"bm_ratio" sokel:"bm_ratio" label:"主力占比%"`
}

// ApiTdxIndex TDX板块信息（tdx_index）
// 目录：股票数据/打板专题数据/TDX概念板块分类
type ApiTdxIndex struct{}

func (ApiTdxIndex) Meta() contract.Meta {
	return contract.Meta{ID: "tdx_index", Label: "TDX板块信息", Desc: "获取板块基础信息，包括概念板块、行业、风格、地域等 限量：单次最大1000条数据，可根据日期参数循环提取 权限：用户积累6000积分可调取，具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 ts_code str N 板块代码：xxxxxx.TDX trade_date str N 交易日期(格式：YYYYMMDD） idx_type str N 板块类型：概念板块、行业板块、风格板块、地区板块 输出参数 名称 类型 默认显示 描述 ts_code str Y 板块代码 trade_date str Y 交易日期 name str Y 板块名称 idx_type str Y 板块类型", TimeoutSec: 90}
}

func (ApiTdxIndex) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("板块代码：xxxxxx.TDX").Desc("板块代码：xxxxxx.TDX").Optional(),
		field.String("trade_date").Label("交易日期(格式：YYYYMMDD）").Desc("交易日期(格式：YYYYMMDD）").Optional(),
		field.String("idx_type").Label("板块类型：概念板块、行业板块、风格板块、地区板块").Desc("板块类型：概念板块、行业板块、风格板块、地区板块").Optional(),
	}
}

func (ApiTdxIndex) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []TdxIndexRecord{}).Label("TDX板块信息"),
		field.Int("count").Label("本批条数"),
	}
}

// TdxIndexRecord TDX板块信息 的一条记录。
type TdxIndexRecord struct {
	Ts_code     string  `json:"ts_code" sokel:"ts_code" label:"板块代码"`
	Trade_date  string  `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Name        string  `json:"name" sokel:"name" label:"板块名称"`
	Idx_type    string  `json:"idx_type" sokel:"idx_type" label:"板块类型"`
	Idx_count   int64   `json:"idx_count" sokel:"idx_count" label:"成分个数"`
	Total_share float64 `json:"total_share" sokel:"total_share" label:"总股本(亿)"`
	Float_share float64 `json:"float_share" sokel:"float_share" label:"流通股(亿)"`
	Total_mv    float64 `json:"total_mv" sokel:"total_mv" label:"总市值(亿)"`
	Float_mv    float64 `json:"float_mv" sokel:"float_mv" label:"流通市值(亿)"`
}

// ApiTdxMember TDX板块成分（tdx_member）
// 目录：股票数据/打板专题数据/TDX概念板块成分
type ApiTdxMember struct{}

func (ApiTdxMember) Meta() contract.Meta {
	return contract.Meta{ID: "tdx_member", Label: "TDX板块成分", Desc: "获取各板块成分股信息 限量：单次最大3000条数据，可以根据日期和板块代码循环提取 权限：用户积累6000积分可调取，具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 ts_code str N 板块代码：xxxxxx.TDX con_code str N 成分股票代码 trade_date str N 交易日期：（YYYYMMDD格式） start_date str N 开始日期：（YYYYMMDD格式） end_date str N 结束日期：（YYYYMMDD格式） 输出参数 名称 类型 默认显示 描述 ts_code str Y 板块代码 trade_date str Y 交", TimeoutSec: 90}
}

func (ApiTdxMember) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("板块代码：xxxxxx.TDX").Desc("板块代码：xxxxxx.TDX").Optional(),
		field.String("con_code").Label("成分股票代码").Desc("成分股票代码").Optional(),
		field.String("trade_date").Label("交易日期：（YYYYMMDD格式）").Desc("交易日期：（YYYYMMDD格式）").Optional(),
		field.String("start_date").Label("开始日期：（YYYYMMDD格式）").Desc("开始日期：（YYYYMMDD格式）").Optional(),
		field.String("end_date").Label("结束日期：（YYYYMMDD格式）").Desc("结束日期：（YYYYMMDD格式）").Optional(),
	}
}

func (ApiTdxMember) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []TdxMemberRecord{}).Label("TDX板块成分"),
		field.Int("count").Label("本批条数"),
	}
}

// TdxMemberRecord TDX板块成分 的一条记录。
type TdxMemberRecord struct {
	Ts_code    string `json:"ts_code" sokel:"ts_code" label:"板块代码"`
	Trade_date string `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Con_code   string `json:"con_code" sokel:"con_code" label:"成分股票代码"`
	Con_name   string `json:"con_name" sokel:"con_name" label:"成分股票名称"`
}

// ApiThsDaily 板块指数行情（ths_daily）
// 目录：股票数据/打板专题数据/THS概念板块行情
type ApiThsDaily struct{}

func (ApiThsDaily) Meta() contract.Meta {
	return contract.Meta{ID: "ths_daily", Label: "板块指数行情", Desc: "获取板块指数行情 限量：单次最大3000行数据（需6000积分），可根据指数代码、日期参数循环提取 输入参数 名称 类型 必选 描述 ts_code str N 板块指数代码 trade_date str N 交易日期（YYYYMMDD格式，下同） start_date str N 开始日期 end_date str N 结束日期 输出参数 名称 类型 默认显示 描述 ts_code str Y TS指数代码 trade_date str Y 交易日 close float Y 收盘点位 open float Y 开盘点位 high float Y 最高点位 low float Y 最低点位", TimeoutSec: 90}
}

func (ApiThsDaily) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("板块指数代码").Desc("板块指数代码").Optional(),
		field.String("trade_date").Label("交易日期（YYYYMMDD格式，下同）").Desc("交易日期（YYYYMMDD格式，下同）").Optional(),
		field.String("start_date").Label("开始日期").Desc("开始日期").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
	}
}

func (ApiThsDaily) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []ThsDailyRecord{}).Label("板块指数行情"),
		field.Int("count").Label("本批条数"),
	}
}

// ThsDailyRecord 板块指数行情 的一条记录。
type ThsDailyRecord struct {
	Ts_code       string  `json:"ts_code" sokel:"ts_code" label:"TS指数代码"`
	Trade_date    string  `json:"trade_date" sokel:"trade_date" label:"交易日"`
	Close         float64 `json:"close" sokel:"close" label:"收盘点位"`
	Open          float64 `json:"open" sokel:"open" label:"开盘点位"`
	High          float64 `json:"high" sokel:"high" label:"最高点位"`
	Low           float64 `json:"low" sokel:"low" label:"最低点位"`
	Pre_close     float64 `json:"pre_close" sokel:"pre_close" label:"昨日收盘点"`
	Avg_price     float64 `json:"avg_price" sokel:"avg_price" label:"平均价"`
	Change        float64 `json:"change" sokel:"change" label:"涨跌点位"`
	Pct_change    float64 `json:"pct_change" sokel:"pct_change" label:"涨跌幅"`
	Vol           float64 `json:"vol" sokel:"vol" label:"成交量（手）"`
	Turnover_rate float64 `json:"turnover_rate" sokel:"turnover_rate" label:"换手率（%）"`
	Total_mv      float64 `json:"total_mv" sokel:"total_mv" label:"总市值（元）"`
	Float_mv      float64 `json:"float_mv" sokel:"float_mv" label:"流通市值（元）"`
}

// ApiThsHot THS热榜（ths_hot）
// 目录：股票数据/打板专题数据/THS热榜
type ApiThsHot struct{}

func (ApiThsHot) Meta() contract.Meta {
	return contract.Meta{ID: "ths_hot", Label: "THS热榜", Desc: "获取热榜数据，包括热股、概念板块、ETF、可转债、港美股等等，每日盘中提取4次，收盘后4次，最晚22点提取一次。 限量：单次最大2000条，可根据日期等参数循环获取全部数据 积分：用户积6000积分可调取使用，积分获取办法请参阅 积分获取办法 输入参数 名称 类型 必选 描述 trade_date str N 交易日期 ts_code str N TS代码 market str N 热榜类型(热股、ETF、可转债、行业板块、概念板块、期货、港股、热基、美股) is_new str N 是否最新（默认Y，如果为N则为盘中和盘后阶段采集，具体时间可参考rank_time字段， 状态N每小时更新一次", TimeoutSec: 90}
}

func (ApiThsHot) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("trade_date").Label("交易日期").Desc("交易日期").Optional(),
		field.String("ts_code").Label("TS代码").Desc("TS代码").Optional(),
		field.String("market").Label("热榜类型(热股、ETF、可转债、行业板块、概念板块、期货、港股、热基、美股)").Desc("热榜类型(热股、ETF、可转债、行业板块、概念板块、期货、港股、热基、美股)").Optional(),
		field.String("is_new").Label("是否最新（默认Y，如果为N则为盘中和盘后阶段采集，具体时间可参考rank_time字段， 状态N每小时更新一次 ， 状态Y更新时间为22：30 ）").Desc("是否最新（默认Y，如果为N则为盘中和盘后阶段采集，具体时间可参考rank_time字段， 状态N每小时更新一次 ， 状态Y更新时间为22：30 ）").Optional(),
	}
}

func (ApiThsHot) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []ThsHotRecord{}).Label("THS热榜"),
		field.Int("count").Label("本批条数"),
	}
}

// ThsHotRecord THS热榜 的一条记录。
type ThsHotRecord struct {
	Trade_date    string  `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Data_type     string  `json:"data_type" sokel:"data_type" label:"数据类型"`
	Ts_code       string  `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	Ts_name       string  `json:"ts_name" sokel:"ts_name" label:"股票名称"`
	Rank          int64   `json:"rank" sokel:"rank" label:"排行"`
	Pct_change    float64 `json:"pct_change" sokel:"pct_change" label:"涨跌幅%"`
	Current_price float64 `json:"current_price" sokel:"current_price" label:"当前价格"`
	Concept       string  `json:"concept" sokel:"concept" label:"标签"`
	Rank_reason   string  `json:"rank_reason" sokel:"rank_reason" label:"上榜解读"`
	Hot           float64 `json:"hot" sokel:"hot" label:"热度值"`
	Rank_time     string  `json:"rank_time" sokel:"rank_time" label:"排行榜获取时间"`
}

// ApiThsIndex 概念和行业指数（ths_index）
// 目录：股票数据/打板专题数据/THS概念板块分类
type ApiThsIndex struct{}

func (ApiThsIndex) Meta() contract.Meta {
	return contract.Meta{ID: "ths_index", Label: "概念和行业指数", Desc: "获取板块指数，包括概念、行业、特色指数。 权限：本接口需有6000积分，单次最大返回5000行数据，一次可提取全部数据，请勿循环提取。 输入参数 名称 类型 必选 描述 ts_code str N 指数代码 exchange str N 市场类型A-a股 HK-港股 US-美股 type str N 指数类型 N-概念指数 I-行业指数 R-地域指数 S-特色指数 ST-风格指数 TH-主题指数 BB-宽基指数 输出参数 名称 类型 默认显示 描述 ts_code str Y 代码 name str Y 名称 count int Y 成分个数 exchange str Y 交易所 list_d", TimeoutSec: 90}
}

func (ApiThsIndex) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("指数代码").Desc("指数代码").Optional(),
		field.String("exchange").Label("市场类型A-a股 HK-港股 US-美股").Desc("市场类型A-a股 HK-港股 US-美股").Optional(),
		field.String("type").Label("指数类型 N-概念指数 I-行业指数 R-地域指数 S-特色指数 ST-风格指数 TH-主题指数 BB-宽基指数").Desc("指数类型 N-概念指数 I-行业指数 R-地域指数 S-特色指数 ST-风格指数 TH-主题指数 BB-宽基指数").Optional(),
	}
}

func (ApiThsIndex) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []ThsIndexRecord{}).Label("概念和行业指数"),
		field.Int("count").Label("本批条数"),
	}
}

// ThsIndexRecord 概念和行业指数 的一条记录。
type ThsIndexRecord struct {
	Ts_code   string `json:"ts_code" sokel:"ts_code" label:"代码"`
	Name      string `json:"name" sokel:"name" label:"名称"`
	Count     int64  `json:"count" sokel:"count" label:"成分个数"`
	Exchange  string `json:"exchange" sokel:"exchange" label:"交易所"`
	List_date string `json:"list_date" sokel:"list_date" label:"上市日期"`
	Type      string `json:"type" sokel:"type" label:"N概念指数S特色指数"`
}

// ApiThsMember 概念板块成分（ths_member）
// 目录：股票数据/打板专题数据/THS概念板块成分
type ApiThsMember struct{}

func (ApiThsMember) Meta() contract.Meta {
	return contract.Meta{ID: "ths_member", Label: "概念板块成分", Desc: "获取概念板块成分列表 限量：用户积累6000积分可调取，每分钟可调取200次，可按概念板块代码循环提取历史成分 输入参数 名称 类型 必选 描述 ts_code str N 板块指数代码 con_code str N 股票代码 输出参数 名称 类型 默认显示 描述 ts_code str Y 指数代码 con_code str Y 股票代码 con_name str Y 股票名称 weight float N 权重(暂无) in_date str N 纳入日期(暂无) out_date str N 剔除日期(暂无) is_new str N 是否最新Y是N否 接口示例 pro = ts . p", TimeoutSec: 90}
}

func (ApiThsMember) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("板块指数代码").Desc("板块指数代码").Optional(),
		field.String("con_code").Label("股票代码").Desc("股票代码").Optional(),
	}
}

func (ApiThsMember) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []ThsMemberRecord{}).Label("概念板块成分"),
		field.Int("count").Label("本批条数"),
	}
}

// ThsMemberRecord 概念板块成分 的一条记录。
type ThsMemberRecord struct {
	Ts_code  string  `json:"ts_code" sokel:"ts_code" label:"指数代码"`
	Con_code string  `json:"con_code" sokel:"con_code" label:"股票代码"`
	Con_name string  `json:"con_name" sokel:"con_name" label:"股票名称"`
	Weight   float64 `json:"weight" sokel:"weight" label:"权重(暂无)"`
	In_date  string  `json:"in_date" sokel:"in_date" label:"纳入日期(暂无)"`
	Out_date string  `json:"out_date" sokel:"out_date" label:"剔除日期(暂无)"`
	Is_new   string  `json:"is_new" sokel:"is_new" label:"是否最新Y是N否"`
}

// ApiTop10CbHolders 可转债十大持有人（top10_cb_holders）
// 目录：债券专题/可转债十大持有人
type ApiTop10CbHolders struct{}

func (ApiTop10CbHolders) Meta() contract.Meta {
	return contract.Meta{ID: "top10_cb_holders", Label: "可转债十大持有人", Desc: "获取可转债前十大持有人 限量：单次最大3000条，可根据代码或日期循环提取 积分：需要5000积分可以调取，具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 ts_code str Y TS代码，支持多值输入，如110059.SH,110060.SH period str N 报告期（YYYYMMDD格式，年中和年报日期，如20240630,20251231） start_date str N 报告期开始日期 end_date str N 报告期结束日期 输出参数 名称 类型 默认显示 描述 ts_code str Y 转债代码 end_date str Y 报告期 holder_r", TimeoutSec: 90}
}

func (ApiTop10CbHolders) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("TS代码，支持多值输入，如110059.SH,110060.SH").Desc("TS代码，支持多值输入，如110059.SH,110060.SH"),
		field.String("period").Label("报告期（YYYYMMDD格式，年中和年报日期，如20240630,20251231）").Desc("报告期（YYYYMMDD格式，年中和年报日期，如20240630,20251231）").Optional(),
		field.String("start_date").Label("报告期开始日期").Desc("报告期开始日期").Optional(),
		field.String("end_date").Label("报告期结束日期").Desc("报告期结束日期").Optional(),
	}
}

func (ApiTop10CbHolders) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []Top10CbHoldersRecord{}).Label("可转债十大持有人"),
		field.Int("count").Label("本批条数"),
	}
}

// Top10CbHoldersRecord 可转债十大持有人 的一条记录。
type Top10CbHoldersRecord struct {
	Ts_code     string  `json:"ts_code" sokel:"ts_code" label:"转债代码"`
	End_date    string  `json:"end_date" sokel:"end_date" label:"报告期"`
	Holder_rank int64   `json:"holder_rank" sokel:"holder_rank" label:"持有排名"`
	Holder_name string  `json:"holder_name" sokel:"holder_name" label:"持有人名称"`
	Hold_amount float64 `json:"hold_amount" sokel:"hold_amount" label:"持有数量(万张)"`
	Hold_ratio  float64 `json:"hold_ratio" sokel:"hold_ratio" label:"持有比例(%)"`
}

// ApiTop10Floatholders 前十大流通股东（top10_floatholders）
// 目录：股票数据/参考数据/前十大流通股东
type ApiTop10Floatholders struct{}

func (ApiTop10Floatholders) Meta() contract.Meta {
	return contract.Meta{ID: "top10_floatholders", Label: "前十大流通股东", Desc: "获取上市公司前十大流通股东数据 积分：需2000积分以上才可以调取本接口，5000积分以上频次会更高 输入参数 名称 类型 必选 描述 ts_code str Y TS代码 period str N 报告期（YYYYMMDD格式，一般为每个季度最后一天） ann_date str N 公告日期 start_date str N 报告期开始日期 end_date str N 报告期结束日期 输出参数 名称 类型 描述 ts_code str TS股票代码 ann_date str 公告日期 end_date str 报告期 holder_name str 股东名称 hold_amount flo", TimeoutSec: 90}
}

func (ApiTop10Floatholders) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("TS代码").Desc("TS代码"),
		field.String("period").Label("报告期（YYYYMMDD格式，一般为每个季度最后一天）").Desc("报告期（YYYYMMDD格式，一般为每个季度最后一天）").Optional(),
		field.String("ann_date").Label("公告日期").Desc("公告日期").Optional(),
		field.String("start_date").Label("报告期开始日期").Desc("报告期开始日期").Optional(),
		field.String("end_date").Label("报告期结束日期").Desc("报告期结束日期").Optional(),
	}
}

func (ApiTop10Floatholders) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []Top10FloatholdersRecord{}).Label("前十大流通股东"),
		field.Int("count").Label("本批条数"),
	}
}

// Top10FloatholdersRecord 前十大流通股东 的一条记录。
type Top10FloatholdersRecord struct {
	Ts_code          string  `json:"ts_code" sokel:"ts_code" label:"TS股票代码"`
	Ann_date         string  `json:"ann_date" sokel:"ann_date" label:"公告日期"`
	End_date         string  `json:"end_date" sokel:"end_date" label:"报告期"`
	Holder_name      string  `json:"holder_name" sokel:"holder_name" label:"股东名称"`
	Hold_amount      float64 `json:"hold_amount" sokel:"hold_amount" label:"持有数量（股）"`
	Hold_ratio       float64 `json:"hold_ratio" sokel:"hold_ratio" label:"占总股本比例(%)"`
	Hold_float_ratio float64 `json:"hold_float_ratio" sokel:"hold_float_ratio" label:"占流通股本比例(%)"`
	Hold_change      float64 `json:"hold_change" sokel:"hold_change" label:"持股变动（0表示不变，空值表示 新进）"`
	Holder_type      string  `json:"holder_type" sokel:"holder_type" label:"股东类型"`
}

// ApiTop10Holders 前十大股东（top10_holders）
// 目录：股票数据/参考数据/前十大股东
type ApiTop10Holders struct{}

func (ApiTop10Holders) Meta() contract.Meta {
	return contract.Meta{ID: "top10_holders", Label: "前十大股东", Desc: "获取上市公司前十大股东数据，包括持有数量和比例等信息 积分：需2000积分以上才可以调取本接口，5000积分以上频次会更高 输入参数 名称 类型 必选 描述 ts_code str Y TS代码 period str N 报告期（YYYYMMDD格式，一般为每个季度最后一天） ann_date str N 公告日期 start_date str N 报告期开始日期 end_date str N 报告期结束日期 输出参数 名称 类型 描述 ts_code str TS股票代码 ann_date str 公告日期 end_date str 报告期 holder_name str 股东名称 hold", TimeoutSec: 90}
}

func (ApiTop10Holders) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("TS代码").Desc("TS代码"),
		field.String("period").Label("报告期（YYYYMMDD格式，一般为每个季度最后一天）").Desc("报告期（YYYYMMDD格式，一般为每个季度最后一天）").Optional(),
		field.String("ann_date").Label("公告日期").Desc("公告日期").Optional(),
		field.String("start_date").Label("报告期开始日期").Desc("报告期开始日期").Optional(),
		field.String("end_date").Label("报告期结束日期").Desc("报告期结束日期").Optional(),
	}
}

func (ApiTop10Holders) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []Top10HoldersRecord{}).Label("前十大股东"),
		field.Int("count").Label("本批条数"),
	}
}

// Top10HoldersRecord 前十大股东 的一条记录。
type Top10HoldersRecord struct {
	Ts_code          string  `json:"ts_code" sokel:"ts_code" label:"TS股票代码"`
	Ann_date         string  `json:"ann_date" sokel:"ann_date" label:"公告日期"`
	End_date         string  `json:"end_date" sokel:"end_date" label:"报告期"`
	Holder_name      string  `json:"holder_name" sokel:"holder_name" label:"股东名称"`
	Hold_amount      float64 `json:"hold_amount" sokel:"hold_amount" label:"持有数量（股）"`
	Hold_ratio       float64 `json:"hold_ratio" sokel:"hold_ratio" label:"占总股本比例(%)"`
	Hold_float_ratio float64 `json:"hold_float_ratio" sokel:"hold_float_ratio" label:"占流通股本比例(%)"`
	Hold_change      float64 `json:"hold_change" sokel:"hold_change" label:"持股变动"`
	Holder_type      string  `json:"holder_type" sokel:"holder_type" label:"股东类型"`
}

// ApiTopInst 龙虎榜机构明细（top_inst）
// 目录：股票数据/打板专题数据/龙虎榜机构交易单
type ApiTopInst struct{}

func (ApiTopInst) Meta() contract.Meta {
	return contract.Meta{ID: "top_inst", Label: "龙虎榜机构明细", Desc: "龙虎榜机构成交明细 限量：单次请求最大返回10000行数据，可根据参数循环获取全部历史 积分：用户需要至少5000积分才可以调取，具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 trade_date str Y 交易日期 ts_code str N TS代码 输出参数 名称 类型 默认显示 描述 trade_date str Y 交易日期 ts_code str Y TS代码 exalter str Y 营业部名称 side str Y 买卖类型0：买入金额最大的前5名， 1：卖出金额最大的前5名 buy float Y 买入额（元） buy_rate float Y 买入占总成交", TimeoutSec: 90}
}

func (ApiTopInst) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("trade_date").Label("交易日期").Desc("交易日期"),
		field.String("ts_code").Label("TS代码").Desc("TS代码").Optional(),
	}
}

func (ApiTopInst) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []TopInstRecord{}).Label("龙虎榜机构明细"),
		field.Int("count").Label("本批条数"),
	}
}

// TopInstRecord 龙虎榜机构明细 的一条记录。
type TopInstRecord struct {
	Trade_date string  `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Ts_code    string  `json:"ts_code" sokel:"ts_code" label:"TS代码"`
	Exalter    string  `json:"exalter" sokel:"exalter" label:"营业部名称"`
	Side       string  `json:"side" sokel:"side" label:"买卖类型0：买入金额最大的前5名， 1：卖出金额最大的前5名"`
	Buy        float64 `json:"buy" sokel:"buy" label:"买入额（元）"`
	Buy_rate   float64 `json:"buy_rate" sokel:"buy_rate" label:"买入占总成交比例"`
	Sell       float64 `json:"sell" sokel:"sell" label:"卖出额（元）"`
	Sell_rate  float64 `json:"sell_rate" sokel:"sell_rate" label:"卖出占总成交比例"`
	Net_buy    float64 `json:"net_buy" sokel:"net_buy" label:"净成交额（元）"`
	Reason     string  `json:"reason" sokel:"reason" label:"上榜理由"`
}

// ApiTopList 龙虎榜每日明细（top_list）
// 目录：股票数据/打板专题数据/龙虎榜每日统计单
type ApiTopList struct{}

func (ApiTopList) Meta() contract.Meta {
	return contract.Meta{ID: "top_list", Label: "龙虎榜每日明细", Desc: "龙虎榜每日交易明细 数据历史： 2005年至今 限量：单次请求返回最大10000行数据，可通过参数循环获取全部历史 积分：用户需要至少2000积分才可以调取，具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 trade_date str Y 交易日期 ts_code str N 股票代码 输出参数 名称 类型 默认显示 描述 trade_date str Y 交易日期 ts_code str Y TS代码 name str Y 名称 close float Y 收盘价 pct_change float Y 涨跌幅 turnover_rate float Y 换手率 amount fl", TimeoutSec: 90}
}

func (ApiTopList) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("trade_date").Label("交易日期").Desc("交易日期"),
		field.String("ts_code").Label("股票代码").Desc("股票代码").Optional(),
	}
}

func (ApiTopList) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []TopListRecord{}).Label("龙虎榜每日明细"),
		field.Int("count").Label("本批条数"),
	}
}

// TopListRecord 龙虎榜每日明细 的一条记录。
type TopListRecord struct {
	Trade_date    string  `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Ts_code       string  `json:"ts_code" sokel:"ts_code" label:"TS代码"`
	Name          string  `json:"name" sokel:"name" label:"名称"`
	Close         float64 `json:"close" sokel:"close" label:"收盘价"`
	Pct_change    float64 `json:"pct_change" sokel:"pct_change" label:"涨跌幅"`
	Turnover_rate float64 `json:"turnover_rate" sokel:"turnover_rate" label:"换手率"`
	Amount        float64 `json:"amount" sokel:"amount" label:"总成交额"`
	L_sell        float64 `json:"l_sell" sokel:"l_sell" label:"龙虎榜卖出额"`
	L_buy         float64 `json:"l_buy" sokel:"l_buy" label:"龙虎榜买入额"`
	L_amount      float64 `json:"l_amount" sokel:"l_amount" label:"龙虎榜成交额"`
	Net_amount    float64 `json:"net_amount" sokel:"net_amount" label:"龙虎榜净买入额"`
	Net_rate      float64 `json:"net_rate" sokel:"net_rate" label:"龙虎榜净买额占比"`
	Amount_rate   float64 `json:"amount_rate" sokel:"amount_rate" label:"龙虎榜成交额占比"`
	Float_values  float64 `json:"float_values" sokel:"float_values" label:"当日流通市值"`
	Reason        string  `json:"reason" sokel:"reason" label:"上榜理由"`
}

// ApiTradeCal 交易日历（trade_cal）
// 目录：股票数据/基础数据/交易日历
type ApiTradeCal struct{}

func (ApiTradeCal) Meta() contract.Meta {
	return contract.Meta{ID: "trade_cal", Label: "交易日历", Desc: "获取各大交易所交易日历数据,默认提取的是上交所 积分：需2000积分 输入参数 名称 类型 必选 描述 exchange str N 交易所 SSE上交所,SZSE深交所,CFFEX 中金所,SHFE 上期所,CZCE 郑商所,DCE 大商所,INE 上能源 start_date str N 开始日期 （格式：YYYYMMDD 下同） end_date str N 结束日期 is_open str N 是否交易 '0'休市 '1'交易 输出参数 名称 类型 默认显示 描述 exchange str Y 交易所 SSE上交所 SZSE深交所 cal_date str Y 日历日期 is_open", TimeoutSec: 90}
}

func (ApiTradeCal) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("exchange").Label("交易所 SSE上交所,SZSE深交所,CFFEX 中金所,SHFE 上期所,CZCE 郑商所,DCE 大商所,INE 上能源").Desc("交易所 SSE上交所,SZSE深交所,CFFEX 中金所,SHFE 上期所,CZCE 郑商所,DCE 大商所,INE 上能源").Optional(),
		field.String("start_date").Label("开始日期 （格式：YYYYMMDD 下同）").Desc("开始日期 （格式：YYYYMMDD 下同）").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
		field.String("is_open").Label("是否交易 '0'休市 '1'交易").Desc("是否交易 '0'休市 '1'交易").Optional(),
	}
}

func (ApiTradeCal) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []TradeCalRecord{}).Label("交易日历"),
		field.Int("count").Label("本批条数"),
	}
}

// TradeCalRecord 交易日历 的一条记录。
type TradeCalRecord struct {
	Exchange      string `json:"exchange" sokel:"exchange" label:"交易所 SSE上交所 SZSE深交所"`
	Cal_date      string `json:"cal_date" sokel:"cal_date" label:"日历日期"`
	Is_open       string `json:"is_open" sokel:"is_open" label:"是否交易 0休市 1交易"`
	Pretrade_date string `json:"pretrade_date" sokel:"pretrade_date" label:"上一个交易日"`
}

// ApiUsAdjfactor 美股复权因子（us_adjfactor）
// 目录：美股数据/美股复权因子
type ApiUsAdjfactor struct{}

func (ApiUsAdjfactor) Meta() contract.Meta {
	return contract.Meta{ID: "us_adjfactor", Label: "美股复权因子", Desc: "获取美股每日复权因子数据，在每天美股收盘后滚动刷新 限量：单次最大15000行数据，可以根据日期循环 权限：本接口是在开通美股日线权限后自动获取权限，权限请参考 权限说明文档 输入参数 名称 类型 必选 描述 ts_code str N 股票代码 trade_date str N 交易日期（格式：YYYYMMDD，下同） start_date str N 开始日期 end_date str N 结束日期 输出参数 名称 类型 默认显示 描述 ts_code str Y 股票代码 trade_date str Y 交易日期 exchange str Y 交易所 cum_adjfactor flo", TimeoutSec: 90}
}

func (ApiUsAdjfactor) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码").Desc("股票代码").Optional(),
		field.String("trade_date").Label("交易日期（格式：YYYYMMDD，下同）").Desc("交易日期（格式：YYYYMMDD，下同）").Optional(),
		field.String("start_date").Label("开始日期").Desc("开始日期").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
	}
}

func (ApiUsAdjfactor) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsAdjfactorRecord{}).Label("美股复权因子"),
		field.Int("count").Label("本批条数"),
	}
}

// UsAdjfactorRecord 美股复权因子 的一条记录。
type UsAdjfactorRecord struct {
	Ts_code       string  `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	Trade_date    string  `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Exchange      string  `json:"exchange" sokel:"exchange" label:"交易所"`
	Cum_adjfactor float64 `json:"cum_adjfactor" sokel:"cum_adjfactor" label:"累计复权因子"`
	Close_price   float64 `json:"close_price" sokel:"close_price" label:"收盘价"`
}

// ApiUsBalancesheet 美股资产负债表（us_balancesheet）
// 目录：美股数据/美股资产负债表
type ApiUsBalancesheet struct{}

func (ApiUsBalancesheet) Meta() contract.Meta {
	return contract.Meta{ID: "us_balancesheet", Label: "美股资产负债表", Desc: "获取美股上市公司资产负债表（目前只覆盖主要美股和中概股） 权限：需单独开权限，具体权限信息请参考 权限列表 提示：当前接口按单只股票获取其历史数据，单次请求最大返回10000行数据，可循环提取 输入参数 名称 类型 必选 描述 ts_code str Y 股票代码 period str N 报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231) ind_name str N 指标名(如：新增借款） report_type str N 报告期类型(Q1一季报Q2半年报Q3三季报Q4年报) start_date str N 报告期开始时间（格式：YYYYMMDD） end_d", TimeoutSec: 90}
}

func (ApiUsBalancesheet) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码").Desc("股票代码"),
		field.String("period").Label("报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231)").Desc("报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231)").Optional(),
		field.String("ind_name").Label("指标名(如：新增借款）").Desc("指标名(如：新增借款）").Optional(),
		field.String("report_type").Label("报告期类型(Q1一季报Q2半年报Q3三季报Q4年报)").Desc("报告期类型(Q1一季报Q2半年报Q3三季报Q4年报)").Optional(),
		field.String("start_date").Label("报告期开始时间（格式：YYYYMMDD）").Desc("报告期开始时间（格式：YYYYMMDD）").Optional(),
		field.String("end_date").Label("报告结束始时间（格式：YYYYMMDD）").Desc("报告结束始时间（格式：YYYYMMDD）").Optional(),
	}
}

func (ApiUsBalancesheet) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsBalancesheetRecord{}).Label("美股资产负债表"),
		field.Int("count").Label("本批条数"),
	}
}

// UsBalancesheetRecord 美股资产负债表 的一条记录。
type UsBalancesheetRecord struct {
	Ts_code     string  `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	End_date    string  `json:"end_date" sokel:"end_date" label:"报告期"`
	Ind_type    string  `json:"ind_type" sokel:"ind_type" label:"报告期类型(Q1一季报Q2半年报Q3三季报Q4年报)"`
	Name        string  `json:"name" sokel:"name" label:"股票名称"`
	Ind_name    string  `json:"ind_name" sokel:"ind_name" label:"财务科目名称"`
	Ind_value   float64 `json:"ind_value" sokel:"ind_value" label:"财务科目值"`
	Report_type string  `json:"report_type" sokel:"report_type" label:"报告类型"`
}

// ApiUsBasic 美股列表（us_basic）
// 目录：美股数据/美股基础信息
type ApiUsBasic struct{}

func (ApiUsBasic) Meta() contract.Meta {
	return contract.Meta{ID: "us_basic", Label: "美股列表", Desc: "获取美股列表信息 限量：单次最大6000，可分页提取 积分：120积分可以试用，5000积分有正式权限 输入参数 名称 类型 必选 描述 示例 ts_code str N 股票代码 AAPL（苹果） classify str N 股票分类 ADR-美国存托凭证；GDR-全球存托凭证；EQ-普通股；PF-优先股 list_stauts str N 上市状态 L上市D退市P暂停上市 offset str N 开始行数 1：第一行 limit str N 每页最大行数 500：每页500行 输出参数 名称 类型 默认显示 描述 ts_code str Y 美股代码 name str Y 中文名称 e", TimeoutSec: 90}
}

func (ApiUsBasic) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码").Desc("股票代码").Optional(),
		field.String("classify").Label("股票分类").Desc("股票分类").Optional(),
		field.String("list_stauts").Label("上市状态").Desc("上市状态").Optional(),
		field.String("offset").Label("开始行数").Desc("开始行数").Optional(),
		field.String("limit").Label("每页最大行数").Desc("每页最大行数").Optional(),
	}
}

func (ApiUsBasic) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsBasicRecord{}).Label("美股列表"),
		field.Int("count").Label("本批条数"),
	}
}

// UsBasicRecord 美股列表 的一条记录。
type UsBasicRecord struct {
	Ts_code     string `json:"ts_code" sokel:"ts_code" label:"美股代码"`
	Name        string `json:"name" sokel:"name" label:"中文名称"`
	Enname      string `json:"enname" sokel:"enname" label:"英文名称"`
	Classify    string `json:"classify" sokel:"classify" label:"分类:ADR-美国存托凭证；GDR-全球存托凭证；EQ-普通股；PF-优先股"`
	List_date   string `json:"list_date" sokel:"list_date" label:"上市日期"`
	Delist_date string `json:"delist_date" sokel:"delist_date" label:"退市日期"`
}

// ApiUsCashflow 美股现金流量表（us_cashflow）
// 目录：美股数据/美股现金流量表
type ApiUsCashflow struct{}

func (ApiUsCashflow) Meta() contract.Meta {
	return contract.Meta{ID: "us_cashflow", Label: "美股现金流量表", Desc: "获取美股上市公司现金流量表数据（目前只覆盖主要美股和中概股） 权限：需单独开权限，具体权限信息请参考 权限列表 提示：当前接口按单只股票获取其历史数据，单次请求最大返回10000行数据，可循环提取 输入参数 名称 类型 必选 描述 ts_code str Y 股票代码 period str N 报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231) ind_name str N 指标名(如：新增借款） report_type str N 报告期类型(Q1一季报Q2半年报Q3三季报Q4年报) start_date str N 报告期开始时间（格式：YYYYMMDD） end", TimeoutSec: 90}
}

func (ApiUsCashflow) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码").Desc("股票代码"),
		field.String("period").Label("报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231)").Desc("报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231)").Optional(),
		field.String("ind_name").Label("指标名(如：新增借款）").Desc("指标名(如：新增借款）").Optional(),
		field.String("report_type").Label("报告期类型(Q1一季报Q2半年报Q3三季报Q4年报)").Desc("报告期类型(Q1一季报Q2半年报Q3三季报Q4年报)").Optional(),
		field.String("start_date").Label("报告期开始时间（格式：YYYYMMDD）").Desc("报告期开始时间（格式：YYYYMMDD）").Optional(),
		field.String("end_date").Label("报告结束始时间（格式：YYYYMMDD）").Desc("报告结束始时间（格式：YYYYMMDD）").Optional(),
	}
}

func (ApiUsCashflow) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsCashflowRecord{}).Label("美股现金流量表"),
		field.Int("count").Label("本批条数"),
	}
}

// UsCashflowRecord 美股现金流量表 的一条记录。
type UsCashflowRecord struct {
	Ts_code     string  `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	End_date    string  `json:"end_date" sokel:"end_date" label:"报告期"`
	Ind_type    string  `json:"ind_type" sokel:"ind_type" label:"报告期类型(Q1一季报Q2半年报Q3三季报Q4年报)"`
	Name        string  `json:"name" sokel:"name" label:"股票名称"`
	Ind_name    string  `json:"ind_name" sokel:"ind_name" label:"财务科目名称"`
	Ind_value   float64 `json:"ind_value" sokel:"ind_value" label:"财务科目值"`
	Report_type string  `json:"report_type" sokel:"report_type" label:"报告类型"`
}

// ApiUsDaily 美股行情（us_daily）
// 目录：美股数据/美股日线行情
type ApiUsDaily struct{}

func (ApiUsDaily) Meta() contract.Meta {
	return contract.Meta{ID: "us_daily", Label: "美股行情", Desc: "获取美股行情（未复权），包括全部股票全历史行情，以及重要的市场和估值指标 限量：单次最大6000行数据，可根据日期参数循环提取，开通正式权限后也可支持分页提取全部历史 要求：120积分可以试用查看数据，开通正式权限请参考 权限说明文档 。 输入参数 名称 类型 必选 描述 ts_code str N 股票代码（e.g. AAPL） trade_date str N 交易日期（YYYYMMDD） start_date str N 开始日期（YYYYMMDD） end_date str N 结束日期（YYYYMMDD） 输出参数 名称 类型 默认显示 描述 ts_code str Y 股票代码 t", TimeoutSec: 90}
}

func (ApiUsDaily) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码（e.g. AAPL）").Desc("股票代码（e.g. AAPL）").Optional(),
		field.String("trade_date").Label("交易日期（YYYYMMDD）").Desc("交易日期（YYYYMMDD）").Optional(),
		field.String("start_date").Label("开始日期（YYYYMMDD）").Desc("开始日期（YYYYMMDD）").Optional(),
		field.String("end_date").Label("结束日期（YYYYMMDD）").Desc("结束日期（YYYYMMDD）").Optional(),
	}
}

func (ApiUsDaily) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsDailyRecord{}).Label("美股行情"),
		field.Int("count").Label("本批条数"),
	}
}

// UsDailyRecord 美股行情 的一条记录。
type UsDailyRecord struct {
	Ts_code        string  `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	Trade_date     string  `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Close          float64 `json:"close" sokel:"close" label:"收盘价"`
	Open           float64 `json:"open" sokel:"open" label:"开盘价"`
	High           float64 `json:"high" sokel:"high" label:"最高价"`
	Low            float64 `json:"low" sokel:"low" label:"最低价"`
	Pre_close      float64 `json:"pre_close" sokel:"pre_close" label:"昨收价"`
	Change         float64 `json:"change" sokel:"change" label:"涨跌额"`
	Pct_change     float64 `json:"pct_change" sokel:"pct_change" label:"涨跌幅"`
	Vol            float64 `json:"vol" sokel:"vol" label:"成交量"`
	Amount         float64 `json:"amount" sokel:"amount" label:"成交额"`
	Vwap           float64 `json:"vwap" sokel:"vwap" label:"平均价"`
	Turnover_ratio float64 `json:"turnover_ratio" sokel:"turnover_ratio" label:"换手率"`
	Total_mv       float64 `json:"total_mv" sokel:"total_mv" label:"总市值"`
	Pe             float64 `json:"pe" sokel:"pe" label:"PE"`
	Pb             float64 `json:"pb" sokel:"pb" label:"PB"`
}

// ApiUsDailyAdj 美股复权行情（us_daily_adj）
// 目录：美股数据/美股复权行情
type ApiUsDailyAdj struct{}

func (ApiUsDailyAdj) Meta() contract.Meta {
	return contract.Meta{ID: "us_daily_adj", Label: "美股复权行情", Desc: "获取美股复权行情，支持美股全市场股票，提供股本、市值、复权因子和成交信息等多个数据指标 限量：单次最大可以提取8000条数据，可循环获取全部，支持分页提取 要求：120积分可以试用查看数据，开通正式权限请参考 权限说明文档 注：美股复权逻辑是：价格 * 复权因子 = 复权价格，比如close * adj_factor = 前复权收盘价。复权因子历史数据可能除权等被刷新，请注意动态更新。 输入参数 名称 类型 必选 描述 ts_code str N 股票代码（e.g. AAPL） trade_date str N 交易日期（YYYYMMDD） start_date str N 开始日期（YYYY", TimeoutSec: 90}
}

func (ApiUsDailyAdj) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码（e.g. AAPL）").Desc("股票代码（e.g. AAPL）").Optional(),
		field.String("trade_date").Label("交易日期（YYYYMMDD）").Desc("交易日期（YYYYMMDD）").Optional(),
		field.String("start_date").Label("开始日期（YYYYMMDD）").Desc("开始日期（YYYYMMDD）").Optional(),
		field.String("end_date").Label("结束日期（YYYYMMDD）").Desc("结束日期（YYYYMMDD）").Optional(),
		field.String("exchange").Label("交易所（NAS/NYS/OTC)").Desc("交易所（NAS/NYS/OTC)").Optional(),
		field.String("offset").Label("开始行数").Desc("开始行数（类型 int）").Optional(),
		field.String("limit").Label("每页行数行数").Desc("每页行数行数（类型 int）").Optional(),
	}
}

func (ApiUsDailyAdj) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsDailyAdjRecord{}).Label("美股复权行情"),
		field.Int("count").Label("本批条数"),
	}
}

// UsDailyAdjRecord 美股复权行情 的一条记录。
type UsDailyAdjRecord struct {
	Ts_code        string  `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	Trade_date     string  `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Close          float64 `json:"close" sokel:"close" label:"收盘价"`
	Open           float64 `json:"open" sokel:"open" label:"开盘价"`
	High           float64 `json:"high" sokel:"high" label:"最高价"`
	Low            float64 `json:"low" sokel:"low" label:"最低价"`
	Pre_close      float64 `json:"pre_close" sokel:"pre_close" label:"昨收价"`
	Change         float64 `json:"change" sokel:"change" label:"涨跌额"`
	Pct_change     float64 `json:"pct_change" sokel:"pct_change" label:"涨跌幅"`
	Vol            int64   `json:"vol" sokel:"vol" label:"成交量"`
	Amount         float64 `json:"amount" sokel:"amount" label:"成交额"`
	Vwap           float64 `json:"vwap" sokel:"vwap" label:"平均价"`
	Adj_factor     float64 `json:"adj_factor" sokel:"adj_factor" label:"复权因子"`
	Turnover_ratio float64 `json:"turnover_ratio" sokel:"turnover_ratio" label:"换手率"`
	Free_share     int64   `json:"free_share" sokel:"free_share" label:"流通股本"`
	Total_share    int64   `json:"total_share" sokel:"total_share" label:"总股本"`
	Free_mv        float64 `json:"free_mv" sokel:"free_mv" label:"流通市值"`
	Total_mv       float64 `json:"total_mv" sokel:"total_mv" label:"总市值"`
	Exchange       string  `json:"exchange" sokel:"exchange" label:"交易所代码"`
}

// ApiUsFinaIndicator 美股财务指标数据（us_fina_indicator）
// 目录：美股数据/美股财务指标数据
type ApiUsFinaIndicator struct{}

func (ApiUsFinaIndicator) Meta() contract.Meta {
	return contract.Meta{ID: "us_fina_indicator", Label: "美股财务指标数据", Desc: "获取美股上市公司财务指标数据，目前只覆盖主要美股和中概股。为避免服务器压力，现阶段每次请求最多返回200条记录，可通过设置日期多次请求获取更多数据。 权限：需单独开权限，具体权限信息请参考 权限列表 提示：当前接口按单只股票获取其历史数据，单次请求最大返回10000行数据，可循环提取 输入参数 名称 类型 必选 描述 ts_code str Y 股票代码 period str N 报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231) report_type str N 报告期类型(Q1一季报Q2半年报Q3三季报Q4年报) start_date str N 报告期开始时间", TimeoutSec: 90}
}

func (ApiUsFinaIndicator) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码").Desc("股票代码"),
		field.String("period").Label("报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231)").Desc("报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231)").Optional(),
		field.String("report_type").Label("报告期类型(Q1一季报Q2半年报Q3三季报Q4年报)").Desc("报告期类型(Q1一季报Q2半年报Q3三季报Q4年报)").Optional(),
		field.String("start_date").Label("报告期开始时间（格式：YYYYMMDD）").Desc("报告期开始时间（格式：YYYYMMDD）").Optional(),
		field.String("end_date").Label("报告结束始时间（格式：YYYYMMDD）").Desc("报告结束始时间（格式：YYYYMMDD）").Optional(),
	}
}

func (ApiUsFinaIndicator) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsFinaIndicatorRecord{}).Label("美股财务指标数据"),
		field.Int("count").Label("本批条数"),
	}
}

// UsFinaIndicatorRecord 美股财务指标数据 的一条记录。
type UsFinaIndicatorRecord struct {
	Ts_code                     string  `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	End_date                    string  `json:"end_date" sokel:"end_date" label:"报告期"`
	Ind_type                    string  `json:"ind_type" sokel:"ind_type" label:"报告类型,Q1一季报,Q2中报,Q3三季报,Q4年报"`
	Security_name_abbr          string  `json:"security_name_abbr" sokel:"security_name_abbr" label:"股票名称"`
	Accounting_standards        string  `json:"accounting_standards" sokel:"accounting_standards" label:"会计准则"`
	Notice_date                 string  `json:"notice_date" sokel:"notice_date" label:"公告日期"`
	Start_date                  string  `json:"start_date" sokel:"start_date" label:"报告期开始时间"`
	Std_report_date             string  `json:"std_report_date" sokel:"std_report_date" label:"标准报告期"`
	Financial_date              string  `json:"financial_date" sokel:"financial_date" label:"年结日"`
	Currency                    string  `json:"currency" sokel:"currency" label:"币种"`
	Date_type                   string  `json:"date_type" sokel:"date_type" label:"报告期类型"`
	Report_type                 string  `json:"report_type" sokel:"report_type" label:"报告类型"`
	Operate_income              float64 `json:"operate_income" sokel:"operate_income" label:"收入"`
	Operate_income_yoy          float64 `json:"operate_income_yoy" sokel:"operate_income_yoy" label:"收入增长"`
	Gross_profit                float64 `json:"gross_profit" sokel:"gross_profit" label:"毛利"`
	Gross_profit_yoy            float64 `json:"gross_profit_yoy" sokel:"gross_profit_yoy" label:"毛利增长"`
	Parent_holder_netprofit     float64 `json:"parent_holder_netprofit" sokel:"parent_holder_netprofit" label:"归母净利润"`
	Parent_holder_netprofit_yoy float64 `json:"parent_holder_netprofit_yoy" sokel:"parent_holder_netprofit_yoy" label:"归母净利润增长"`
	Basic_eps                   float64 `json:"basic_eps" sokel:"basic_eps" label:"基本每股收益"`
	Diluted_eps                 float64 `json:"diluted_eps" sokel:"diluted_eps" label:"稀释每股收益"`
	Gross_profit_ratio          float64 `json:"gross_profit_ratio" sokel:"gross_profit_ratio" label:"销售毛利率"`
	Net_profit_ratio            float64 `json:"net_profit_ratio" sokel:"net_profit_ratio" label:"销售净利率"`
	Accounts_rece_tr            float64 `json:"accounts_rece_tr" sokel:"accounts_rece_tr" label:"应收账款周转率(次)"`
	Inventory_tr                float64 `json:"inventory_tr" sokel:"inventory_tr" label:"存货周转率(次)"`
	Total_assets_tr             float64 `json:"total_assets_tr" sokel:"total_assets_tr" label:"总资产周转率(次)"`
	Accounts_rece_tdays         float64 `json:"accounts_rece_tdays" sokel:"accounts_rece_tdays" label:"应收账款周转天数"`
	Inventory_tdays             float64 `json:"inventory_tdays" sokel:"inventory_tdays" label:"存货周转天数"`
	Total_assets_tdays          float64 `json:"total_assets_tdays" sokel:"total_assets_tdays" label:"总资产周转天数"`
	Roe_avg                     float64 `json:"roe_avg" sokel:"roe_avg" label:"净资产收益率"`
	Roa                         float64 `json:"roa" sokel:"roa" label:"总资产净利率"`
	Current_ratio               float64 `json:"current_ratio" sokel:"current_ratio" label:"流动比率(倍)"`
	Speed_ratio                 float64 `json:"speed_ratio" sokel:"speed_ratio" label:"速动比率(倍)"`
	Ocf_liqdebt                 float64 `json:"ocf_liqdebt" sokel:"ocf_liqdebt" label:"经营业务现金净额/流动负债"`
	Debt_asset_ratio            float64 `json:"debt_asset_ratio" sokel:"debt_asset_ratio" label:"资产负债率"`
	Equity_ratio                float64 `json:"equity_ratio" sokel:"equity_ratio" label:"产权比率"`
	Basic_eps_yoy               float64 `json:"basic_eps_yoy" sokel:"basic_eps_yoy" label:"基本每股收益同比增长"`
	Gross_profit_ratio_yoy      float64 `json:"gross_profit_ratio_yoy" sokel:"gross_profit_ratio_yoy" label:"毛利率同比增长(%)"`
	Net_profit_ratio_yoy        float64 `json:"net_profit_ratio_yoy" sokel:"net_profit_ratio_yoy" label:"净利率同比增长(%)"`
	Roe_avg_yoy                 float64 `json:"roe_avg_yoy" sokel:"roe_avg_yoy" label:"平均净资产收益率同比增长(%)"`
	Roa_yoy                     float64 `json:"roa_yoy" sokel:"roa_yoy" label:"净资产收益率同比增长(%)"`
	Debt_asset_ratio_yoy        float64 `json:"debt_asset_ratio_yoy" sokel:"debt_asset_ratio_yoy" label:"资产负债率同比增长(%)"`
	Current_ratio_yoy           float64 `json:"current_ratio_yoy" sokel:"current_ratio_yoy" label:"流动比率同比增长(%)"`
	Speed_ratio_yoy             float64 `json:"speed_ratio_yoy" sokel:"speed_ratio_yoy" label:"速动比率同比增长(%)"`
	Currency_abbr               string  `json:"currency_abbr" sokel:"currency_abbr" label:"币种"`
	Total_income                float64 `json:"total_income" sokel:"total_income" label:"收入总额"`
	Total_income_yoy            float64 `json:"total_income_yoy" sokel:"total_income_yoy" label:"收入总额同比增长"`
	Premium_income              float64 `json:"premium_income" sokel:"premium_income" label:"保费收入"`
	Premium_income_yoy          float64 `json:"premium_income_yoy" sokel:"premium_income_yoy" label:"保费收入同比"`
	Basic_eps_cs                float64 `json:"basic_eps_cs" sokel:"basic_eps_cs" label:"基本每股收益"`
	Basic_eps_cs_yoy            float64 `json:"basic_eps_cs_yoy" sokel:"basic_eps_cs_yoy" label:"基本每股收益同比增长"`
	Diluted_eps_cs              float64 `json:"diluted_eps_cs" sokel:"diluted_eps_cs" label:"稀释每股收益"`
	Payout_ratio                float64 `json:"payout_ratio" sokel:"payout_ratio" label:"保费收入/赔付支出"`
	Capitial_ratio              float64 `json:"capitial_ratio" sokel:"capitial_ratio" label:"总资产周转率"`
	Roe                         float64 `json:"roe" sokel:"roe" label:"净资产收益率"`
	Roe_yoy                     float64 `json:"roe_yoy" sokel:"roe_yoy" label:"净资产收益率同比增长"`
	Debt_ratio                  float64 `json:"debt_ratio" sokel:"debt_ratio" label:"资产负债率"`
	Debt_ratio_yoy              float64 `json:"debt_ratio_yoy" sokel:"debt_ratio_yoy" label:"资产负债率同比增长"`
	Net_interest_income         float64 `json:"net_interest_income" sokel:"net_interest_income" label:"净利息收入"`
	Net_interest_income_yoy     float64 `json:"net_interest_income_yoy" sokel:"net_interest_income_yoy" label:"净利息收入增长"`
	Diluted_eps_cs_yoy          float64 `json:"diluted_eps_cs_yoy" sokel:"diluted_eps_cs_yoy" label:"稀释每股收益增长"`
	Loan_loss_provision         float64 `json:"loan_loss_provision" sokel:"loan_loss_provision" label:"贷款损失准备"`
	Loan_loss_provision_yoy     float64 `json:"loan_loss_provision_yoy" sokel:"loan_loss_provision_yoy" label:"贷款损失准备增长"`
	Loan_deposit                float64 `json:"loan_deposit" sokel:"loan_deposit" label:"贷款/存款"`
	Loan_equity                 float64 `json:"loan_equity" sokel:"loan_equity" label:"贷款/股东权益(倍)"`
	Loan_assets                 float64 `json:"loan_assets" sokel:"loan_assets" label:"贷款/总资产"`
	Deposit_equity              float64 `json:"deposit_equity" sokel:"deposit_equity" label:"存款/股东权益(倍)"`
	Deposit_assets              float64 `json:"deposit_assets" sokel:"deposit_assets" label:"存款/总资产"`
	Rol                         float64 `json:"rol" sokel:"rol" label:"贷款回报率"`
	Rod                         float64 `json:"rod" sokel:"rod" label:"存款回报率"`
}

// ApiUsIncome 美股利润表（us_income）
// 目录：美股数据/美股利润表
type ApiUsIncome struct{}

func (ApiUsIncome) Meta() contract.Meta {
	return contract.Meta{ID: "us_income", Label: "美股利润表", Desc: "获取美股上市公司财务利润表数据（目前只覆盖主要美股和中概股） 权限：需单独开权限，具体权限信息请参考 权限列表 提示：当前接口按单只股票获取其历史数据，单次请求最大返回10000行数据，可循环提取 输入参数 名称 类型 必选 描述 ts_code str Y 股票代码 period str N 报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231) ind_name str N 指标名(如：新增借款） report_type str N 报告期类型(Q1一季报Q2半年报Q3三季报Q4年报) start_date str N 报告期开始时间（格式：YYYYMMDD） end", TimeoutSec: 90}
}

func (ApiUsIncome) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("股票代码").Desc("股票代码"),
		field.String("period").Label("报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231)").Desc("报告期（格式：YYYYMMDD，每个季度最后一天的日期，如20241231)").Optional(),
		field.String("ind_name").Label("指标名(如：新增借款）").Desc("指标名(如：新增借款）").Optional(),
		field.String("report_type").Label("报告期类型(Q1一季报Q2半年报Q3三季报Q4年报)").Desc("报告期类型(Q1一季报Q2半年报Q3三季报Q4年报)").Optional(),
		field.String("start_date").Label("报告期开始时间（格式：YYYYMMDD）").Desc("报告期开始时间（格式：YYYYMMDD）").Optional(),
		field.String("end_date").Label("报告结束始时间（格式：YYYYMMDD）").Desc("报告结束始时间（格式：YYYYMMDD）").Optional(),
	}
}

func (ApiUsIncome) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsIncomeRecord{}).Label("美股利润表"),
		field.Int("count").Label("本批条数"),
	}
}

// UsIncomeRecord 美股利润表 的一条记录。
type UsIncomeRecord struct {
	Ts_code     string  `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	End_date    string  `json:"end_date" sokel:"end_date" label:"报告期"`
	Ind_type    string  `json:"ind_type" sokel:"ind_type" label:"报告期类型(Q1一季报Q2半年报Q3三季报Q4年报)"`
	Name        string  `json:"name" sokel:"name" label:"股票名称"`
	Ind_name    string  `json:"ind_name" sokel:"ind_name" label:"财务科目名称"`
	Ind_value   float64 `json:"ind_value" sokel:"ind_value" label:"财务科目值"`
	Report_type string  `json:"report_type" sokel:"report_type" label:"报告类型"`
}

// ApiUsTbr 短期国债利率（us_tbr）
// 目录：宏观经济/国际宏观/美国利率/短期国债利率
type ApiUsTbr struct{}

func (ApiUsTbr) Meta() contract.Meta {
	return contract.Meta{ID: "us_tbr", Label: "短期国债利率", Desc: "获取美国短期国债利率数据 限量：单次最大可获取2000行数据，可循环获取 权限：用户积累120积分可以使用，积分越高频次越高。具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 date str N 日期 start_date str N 开始日期(YYYYMMDD格式) end_date str N 结束日期 fields str N 指定输出字段(e.g. fields='w4_bd,w52_ce') 输出参数 名称 类型 默认显示 描述 date str Y 日期 w4_bd float Y 4周银行折现收益率 w4_ce float Y 4周票面利率 w8_bd float Y", TimeoutSec: 90}
}

func (ApiUsTbr) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("date").Label("日期").Desc("日期").Optional(),
		field.String("start_date").Label("开始日期(YYYYMMDD格式)").Desc("开始日期(YYYYMMDD格式)").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
		field.String("fields").Label("指定输出字段(e.g. fields='w4_bd,w52_ce')").Desc("指定输出字段(e.g. fields='w4_bd,w52_ce')").Optional(),
	}
}

func (ApiUsTbr) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsTbrRecord{}).Label("短期国债利率"),
		field.Int("count").Label("本批条数"),
	}
}

// UsTbrRecord 短期国债利率 的一条记录。
type UsTbrRecord struct {
	Date   string  `json:"date" sokel:"date" label:"日期"`
	W4_bd  float64 `json:"w4_bd" sokel:"w4_bd" label:"4周银行折现收益率"`
	W4_ce  float64 `json:"w4_ce" sokel:"w4_ce" label:"4周票面利率"`
	W8_bd  float64 `json:"w8_bd" sokel:"w8_bd" label:"8周银行折现收益率"`
	W8_ce  float64 `json:"w8_ce" sokel:"w8_ce" label:"8周票面利率"`
	W13_bd float64 `json:"w13_bd" sokel:"w13_bd" label:"13周银行折现收益率"`
	W13_ce float64 `json:"w13_ce" sokel:"w13_ce" label:"13周票面利率"`
	W17_bd float64 `json:"w17_bd" sokel:"w17_bd" label:"17周银行折现收益率（数据从20221019开始）"`
	W17_ce float64 `json:"w17_ce" sokel:"w17_ce" label:"17周票面利率（数据从20221019开始）"`
	W26_bd float64 `json:"w26_bd" sokel:"w26_bd" label:"26周银行折现收益率"`
	W26_ce float64 `json:"w26_ce" sokel:"w26_ce" label:"26周票面利率"`
	W52_bd float64 `json:"w52_bd" sokel:"w52_bd" label:"52周银行折现收益率"`
	W52_ce float64 `json:"w52_ce" sokel:"w52_ce" label:"52周票面利率"`
}

// ApiUsTltr 国债长期利率（us_tltr）
// 目录：宏观经济/国际宏观/美国利率/国债长期利率
type ApiUsTltr struct{}

func (ApiUsTltr) Meta() contract.Meta {
	return contract.Meta{ID: "us_tltr", Label: "国债长期利率", Desc: "国债长期利率 限量：单次最大可获取2000行数据，可循环获取 权限：用户积累120积分可以使用，积分越高频次越高。具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 date str N 日期 start_date str N 开始日期 end_date str N 结束日期 fields str N 指定字段 输出参数 名称 类型 默认显示 描述 date str Y 日期 ltc float Y 收益率 LT COMPOSITE (>10 Yrs) cmt float Y 20年期CMT利率(TREASURY 20-Yr CMT) e_factor float Y 外推因子EXTR", TimeoutSec: 90}
}

func (ApiUsTltr) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("date").Label("日期").Desc("日期").Optional(),
		field.String("start_date").Label("开始日期").Desc("开始日期").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
		field.String("fields").Label("指定字段").Desc("指定字段").Optional(),
	}
}

func (ApiUsTltr) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsTltrRecord{}).Label("国债长期利率"),
		field.Int("count").Label("本批条数"),
	}
}

// UsTltrRecord 国债长期利率 的一条记录。
type UsTltrRecord struct {
	Date     string  `json:"date" sokel:"date" label:"日期"`
	Ltc      float64 `json:"ltc" sokel:"ltc" label:"收益率 LT COMPOSITE (>10 Yrs)"`
	Cmt      float64 `json:"cmt" sokel:"cmt" label:"20年期CMT利率(TREASURY 20-Yr CMT)"`
	E_factor float64 `json:"e_factor" sokel:"e_factor" label:"外推因子EXTRAPOLATION FACTOR"`
}

// ApiUsTradecal 美股交易日历（us_tradecal）
// 目录：美股数据/美股交易日历
type ApiUsTradecal struct{}

func (ApiUsTradecal) Meta() contract.Meta {
	return contract.Meta{ID: "us_tradecal", Label: "美股交易日历", Desc: "获取美股交易日历信息 限量：5000积分有正式权限，单次最大6000，可根据日期阶段获取 输入参数 名称 类型 必选 描述 示例 start_date str N 开始日期 20200101 end_date str N 结束日期 20200701 is_open str N 是否交易 0：休市 、1：交易 输出参数 名称 类型 默认显示 描述 cal_date str Y 日历日期 is_open int Y 是否交易 '0'休市 '1'交易 pretrade_date str Y 上一个交易日 接口示例 pro = ts . pro_api () df = pro . us_tradeca", TimeoutSec: 90}
}

func (ApiUsTradecal) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("start_date").Label("开始日期").Desc("开始日期").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
		field.String("is_open").Label("是否交易").Desc("是否交易").Optional(),
	}
}

func (ApiUsTradecal) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsTradecalRecord{}).Label("美股交易日历"),
		field.Int("count").Label("本批条数"),
	}
}

// UsTradecalRecord 美股交易日历 的一条记录。
type UsTradecalRecord struct {
	Cal_date      string `json:"cal_date" sokel:"cal_date" label:"日历日期"`
	Is_open       int64  `json:"is_open" sokel:"is_open" label:"是否交易 '0'休市 '1'交易"`
	Pretrade_date string `json:"pretrade_date" sokel:"pretrade_date" label:"上一个交易日"`
}

// ApiUsTrltr 国债实际长期利率平均值（us_trltr）
// 目录：宏观经济/国际宏观/美国利率/国债长期利率平均值
type ApiUsTrltr struct{}

func (ApiUsTrltr) Meta() contract.Meta {
	return contract.Meta{ID: "us_trltr", Label: "国债实际长期利率平均值", Desc: "国债实际长期利率平均值 限量：单次最大可获取2000行数据，可循环获取 权限：用户积累120积分可以使用，积分越高频次越高。具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 date str N 日期 start_date str N 开始日期 end_date str N 结束日期 fields str N 指定字段 输出参数 名称 类型 默认显示 描述 date str Y 日期 ltr_avg float Y 实际平均利率LT Real Average (10> Yrs) 接口调用 pro = ts.pro_api() df = pro.us_trltr(start_date=", TimeoutSec: 90}
}

func (ApiUsTrltr) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("date").Label("日期").Desc("日期").Optional(),
		field.String("start_date").Label("开始日期").Desc("开始日期").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
		field.String("fields").Label("指定字段").Desc("指定字段").Optional(),
	}
}

func (ApiUsTrltr) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsTrltrRecord{}).Label("国债实际长期利率平均值"),
		field.Int("count").Label("本批条数"),
	}
}

// UsTrltrRecord 国债实际长期利率平均值 的一条记录。
type UsTrltrRecord struct {
	Date    string  `json:"date" sokel:"date" label:"日期"`
	Ltr_avg float64 `json:"ltr_avg" sokel:"ltr_avg" label:"实际平均利率LT Real Average (10> Yrs)"`
}

// ApiUsTrycr 国债实际收益率曲线利率（us_trycr）
// 目录：宏观经济/国际宏观/美国利率/国债实际收益率曲线利率
type ApiUsTrycr struct{}

func (ApiUsTrycr) Meta() contract.Meta {
	return contract.Meta{ID: "us_trycr", Label: "国债实际收益率曲线利率", Desc: "国债实际收益率曲线利率 限量：单次最大可获取2000行数据，可循环获取 权限：用户积累120积分可以使用，积分越高频次越高。具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 date str N 日期 （YYYYMMDD格式，下同） start_date str N 开始日期 end_date str N 结束日期 fields str N 指定输出字段 输出参数 名称 类型 默认显示 描述 date str Y 日期 y5 float Y 5年期 y7 float Y 7年期 y10 float Y 10年期 y20 float Y 20年期 y30 float Y 30年期 接口", TimeoutSec: 90}
}

func (ApiUsTrycr) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("date").Label("日期 （YYYYMMDD格式，下同）").Desc("日期 （YYYYMMDD格式，下同）").Optional(),
		field.String("start_date").Label("开始日期").Desc("开始日期").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
		field.String("fields").Label("指定输出字段").Desc("指定输出字段").Optional(),
	}
}

func (ApiUsTrycr) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsTrycrRecord{}).Label("国债实际收益率曲线利率"),
		field.Int("count").Label("本批条数"),
	}
}

// UsTrycrRecord 国债实际收益率曲线利率 的一条记录。
type UsTrycrRecord struct {
	Date string  `json:"date" sokel:"date" label:"日期"`
	Y5   float64 `json:"y5" sokel:"y5" label:"5年期"`
	Y7   float64 `json:"y7" sokel:"y7" label:"7年期"`
	Y10  float64 `json:"y10" sokel:"y10" label:"10年期"`
	Y20  float64 `json:"y20" sokel:"y20" label:"20年期"`
	Y30  float64 `json:"y30" sokel:"y30" label:"30年期"`
}

// ApiUsTycr 国债收益率曲线利率（日频）（us_tycr）
// 目录：宏观经济/国际宏观/美国利率/国债收益率曲线利率
type ApiUsTycr struct{}

func (ApiUsTycr) Meta() contract.Meta {
	return contract.Meta{ID: "us_tycr", Label: "国债收益率曲线利率（日频）", Desc: "获取美国每日国债收益率曲线利率 限量：单次最大可获取2000条数据 权限：用户积累120积分可以使用，积分越高频次越高。具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 date str N 日期 （YYYYMMDD格式，下同） start_date str N 开始日期 end_date str N 结束日期 fields str N 指定输出字段（e.g. fields='m1,y1'） 输出参数 名称 类型 默认显示 描述 date str Y 日期 m1 float Y 1月期 m2 float Y 2月期 m3 float Y 3月期 m4 float Y 4月期（数据从2", TimeoutSec: 90}
}

func (ApiUsTycr) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("date").Label("日期 （YYYYMMDD格式，下同）").Desc("日期 （YYYYMMDD格式，下同）").Optional(),
		field.String("start_date").Label("开始日期").Desc("开始日期").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
		field.String("fields").Label("指定输出字段（e.g. fields='m1,y1'）").Desc("指定输出字段（e.g. fields='m1,y1'）").Optional(),
	}
}

func (ApiUsTycr) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []UsTycrRecord{}).Label("国债收益率曲线利率（日频）"),
		field.Int("count").Label("本批条数"),
	}
}

// UsTycrRecord 国债收益率曲线利率（日频） 的一条记录。
type UsTycrRecord struct {
	Date string  `json:"date" sokel:"date" label:"日期"`
	M1   float64 `json:"m1" sokel:"m1" label:"1月期"`
	M2   float64 `json:"m2" sokel:"m2" label:"2月期"`
	M3   float64 `json:"m3" sokel:"m3" label:"3月期"`
	M4   float64 `json:"m4" sokel:"m4" label:"4月期（数据从20221019开始）"`
	M6   float64 `json:"m6" sokel:"m6" label:"6月期"`
	Y1   float64 `json:"y1" sokel:"y1" label:"1年期"`
	Y2   float64 `json:"y2" sokel:"y2" label:"2年期"`
	Y3   float64 `json:"y3" sokel:"y3" label:"3年期"`
	Y5   float64 `json:"y5" sokel:"y5" label:"5年期"`
	Y7   float64 `json:"y7" sokel:"y7" label:"7年期"`
	Y10  float64 `json:"y10" sokel:"y10" label:"10年期"`
	Y20  float64 `json:"y20" sokel:"y20" label:"20年期"`
	Y30  float64 `json:"y30" sokel:"y30" label:"30年期"`
}

// ApiWeekly 周线行情（weekly）
// 目录：股票数据/行情数据/周线行情
type ApiWeekly struct{}

func (ApiWeekly) Meta() contract.Meta {
	return contract.Meta{ID: "weekly", Label: "周线行情", Desc: "获取A股周线行情，本接口每周最后一个交易日更新，如需要使用每天更新的周线数据，请使用 日度更新的周线行情接口 。 限量：单次最大6000行，可使用交易日期循环提取，总量不限制 积分：用户需要至少2000积分才可以调取，具体请参阅 积分获取办法 输入参数 名称 类型 必选 描述 ts_code str N TS代码 （ts_code,trade_date两个参数任选一） trade_date str N 交易日期 （每周最后一个交易日期，YYYYMMDD格式） start_date str N 开始日期 end_date str N 结束日期 输出参数 名称 类型 默认显示 描述 ts_code", TimeoutSec: 90}
}

func (ApiWeekly) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("TS代码 （ts_code,trade_date两个参数任选一）").Desc("TS代码 （ts_code,trade_date两个参数任选一）").Optional(),
		field.String("trade_date").Label("交易日期 （每周最后一个交易日期，YYYYMMDD格式）").Desc("交易日期 （每周最后一个交易日期，YYYYMMDD格式）").Optional(),
		field.String("start_date").Label("开始日期").Desc("开始日期").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
	}
}

func (ApiWeekly) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []WeeklyRecord{}).Label("周线行情"),
		field.Int("count").Label("本批条数"),
	}
}

// WeeklyRecord 周线行情 的一条记录。
type WeeklyRecord struct {
	Ts_code    string  `json:"ts_code" sokel:"ts_code" label:"股票代码"`
	Trade_date string  `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Close      float64 `json:"close" sokel:"close" label:"周收盘价"`
	Open       float64 `json:"open" sokel:"open" label:"周开盘价"`
	High       float64 `json:"high" sokel:"high" label:"周最高价"`
	Low        float64 `json:"low" sokel:"low" label:"周最低价"`
	Pre_close  float64 `json:"pre_close" sokel:"pre_close" label:"上一周收盘价"`
	Change     float64 `json:"change" sokel:"change" label:"周涨跌额"`
	Pct_chg    float64 `json:"pct_chg" sokel:"pct_chg" label:"周涨跌 （未复权，未 100，如果是复权请用 通用行情接口 ，如需%单位请 100 ）"`
	Vol        float64 `json:"vol" sokel:"vol" label:"周成交量"`
	Amount     float64 `json:"amount" sokel:"amount" label:"周成交额"`
}

// ApiWzIndex 温州民间借贷利率（wz_index）
// 目录：宏观经济/国内宏观/利率数据/温州民间借贷利率
type ApiWzIndex struct{}

func (ApiWzIndex) Meta() contract.Meta {
	return contract.Meta{ID: "wz_index", Label: "温州民间借贷利率", Desc: "温州民间借贷利率，即温州指数 限量：不限量，一次可取全部指标全部历史数据 积分：用户需要积攒2000积分可调取，具体请参阅 积分获取办法 数据来源：温州指数网 注： 温州指数 ，即温州民间融资综合利率指数，该指数及时反映民间金融交易活跃度和交易价格。该指数样板数据主要采集于四个方面：由温州市设立的几百家企业测报点，把各自借入的民间资本利率通过各地方金融办不记名申报收集起来；对各小额贷款公司借出的利率进行加权平均；融资性担保公司如典当行在融资过程中的利率，由温州经信委和商务局负责测报；民间借贷服务中心的实时利率。这些利率进行加权平均，就得出了“温州指数”。它是温州民间融资利率的风向标。2012年", TimeoutSec: 90}
}

func (ApiWzIndex) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("date").Label("日期").Desc("日期").Optional(),
		field.String("start_date").Label("开始日期").Desc("开始日期").Optional(),
		field.String("end_date").Label("结束日期").Desc("结束日期").Optional(),
	}
}

func (ApiWzIndex) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []WzIndexRecord{}).Label("温州民间借贷利率"),
		field.Int("count").Label("本批条数"),
	}
}

// WzIndexRecord 温州民间借贷利率 的一条记录。
type WzIndexRecord struct {
	Date        string  `json:"date" sokel:"date" label:"日期"`
	Comp_rate   float64 `json:"comp_rate" sokel:"comp_rate" label:"温州民间融资综合利率指数 (%，下同)"`
	Center_rate float64 `json:"center_rate" sokel:"center_rate" label:"民间借贷服务中心利率"`
	Micro_rate  float64 `json:"micro_rate" sokel:"micro_rate" label:"小额贷款公司放款利率"`
	Cm_rate     float64 `json:"cm_rate" sokel:"cm_rate" label:"民间资本管理公司融资价格"`
	Sdb_rate    float64 `json:"sdb_rate" sokel:"sdb_rate" label:"社会直接借贷利率"`
	Om_rate     float64 `json:"om_rate" sokel:"om_rate" label:"其他市场主体利率"`
	Aa_rate     float64 `json:"aa_rate" sokel:"aa_rate" label:"农村互助会互助金费率"`
	M1_rate     float64 `json:"m1_rate" sokel:"m1_rate" label:"温州地区民间借贷分期限利率（一月期）"`
	M3_rate     float64 `json:"m3_rate" sokel:"m3_rate" label:"温州地区民间借贷分期限利率（三月期）"`
	M6_rate     float64 `json:"m6_rate" sokel:"m6_rate" label:"温州地区民间借贷分期限利率（六月期）"`
	M12_rate    float64 `json:"m12_rate" sokel:"m12_rate" label:"温州地区民间借贷分期限利率（一年期）"`
	Long_rate   float64 `json:"long_rate" sokel:"long_rate" label:"温州地区民间借贷分期限利率（长期）"`
}

// ApiYcCb 国债收益率曲线（yc_cb）
// 目录：债券专题/国债收益率曲线
type ApiYcCb struct{}

func (ApiYcCb) Meta() contract.Meta {
	return contract.Meta{ID: "yc_cb", Label: "国债收益率曲线", Desc: "获取中债收益率曲线，目前可获取中债国债收益率曲线即期和到期收益率曲线数据 限量：单次最大2000，总量不限制，可循环提取 权限：属于单独的权限接口，请在群里联系群主或管理员 输入参数 名称 类型 必选 描述 ts_code str N 收益率曲线编码：1001.CB-国债收益率曲线 curve_type str N 曲线类型：0-到期，1-即期 trade_date str N 交易日期 start_date str N 查询起始日期 end_date str N 查询结束日期 curve_term float N 期限 输出参数 名称 类型 默认显示 描述 trade_date str Y", TimeoutSec: 90}
}

func (ApiYcCb) Inputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.String("ts_code").Label("收益率曲线编码：1001.CB-国债收益率曲线").Desc("收益率曲线编码：1001.CB-国债收益率曲线").Optional(),
		field.String("curve_type").Label("曲线类型：0-到期，1-即期").Desc("曲线类型：0-到期，1-即期").Optional(),
		field.String("trade_date").Label("交易日期").Desc("交易日期").Optional(),
		field.String("start_date").Label("查询起始日期").Desc("查询起始日期").Optional(),
		field.String("end_date").Label("查询结束日期").Desc("查询结束日期").Optional(),
		field.String("curve_term").Label("期限").Desc("期限（类型 float）").Optional(),
	}
}

func (ApiYcCb) Outputs() []contract.FieldSpec {
	return []contract.FieldSpec{
		field.Array("items", []YcCbRecord{}).Label("国债收益率曲线"),
		field.Int("count").Label("本批条数"),
	}
}

// YcCbRecord 国债收益率曲线 的一条记录。
type YcCbRecord struct {
	Trade_date string  `json:"trade_date" sokel:"trade_date" label:"交易日期"`
	Ts_code    string  `json:"ts_code" sokel:"ts_code" label:"曲线编码"`
	Curve_name string  `json:"curve_name" sokel:"curve_name" label:"曲线名称"`
	Curve_type string  `json:"curve_type" sokel:"curve_type" label:"曲线类型：0-到期，1-即期"`
	Curve_term float64 `json:"curve_term" sokel:"curve_term" label:"期限(年)"`
	Yield      float64 `json:"yield" sokel:"yield" label:"收益率(%)"`
}
