// Code generated by sokel-gen. DO NOT EDIT.
//
// Event payload types and trigger functions are generated from the schema declaration.
// Change an event there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/wechat-claw/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// MessageEvent is the payload of the "收到消息" event.
type MessageEvent struct {
	ChatID    string         `json:"chat_id" sokel:"chat_id"`
	To        string         `json:"to" sokel:"to"`
	Text      string         `json:"text" sokel:"text"`
	MessageID int            `json:"message_id" sokel:"message_id"`
	Images    []*plugin.File `json:"images" sokel:"images"`
	Files     []*plugin.File `json:"files" sokel:"files"`
	Voice     *plugin.File   `json:"voice" sokel:"voice"`
	Raw       any            `json:"raw" sokel:"raw"`
}

// DeclareEvents hands this plugin's event contracts to the host.
//
// Common-field consistency was checked at **generation time** (each one must exist in every
// event with the same type), so this cannot fail here — a real problem showed up at
// go generate.
func DeclareEvents(h plugin.EventHost) {
	events := []contract.Event{
		contract.EventOf(&schema.MessageReceived{}),
	}
	for _, e := range events {
		h.DeclareEvent(e)
	}
	names := []string{"chat_id"}
	fields, _ := contract.ValidateCommonFields(events, names)
	h.DeclareEventsCommon(fields, names)
}

// TriggerMessage pushes one "收到消息" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerMessage(ctx plugin.SourceCtx, eventID string, p *MessageEvent) error {
	return ctx.Trigger("message", eventID, p)
}
