// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/wechat-claw/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnSendFile registers the implementation of "send_file".
func OnSendFile(h plugin.Host, fn func(plugin.Ctx, *SendFileIn) (*SendFileOut, error)) {
	h.Register(contract.OperationOf(&schema.SendFile{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SendFileIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSendImage registers the implementation of "send_image".
func OnSendImage(h plugin.Host, fn func(plugin.Ctx, *SendImageIn) (*SendImageOut, error)) {
	h.Register(contract.OperationOf(&schema.SendImage{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SendImageIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSendText registers the implementation of "send_text".
func OnSendText(h plugin.Host, fn func(plugin.Ctx, *SendTextIn) (*SendTextOut, error)) {
	h.Register(contract.OperationOf(&schema.SendText{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SendTextIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
