// Code generated by sokel-gen. DO NOT EDIT.
//
// Event payload types and trigger functions are generated from the schema declaration.
// Change an event there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/telegram-bot/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// CallbackQueryEvent is the payload of the "按钮点击" event.
type CallbackQueryEvent struct {
	ChatID       int    `json:"chat_id" sokel:"chat_id"`
	UserID       int    `json:"user_id" sokel:"user_id"`
	CallbackID   string `json:"callback_id" sokel:"callback_id"`
	CallbackData string `json:"callback_data" sokel:"callback_data"`
	MessageID    int    `json:"message_id" sokel:"message_id"`
	Raw          any    `json:"raw" sokel:"raw"`
}

// EditedMessageEvent is the payload of the "消息被编辑" event.
type EditedMessageEvent struct {
	ChatID    int    `json:"chat_id" sokel:"chat_id"`
	UserID    int    `json:"user_id" sokel:"user_id"`
	Username  string `json:"username" sokel:"username"`
	Text      string `json:"text" sokel:"text"`
	MessageID int    `json:"message_id" sokel:"message_id"`
	Raw       any    `json:"raw" sokel:"raw"`
}

// MessageEvent is the payload of the "收到消息" event.
type MessageEvent struct {
	ChatID    int    `json:"chat_id" sokel:"chat_id"`
	UserID    int    `json:"user_id" sokel:"user_id"`
	Username  string `json:"username" sokel:"username"`
	Text      string `json:"text" sokel:"text"`
	MessageID int    `json:"message_id" sokel:"message_id"`
	Raw       any    `json:"raw" sokel:"raw"`
}

// MyChatMemberEvent is the payload of the "bot 成员状态变化" event.
type MyChatMemberEvent struct {
	ChatID int `json:"chat_id" sokel:"chat_id"`
	UserID int `json:"user_id" sokel:"user_id"`
	Raw    any `json:"raw" sokel:"raw"`
}

// DeclareEvents hands this plugin's event contracts to the host.
//
// Common-field consistency was checked at **generation time** (each one must exist in every
// event with the same type), so this cannot fail here — a real problem showed up at
// go generate.
func DeclareEvents(h plugin.EventHost) {
	events := []contract.Event{
		contract.EventOf(&schema.CallbackQuery{}),
		contract.EventOf(&schema.MessageEdited{}),
		contract.EventOf(&schema.MessageReceived{}),
		contract.EventOf(&schema.MyChatMember{}),
	}
	for _, e := range events {
		h.DeclareEvent(e)
	}
	names := []string{"chat_id"}
	fields, _ := contract.ValidateCommonFields(events, names)
	h.DeclareEventsCommon(fields, names)
}

// TriggerCallbackQuery pushes one "按钮点击" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerCallbackQuery(ctx plugin.SourceCtx, eventID string, p *CallbackQueryEvent) error {
	return ctx.Trigger("callback_query", eventID, p)
}

// TriggerEditedMessage pushes one "消息被编辑" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerEditedMessage(ctx plugin.SourceCtx, eventID string, p *EditedMessageEvent) error {
	return ctx.Trigger("edited_message", eventID, p)
}

// TriggerMessage pushes one "收到消息" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerMessage(ctx plugin.SourceCtx, eventID string, p *MessageEvent) error {
	return ctx.Trigger("message", eventID, p)
}

// TriggerMyChatMember pushes one "bot 成员状态变化" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerMyChatMember(ctx plugin.SourceCtx, eventID string, p *MyChatMemberEvent) error {
	return ctx.Trigger("my_chat_member", eventID, p)
}
