// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/telegram-bot/schema"
)

type AnswerCallbackQueryIn struct {
	CallbackQueryID string `json:"callback_query_id" sokel:"callback_query_id"`
	Text            string `json:"text" sokel:"text"`
	ShowAlert       bool   `json:"show_alert" sokel:"show_alert"`
}

type AnswerCallbackQueryOut struct {
	OK     bool `json:"ok" sokel:"ok"`
	Result any  `json:"result" sokel:"result"`
}

type CallIn struct {
	Method string         `json:"method" sokel:"method"`
	Params map[string]any `json:"params" sokel:"params"`
}

type CallOut struct {
	OK     bool `json:"ok" sokel:"ok"`
	Result any  `json:"result" sokel:"result"`
}

type DeleteMessageIn struct {
	ChatID    string `json:"chat_id" sokel:"chat_id"`
	MessageID int    `json:"message_id" sokel:"message_id"`
}

type DeleteMessageOut struct {
	OK     bool `json:"ok" sokel:"ok"`
	Result any  `json:"result" sokel:"result"`
}

type DeleteWebhookIn struct {
	DropPendingUpdates bool `json:"drop_pending_updates" sokel:"drop_pending_updates"`
}

type DeleteWebhookOut struct {
	OK     bool `json:"ok" sokel:"ok"`
	Result any  `json:"result" sokel:"result"`
}

type DownloadFileIn struct {
	FileID string `json:"file_id" sokel:"file_id"`
}

type DownloadFileOut struct {
	FilePath string `json:"file_path" sokel:"file_path"`
	Size     int    `json:"size" sokel:"size"`
	Base64   string `json:"base64" sokel:"base64"`
}

type EditMessageTextIn struct {
	ChatID      string         `json:"chat_id" sokel:"chat_id"`
	MessageID   int            `json:"message_id" sokel:"message_id"`
	Text        string         `json:"text" sokel:"text"`
	ParseMode   string         `json:"parse_mode" sokel:"parse_mode"`
	ReplyMarkup map[string]any `json:"reply_markup" sokel:"reply_markup"`
}

type EditMessageTextOut struct {
	OK        bool `json:"ok" sokel:"ok"`
	MessageID int  `json:"message_id" sokel:"message_id"`
	Result    any  `json:"result" sokel:"result"`
}

type ForwardMessageIn struct {
	ChatID     string `json:"chat_id" sokel:"chat_id"`
	FromChatID string `json:"from_chat_id" sokel:"from_chat_id"`
	MessageID  int    `json:"message_id" sokel:"message_id"`
}

type ForwardMessageOut struct {
	OK        bool `json:"ok" sokel:"ok"`
	MessageID int  `json:"message_id" sokel:"message_id"`
	Result    any  `json:"result" sokel:"result"`
}

type GetChatIn struct {
	ChatID string `json:"chat_id" sokel:"chat_id"`
}

type GetChatOut struct {
	OK     bool `json:"ok" sokel:"ok"`
	Result any  `json:"result" sokel:"result"`
}

type GetMeIn struct {
}

type GetMeOut struct {
	OK     bool `json:"ok" sokel:"ok"`
	Result any  `json:"result" sokel:"result"`
}

type GetWebhookInfoIn struct {
}

type GetWebhookInfoOut struct {
	OK     bool `json:"ok" sokel:"ok"`
	Result any  `json:"result" sokel:"result"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK       bool   `json:"ok" sokel:"ok"`
	Username string `json:"username" sokel:"username"`
	Message  string `json:"message" sokel:"message"`
}

type SendChatActionIn struct {
	ChatID string `json:"chat_id" sokel:"chat_id"`
	Action string `json:"action" sokel:"action"`
}

type SendChatActionOut struct {
	OK     bool `json:"ok" sokel:"ok"`
	Result any  `json:"result" sokel:"result"`
}

type SendDocumentIn struct {
	ChatID   string `json:"chat_id" sokel:"chat_id"`
	Document string `json:"document" sokel:"document"`
	Caption  string `json:"caption" sokel:"caption"`
}

type SendDocumentOut struct {
	OK        bool `json:"ok" sokel:"ok"`
	MessageID int  `json:"message_id" sokel:"message_id"`
	Result    any  `json:"result" sokel:"result"`
}

type SendMessageIn struct {
	ChatID                string         `json:"chat_id" sokel:"chat_id"`
	Text                  string         `json:"text" sokel:"text"`
	ParseMode             string         `json:"parse_mode" sokel:"parse_mode"`
	ReplyToMessageID      int            `json:"reply_to_message_id" sokel:"reply_to_message_id"`
	ReplyMarkup           map[string]any `json:"reply_markup" sokel:"reply_markup"`
	DisableWebPagePreview bool           `json:"disable_web_page_preview" sokel:"disable_web_page_preview"`
}

type SendMessageOut struct {
	OK        bool `json:"ok" sokel:"ok"`
	MessageID int  `json:"message_id" sokel:"message_id"`
	Result    any  `json:"result" sokel:"result"`
}

type SendPhotoIn struct {
	ChatID    string `json:"chat_id" sokel:"chat_id"`
	Photo     string `json:"photo" sokel:"photo"`
	Caption   string `json:"caption" sokel:"caption"`
	ParseMode string `json:"parse_mode" sokel:"parse_mode"`
}

type SendPhotoOut struct {
	OK        bool `json:"ok" sokel:"ok"`
	MessageID int  `json:"message_id" sokel:"message_id"`
	Result    any  `json:"result" sokel:"result"`
}

type SetMyCommandsIn struct {
	Commands []schema.BotCommand `json:"commands" sokel:"commands"`
}

type SetMyCommandsOut struct {
	OK     bool `json:"ok" sokel:"ok"`
	Result any  `json:"result" sokel:"result"`
}

type SetWebhookIn struct {
	URL            string   `json:"url" sokel:"url"`
	SecretToken    string   `json:"secret_token" sokel:"secret_token"`
	AllowedUpdates []string `json:"allowed_updates" sokel:"allowed_updates"`
	MaxConnections int      `json:"max_connections" sokel:"max_connections"`
}

type SetWebhookOut struct {
	OK     bool `json:"ok" sokel:"ok"`
	Result any  `json:"result" sokel:"result"`
}
