// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	Kubeconfig      string `sokel:"kubeconfig" label:"kubeconfig" secret:"true"`
	Namespace       string `sokel:"namespace,optional" label:"默认命名空间"`
	WatchNamespaces string `sokel:"watch_namespaces,optional" label:"盯哪些命名空间"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "kubeconfig",
			Label:    "kubeconfig",
			Type:     contract.ParamType("secret"),
			Required: true,
			Desc:     "整份 YAML 粘进来（ACK 用 aliyun 插件的「导出 kubeconfig」一键取；自建集群 ~/.kube/config）。它就是进集群的钥匙，只在插件内部使用",
		},
		{
			Name:  "namespace",
			Label: "默认命名空间",
			Type:  contract.ParamType("text"),
			Desc:  "操作里没写命名空间时用它；留空 = default",
		},
		{
			Name:  "watch_namespaces",
			Label: "盯哪些命名空间",
			Type:  contract.ParamType("text"),
			Desc:  "逗号分隔（如 prod,staging）。**填了才启动事件源**：Pod 被驱逐 / 调度失败 / 容器异常退出 / 节点不健康 会触发工作流（轮询，约 1 分钟延迟）。留空 = 不盯，只能用「事件列表」操作自己定时拉",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
