// Code generated by sokel-gen. DO NOT EDIT.
//
// Event payload types and trigger functions are generated from the schema declaration.
// Change an event there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/kubernetes/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// NodeNotReadyEvent is the payload of the "节点不健康" event.
// 节点 Ready 条件不为 True（失联 / 磁盘压力 / 内存压力）
type NodeNotReadyEvent struct {
	Namespace string `json:"namespace" sokel:"namespace"`
	Node      string `json:"node" sokel:"node"`
	Status    string `json:"status" sokel:"status"`
	Message   string `json:"message" sokel:"message"`
}

// PodCrashedEvent is the payload of the "容器异常退出" event.
// 容器非正常结束（OOMKilled / 非零退出码），判据取自 Pod 状态而不是事件
type PodCrashedEvent struct {
	Namespace  string `json:"namespace" sokel:"namespace"`
	Object     string `json:"object" sokel:"object"`
	Pod        string `json:"pod" sokel:"pod"`
	Reason     string `json:"reason" sokel:"reason"`
	ExitCode   int    `json:"exit_code" sokel:"exit_code"`
	Restarts   int    `json:"restarts" sokel:"restarts"`
	Node       string `json:"node" sokel:"node"`
	FinishedAt string `json:"finished_at" sokel:"finished_at"`
	Phase      string `json:"phase" sokel:"phase"`
}

// PodEvictedEvent is the payload of the "Pod 被驱逐" event.
// 节点资源不足时 kubelet 主动赶走了 Pod（Event reason=Evicted）
type PodEvictedEvent struct {
	Namespace string `json:"namespace" sokel:"namespace"`
	Object    string `json:"object" sokel:"object"`
	Pod       string `json:"pod" sokel:"pod"`
	Message   string `json:"message" sokel:"message"`
	Node      string `json:"node" sokel:"node"`
	Count     int    `json:"count" sokel:"count"`
	LastSeen  string `json:"last_seen" sokel:"last_seen"`
}

// ScheduleFailedEvent is the payload of the "调度失败" event.
// Pod 起不来，没有节点能放下它（Event reason=FailedScheduling）
type ScheduleFailedEvent struct {
	Namespace string `json:"namespace" sokel:"namespace"`
	Object    string `json:"object" sokel:"object"`
	Pod       string `json:"pod" sokel:"pod"`
	Message   string `json:"message" sokel:"message"`
	Count     int    `json:"count" sokel:"count"`
	LastSeen  string `json:"last_seen" sokel:"last_seen"`
}

// DeclareEvents hands this plugin's event contracts to the host.
//
// Common-field consistency was checked at **generation time** (each one must exist in every
// event with the same type), so this cannot fail here — a real problem showed up at
// go generate.
func DeclareEvents(h plugin.EventHost) {
	events := []contract.Event{
		contract.EventOf(&schema.NodeNotReady{}),
		contract.EventOf(&schema.PodCrashed{}),
		contract.EventOf(&schema.PodEvicted{}),
		contract.EventOf(&schema.ScheduleFailed{}),
	}
	for _, e := range events {
		h.DeclareEvent(e)
	}
	names := []string{"namespace"}
	fields, _ := contract.ValidateCommonFields(events, names)
	h.DeclareEventsCommon(fields, names)
}

// TriggerNodeNotReady pushes one "节点不健康" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerNodeNotReady(ctx plugin.SourceCtx, eventID string, p *NodeNotReadyEvent) error {
	return ctx.Trigger("node_not_ready", eventID, p)
}

// TriggerPodCrashed pushes one "容器异常退出" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerPodCrashed(ctx plugin.SourceCtx, eventID string, p *PodCrashedEvent) error {
	return ctx.Trigger("pod_crashed", eventID, p)
}

// TriggerPodEvicted pushes one "Pod 被驱逐" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerPodEvicted(ctx plugin.SourceCtx, eventID string, p *PodEvictedEvent) error {
	return ctx.Trigger("pod_evicted", eventID, p)
}

// TriggerScheduleFailed pushes one "调度失败" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerScheduleFailed(ctx plugin.SourceCtx, eventID string, p *ScheduleFailedEvent) error {
	return ctx.Trigger("schedule_failed", eventID, p)
}
