// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/kubernetes/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnApplyManifest registers the implementation of "apply_manifest".
func OnApplyManifest(h plugin.Host, fn func(plugin.Ctx, *ApplyManifestIn) (*ApplyManifestOut, error)) {
	h.Register(contract.OperationOf(&schema.ApplyManifest{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ApplyManifestIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDeleteObject registers the implementation of "delete_object".
func OnDeleteObject(h plugin.Host, fn func(plugin.Ctx, *DeleteObjectIn) (*DeleteObjectOut, error)) {
	h.Register(contract.OperationOf(&schema.DeleteObject{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DeleteObjectIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDeployWorkload registers the implementation of "deploy_workload".
func OnDeployWorkload(h plugin.Host, fn func(plugin.Ctx, *DeployWorkloadIn) (*DeployWorkloadOut, error)) {
	h.Register(contract.OperationOf(&schema.DeployWorkload{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DeployWorkloadIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDeploymentRestart registers the implementation of "deployment_restart".
func OnDeploymentRestart(h plugin.Host, fn func(plugin.Ctx, *DeploymentRestartIn) (*DeploymentRestartOut, error)) {
	h.Register(contract.OperationOf(&schema.DeploymentRestart{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DeploymentRestartIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDeploymentScale registers the implementation of "deployment_scale".
func OnDeploymentScale(h plugin.Host, fn func(plugin.Ctx, *DeploymentScaleIn) (*DeploymentScaleOut, error)) {
	h.Register(contract.OperationOf(&schema.DeploymentScale{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DeploymentScaleIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDeploymentStatus registers the implementation of "deployment_status".
func OnDeploymentStatus(h plugin.Host, fn func(plugin.Ctx, *DeploymentStatusIn) (*DeploymentStatusOut, error)) {
	h.Register(contract.OperationOf(&schema.DeploymentStatus{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DeploymentStatusIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDeployments registers the implementation of "deployments".
func OnDeployments(h plugin.Host, fn func(plugin.Ctx, *DeploymentsIn) (*DeploymentsOut, error)) {
	h.Register(contract.OperationOf(&schema.Deployments{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DeploymentsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnEvents registers the implementation of "events".
func OnEvents(h plugin.Host, fn func(plugin.Ctx, *EventsIn) (*EventsOut, error)) {
	h.Register(contract.OperationOf(&schema.Events{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in EventsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnNodes registers the implementation of "nodes".
func OnNodes(h plugin.Host, fn func(plugin.Ctx, *NodesIn) (*NodesOut, error)) {
	h.Register(contract.OperationOf(&schema.Nodes{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in NodesIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPodLogs registers the implementation of "pod_logs".
func OnPodLogs(h plugin.Host, fn func(plugin.Ctx, *PodLogsIn) (*PodLogsOut, error)) {
	h.Register(contract.OperationOf(&schema.PodLogs{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PodLogsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPods registers the implementation of "pods".
func OnPods(h plugin.Host, fn func(plugin.Ctx, *PodsIn) (*PodsOut, error)) {
	h.Register(contract.OperationOf(&schema.Pods{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PodsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnRunJob registers the implementation of "run_job".
func OnRunJob(h plugin.Host, fn func(plugin.Ctx, *RunJobIn) (*RunJobOut, error)) {
	h.Register(contract.OperationOf(&schema.RunJob{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in RunJobIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
