// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/kubernetes/schema"
)

type ApplyManifestIn struct {
	Manifest  string `json:"manifest" sokel:"manifest"`
	Namespace string `json:"namespace" sokel:"namespace"`
}

type ApplyManifestOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Applied int    `json:"applied" sokel:"applied"`
	Items   string `json:"items" sokel:"items"`
}

type DeleteObjectIn struct {
	Namespace  string `json:"namespace" sokel:"namespace"`
	Kind       string `json:"kind" sokel:"kind"`
	Name       string `json:"name" sokel:"name"`
	APIVersion string `json:"api_version" sokel:"api_version"`
}

type DeleteObjectOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
}

type DeployWorkloadIn struct {
	Namespace       string            `json:"namespace" sokel:"namespace"`
	Name            string            `json:"name" sokel:"name"`
	Image           string            `json:"image" sokel:"image"`
	Replicas        int               `json:"replicas" sokel:"replicas"`
	Env             map[string]string `json:"env" sokel:"env"`
	Labels          map[string]string `json:"labels" sokel:"labels"`
	Command         []string          `json:"command" sokel:"command"`
	ImagePullSecret string            `json:"image_pull_secret" sokel:"image_pull_secret"`
	CPULimit        string            `json:"cpu_limit" sokel:"cpu_limit"`
	MemoryLimit     string            `json:"memory_limit" sokel:"memory_limit"`
}

type DeployWorkloadOut struct {
	OK        bool   `json:"ok" sokel:"ok"`
	Created   bool   `json:"created" sokel:"created"`
	Name      string `json:"name" sokel:"name"`
	Namespace string `json:"namespace" sokel:"namespace"`
}

type DeploymentRestartIn struct {
	Namespace string `json:"namespace" sokel:"namespace"`
	Name      string `json:"name" sokel:"name"`
}

type DeploymentRestartOut struct {
	OK          bool   `json:"ok" sokel:"ok"`
	RestartedAt string `json:"restarted_at" sokel:"restarted_at"`
}

type DeploymentScaleIn struct {
	Namespace string `json:"namespace" sokel:"namespace"`
	Name      string `json:"name" sokel:"name"`
	Replicas  int    `json:"replicas" sokel:"replicas"`
}

type DeploymentScaleOut struct {
	OK       bool `json:"ok" sokel:"ok"`
	Previous int  `json:"previous" sokel:"previous"`
}

type DeploymentStatusIn struct {
	Namespace string `json:"namespace" sokel:"namespace"`
	Name      string `json:"name" sokel:"name"`
}

type DeploymentStatusOut struct {
	Ready         bool   `json:"ready" sokel:"ready"`
	Desired       int    `json:"desired" sokel:"desired"`
	ReadyReplicas int    `json:"ready_replicas" sokel:"ready_replicas"`
	Available     int    `json:"available" sokel:"available"`
	Image         string `json:"image" sokel:"image"`
	Message       string `json:"message" sokel:"message"`
}

type DeploymentsIn struct {
	Namespace string `json:"namespace" sokel:"namespace"`
}

type DeploymentsOut struct {
	Deployments []schema.Deployment `json:"deployments" sokel:"deployments"`
	Count       int                 `json:"count" sokel:"count"`
}

type EventsIn struct {
	Namespace   string   `json:"namespace" sokel:"namespace"`
	OnlyWarning bool     `json:"only_warning" sokel:"only_warning"`
	Limit       int      `json:"limit" sokel:"limit"`
	Since       string   `json:"since" sokel:"since"`
	Reasons     []string `json:"reasons" sokel:"reasons"`
}

type EventsOut struct {
	Events    []schema.Event `json:"events" sokel:"events"`
	Count     int            `json:"count" sokel:"count"`
	Truncated bool           `json:"truncated" sokel:"truncated"`
	CheckedAt string         `json:"checked_at" sokel:"checked_at"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Version string `json:"version" sokel:"version"`
	Message string `json:"message" sokel:"message"`
}

type NodesIn struct {
}

type NodesOut struct {
	Nodes    []schema.Node `json:"nodes" sokel:"nodes"`
	Count    int           `json:"count" sokel:"count"`
	NotReady int           `json:"not_ready" sokel:"not_ready"`
}

type PodLogsIn struct {
	Namespace string `json:"namespace" sokel:"namespace"`
	Pod       string `json:"pod" sokel:"pod"`
	Container string `json:"container" sokel:"container"`
	TailLines int    `json:"tail_lines" sokel:"tail_lines"`
	Previous  bool   `json:"previous" sokel:"previous"`
}

type PodLogsOut struct {
	Logs  string `json:"logs" sokel:"logs"`
	Lines int    `json:"lines" sokel:"lines"`
}

type PodsIn struct {
	Namespace     string `json:"namespace" sokel:"namespace"`
	LabelSelector string `json:"label_selector" sokel:"label_selector"`
	OnlyAbnormal  bool   `json:"only_abnormal" sokel:"only_abnormal"`
}

type PodsOut struct {
	Pods  []schema.Pod `json:"pods" sokel:"pods"`
	Count int          `json:"count" sokel:"count"`
}

type RunJobIn struct {
	Namespace  string            `json:"namespace" sokel:"namespace"`
	NamePrefix string            `json:"name_prefix" sokel:"name_prefix"`
	Image      string            `json:"image" sokel:"image"`
	Command    []string          `json:"command" sokel:"command"`
	Env        map[string]string `json:"env" sokel:"env"`
	Wait       bool              `json:"wait" sokel:"wait"`
	TimeoutSec int               `json:"timeout_sec" sokel:"timeout_sec"`
}

type RunJobOut struct {
	Job       string `json:"job" sokel:"job"`
	Succeeded bool   `json:"succeeded" sokel:"succeeded"`
	Status    string `json:"status" sokel:"status"`
	Logs      string `json:"logs" sokel:"logs"`
}
