// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/reddit/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnRedditPostComments registers the implementation of "reddit_post_comments".
func OnRedditPostComments(h plugin.Host, fn func(plugin.Ctx, *RedditPostCommentsIn) (*RedditPostCommentsOut, error)) {
	h.Register(contract.OperationOf(&schema.PostComments{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in RedditPostCommentsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnRedditSearch registers the implementation of "reddit_search".
func OnRedditSearch(h plugin.Host, fn func(plugin.Ctx, *RedditSearchIn) (*RedditSearchOut, error)) {
	h.Register(contract.OperationOf(&schema.Search{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in RedditSearchIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnRedditSubredditNew registers the implementation of "reddit_subreddit_new".
func OnRedditSubredditNew(h plugin.Host, fn func(plugin.Ctx, *RedditSubredditNewIn) (*RedditSubredditNewOut, error)) {
	h.Register(contract.OperationOf(&schema.SubredditNew{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in RedditSubredditNewIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnRedditUserPosts registers the implementation of "reddit_user_posts".
func OnRedditUserPosts(h plugin.Host, fn func(plugin.Ctx, *RedditUserPostsIn) (*RedditUserPostsOut, error)) {
	h.Register(contract.OperationOf(&schema.UserPosts{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in RedditUserPostsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
