// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/reddit/schema"
)

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
}

type RedditPostCommentsIn struct {
	Post string `json:"post" sokel:"post"`
}

type RedditPostCommentsOut struct {
	Post  schema.Item   `json:"post" sokel:"post"`
	Items []schema.Item `json:"items" sokel:"items"`
	Count int           `json:"count" sokel:"count"`
}

type RedditSearchIn struct {
	Query      string `json:"query" sokel:"query"`
	Subreddits string `json:"subreddits" sokel:"subreddits"`
	Sort       string `json:"sort" sokel:"sort"`
	Time       string `json:"time" sokel:"time"`
}

type RedditSearchOut struct {
	Items []schema.Item `json:"items" sokel:"items"`
	Count int           `json:"count" sokel:"count"`
}

type RedditSubredditNewIn struct {
	Subreddits string `json:"subreddits" sokel:"subreddits"`
}

type RedditSubredditNewOut struct {
	Items []schema.Item `json:"items" sokel:"items"`
	Count int           `json:"count" sokel:"count"`
}

type RedditUserPostsIn struct {
	Username string `json:"username" sokel:"username"`
}

type RedditUserPostsOut struct {
	Items []schema.Item `json:"items" sokel:"items"`
	Count int           `json:"count" sokel:"count"`
}
