// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	BaseURL       string `sokel:"base_url,optional" label:"GitHub 地址"`
	Token         string `sokel:"token" label:"访问令牌" secret:"true"`
	WebhookSecret string `sokel:"webhook_secret,optional" label:"Webhook Secret" secret:"true"`
	WatchRepos    string `sokel:"watch_repos,optional" label:"事件盯哪些仓库"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:  "base_url",
			Label: "GitHub 地址",
			Type:  contract.ParamType("text"),
			Desc:  "GitHub Enterprise Server 填根地址（如 https://github.example.com，**不用带 /api/v3**，插件会补）；留空 = github.com",
		},
		{
			Name:     "token",
			Label:    "访问令牌",
			Type:     contract.ParamType("secret"),
			Required: true,
			Desc:     "个人访问令牌。经典令牌勾 repo（私有仓库）与 workflow（触发 Actions）；细粒度令牌按仓库授权，至少给 Contents/Issues/Pull requests 读写，要回写检查结果再加 Commit statuses 与 Checks。建议专建一个机器人账号",
		},
		{
			Name:  "webhook_secret",
			Label: "Webhook Secret",
			Type:  contract.ParamType("secret"),
			Desc:  "平台代收 webhook 用：GitHub 仓库 Settings→Webhooks 里填的 Secret，两边一致才收（**HMAC-SHA256 验签**）。不用 webhook 可留空",
		},
		{
			Name:  "watch_repos",
			Label: "事件盯哪些仓库",
			Type:  contract.ParamType("text"),
			Desc:  "owner/repo 逗号分隔（如 sokel-dev/sokel,acme/infra）。**填了才启动轮询事件源**：新提交/新 PR/合并/新 Issue/评论/工作流失败 会触发工作流（约 1 分钟延迟）。配了 Webhook 就**不要**再填这个——两条路会各触发一次",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
