// Code generated by sokel-gen. DO NOT EDIT.
//
// Event payload types and trigger functions are generated from the schema declaration.
// Change an event there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/github/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// CommitPushedEvent is the payload of the "有新提交" event.
// 有人往被监听的仓库推了提交
type CommitPushedEvent struct {
	Repo          string `json:"repo" sokel:"repo"`
	Ref           string `json:"ref" sokel:"ref"`
	CommitSHA     string `json:"commit_sha" sokel:"commit_sha"`
	CommitMessage string `json:"commit_message" sokel:"commit_message"`
	CommitCount   int    `json:"commit_count" sokel:"commit_count"`
	Author        string `json:"author" sokel:"author"`
	Forced        bool   `json:"forced" sokel:"forced"`
	Created       bool   `json:"created" sokel:"created"`
	Deleted       bool   `json:"deleted" sokel:"deleted"`
	Source        string `json:"source" sokel:"source"`
}

// IssueCommentedEvent is the payload of the "Issue 有新评论" event.
// Issue 下有人发言（ChatOps 斜杠命令从这里进）
type IssueCommentedEvent struct {
	Repo              string `json:"repo" sokel:"repo"`
	Number            int    `json:"number" sokel:"number"`
	Title             string `json:"title" sokel:"title"`
	Comment           string `json:"comment" sokel:"comment"`
	CommentID         int    `json:"comment_id" sokel:"comment_id"`
	Author            string `json:"author" sokel:"author"`
	AuthorAssociation string `json:"author_association" sokel:"author_association"`
	IsBot             bool   `json:"is_bot" sokel:"is_bot"`
	URL               string `json:"url" sokel:"url"`
	Source            string `json:"source" sokel:"source"`
}

// IssueLabeledEvent is the payload of the "Issue 被打标签" event.
// Issue 或 PR 被加上了标签（摘标签不触发）
type IssueLabeledEvent struct {
	Repo       string   `json:"repo" sokel:"repo"`
	Number     int      `json:"number" sokel:"number"`
	Title      string   `json:"title" sokel:"title"`
	Body       string   `json:"body" sokel:"body"`
	AddedLabel string   `json:"added_label" sokel:"added_label"`
	Labels     []string `json:"labels" sokel:"labels"`
	IsPr       bool     `json:"is_pr" sokel:"is_pr"`
	Actor      string   `json:"actor" sokel:"actor"`
	URL        string   `json:"url" sokel:"url"`
	Source     string   `json:"source" sokel:"source"`
}

// IssueOpenedEvent is the payload of the "新 Issue" event.
// 有人开了 Issue
type IssueOpenedEvent struct {
	Repo   string   `json:"repo" sokel:"repo"`
	Number int      `json:"number" sokel:"number"`
	Title  string   `json:"title" sokel:"title"`
	Body   string   `json:"body" sokel:"body"`
	Author string   `json:"author" sokel:"author"`
	Labels []string `json:"labels" sokel:"labels"`
	URL    string   `json:"url" sokel:"url"`
	Source string   `json:"source" sokel:"source"`
}

// PrCommentedEvent is the payload of the "PR 有新评论" event.
// PR 下有人发言（GitHub 与 Issue 评论同一个事件，这里按是不是 PR 拆开）
type PrCommentedEvent struct {
	Repo              string `json:"repo" sokel:"repo"`
	Number            int    `json:"number" sokel:"number"`
	Title             string `json:"title" sokel:"title"`
	Comment           string `json:"comment" sokel:"comment"`
	CommentID         int    `json:"comment_id" sokel:"comment_id"`
	Author            string `json:"author" sokel:"author"`
	AuthorAssociation string `json:"author_association" sokel:"author_association"`
	IsBot             bool   `json:"is_bot" sokel:"is_bot"`
	URL               string `json:"url" sokel:"url"`
	Source            string `json:"source" sokel:"source"`
}

// PrMergedEvent is the payload of the "PR 被合并" event.
// PR 合并进目标分支（**关掉不合不算**）
type PrMergedEvent struct {
	Repo     string   `json:"repo" sokel:"repo"`
	Number   int      `json:"number" sokel:"number"`
	Title    string   `json:"title" sokel:"title"`
	Author   string   `json:"author" sokel:"author"`
	MergedBy string   `json:"merged_by" sokel:"merged_by"`
	Base     string   `json:"base" sokel:"base"`
	MergeSHA string   `json:"merge_sha" sokel:"merge_sha"`
	Labels   []string `json:"labels" sokel:"labels"`
	URL      string   `json:"url" sokel:"url"`
	Source   string   `json:"source" sokel:"source"`
}

// PrOpenedEvent is the payload of the "新 PR" event.
// 有人开了 Pull Request
type PrOpenedEvent struct {
	Repo    string   `json:"repo" sokel:"repo"`
	Number  int      `json:"number" sokel:"number"`
	Title   string   `json:"title" sokel:"title"`
	Body    string   `json:"body" sokel:"body"`
	Author  string   `json:"author" sokel:"author"`
	Base    string   `json:"base" sokel:"base"`
	Head    string   `json:"head" sokel:"head"`
	HeadSHA string   `json:"head_sha" sokel:"head_sha"`
	Draft   bool     `json:"draft" sokel:"draft"`
	Labels  []string `json:"labels" sokel:"labels"`
	URL     string   `json:"url" sokel:"url"`
	Source  string   `json:"source" sokel:"source"`
}

// PrReviewSubmittedEvent is the payload of the "PR 有评审" event.
// 有人提交了评审结论（通过/请求修改/评论）
type PrReviewSubmittedEvent struct {
	Repo     string `json:"repo" sokel:"repo"`
	Number   int    `json:"number" sokel:"number"`
	Title    string `json:"title" sokel:"title"`
	Reviewer string `json:"reviewer" sokel:"reviewer"`
	State    string `json:"state" sokel:"state"`
	Body     string `json:"body" sokel:"body"`
	HeadSHA  string `json:"head_sha" sokel:"head_sha"`
	URL      string `json:"url" sokel:"url"`
	Source   string `json:"source" sokel:"source"`
}

// ReleasePublishedEvent is the payload of the "有新发布" event.
// 发布了一个 Release（草稿转正式也算）
type ReleasePublishedEvent struct {
	Repo       string `json:"repo" sokel:"repo"`
	Tag        string `json:"tag" sokel:"tag"`
	Name       string `json:"name" sokel:"name"`
	Body       string `json:"body" sokel:"body"`
	Prerelease bool   `json:"prerelease" sokel:"prerelease"`
	Author     string `json:"author" sokel:"author"`
	URL        string `json:"url" sokel:"url"`
	Source     string `json:"source" sokel:"source"`
}

// WorkflowFailedEvent is the payload of the "工作流失败" event.
// Actions 跑挂了（只在结论是 failure 时触发，取消与跳过不算）
type WorkflowFailedEvent struct {
	Repo      string `json:"repo" sokel:"repo"`
	Workflow  string `json:"workflow" sokel:"workflow"`
	RunID     int    `json:"run_id" sokel:"run_id"`
	Branch    string `json:"branch" sokel:"branch"`
	CommitSHA string `json:"commit_sha" sokel:"commit_sha"`
	Event     string `json:"event" sokel:"event"`
	Actor     string `json:"actor" sokel:"actor"`
	Attempt   int    `json:"attempt" sokel:"attempt"`
	URL       string `json:"url" sokel:"url"`
	Source    string `json:"source" sokel:"source"`
}

// DeclareEvents hands this plugin's event contracts to the host.
//
// Common-field consistency was checked at **generation time** (each one must exist in every
// event with the same type), so this cannot fail here — a real problem showed up at
// go generate.
func DeclareEvents(h plugin.EventHost) {
	events := []contract.Event{
		contract.EventOf(&schema.CommitPushed{}),
		contract.EventOf(&schema.IssueCommented{}),
		contract.EventOf(&schema.IssueLabeled{}),
		contract.EventOf(&schema.IssueOpened{}),
		contract.EventOf(&schema.PrCommented{}),
		contract.EventOf(&schema.PrMerged{}),
		contract.EventOf(&schema.PrOpened{}),
		contract.EventOf(&schema.PrReviewSubmitted{}),
		contract.EventOf(&schema.ReleasePublished{}),
		contract.EventOf(&schema.WorkflowFailed{}),
	}
	for _, e := range events {
		h.DeclareEvent(e)
	}
	names := []string{"repo"}
	fields, _ := contract.ValidateCommonFields(events, names)
	h.DeclareEventsCommon(fields, names)
}

// TriggerCommitPushed pushes one "有新提交" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerCommitPushed(ctx plugin.SourceCtx, eventID string, p *CommitPushedEvent) error {
	return ctx.Trigger("commit_pushed", eventID, p)
}

// TriggerIssueCommented pushes one "Issue 有新评论" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerIssueCommented(ctx plugin.SourceCtx, eventID string, p *IssueCommentedEvent) error {
	return ctx.Trigger("issue_commented", eventID, p)
}

// TriggerIssueLabeled pushes one "Issue 被打标签" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerIssueLabeled(ctx plugin.SourceCtx, eventID string, p *IssueLabeledEvent) error {
	return ctx.Trigger("issue_labeled", eventID, p)
}

// TriggerIssueOpened pushes one "新 Issue" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerIssueOpened(ctx plugin.SourceCtx, eventID string, p *IssueOpenedEvent) error {
	return ctx.Trigger("issue_opened", eventID, p)
}

// TriggerPrCommented pushes one "PR 有新评论" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerPrCommented(ctx plugin.SourceCtx, eventID string, p *PrCommentedEvent) error {
	return ctx.Trigger("pr_commented", eventID, p)
}

// TriggerPrMerged pushes one "PR 被合并" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerPrMerged(ctx plugin.SourceCtx, eventID string, p *PrMergedEvent) error {
	return ctx.Trigger("pr_merged", eventID, p)
}

// TriggerPrOpened pushes one "新 PR" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerPrOpened(ctx plugin.SourceCtx, eventID string, p *PrOpenedEvent) error {
	return ctx.Trigger("pr_opened", eventID, p)
}

// TriggerPrReviewSubmitted pushes one "PR 有评审" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerPrReviewSubmitted(ctx plugin.SourceCtx, eventID string, p *PrReviewSubmittedEvent) error {
	return ctx.Trigger("pr_review_submitted", eventID, p)
}

// TriggerReleasePublished pushes one "有新发布" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerReleasePublished(ctx plugin.SourceCtx, eventID string, p *ReleasePublishedEvent) error {
	return ctx.Trigger("release_published", eventID, p)
}

// TriggerWorkflowFailed pushes one "工作流失败" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerWorkflowFailed(ctx plugin.SourceCtx, eventID string, p *WorkflowFailedEvent) error {
	return ctx.Trigger("workflow_failed", eventID, p)
}
