// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/github/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnBranchCreate registers the implementation of "branch_create".
func OnBranchCreate(h plugin.Host, fn func(plugin.Ctx, *BranchCreateIn) (*BranchCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.BranchCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BranchCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnBranchProtectionGet registers the implementation of "branch_protection_get".
func OnBranchProtectionGet(h plugin.Host, fn func(plugin.Ctx, *BranchProtectionGetIn) (*BranchProtectionGetOut, error)) {
	h.Register(contract.OperationOf(&schema.BranchProtectionGet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BranchProtectionGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnBranchesList registers the implementation of "branches_list".
func OnBranchesList(h plugin.Host, fn func(plugin.Ctx, *BranchesListIn) (*BranchesListOut, error)) {
	h.Register(contract.OperationOf(&schema.BranchesList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in BranchesListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCall registers the implementation of "call".
func OnCall(h plugin.Host, fn func(plugin.Ctx, *CallIn) (*CallOut, error)) {
	h.Register(contract.OperationOf(&schema.Call{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CallIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCheckRunCreate registers the implementation of "check_run_create".
func OnCheckRunCreate(h plugin.Host, fn func(plugin.Ctx, *CheckRunCreateIn) (*CheckRunCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.CheckRunCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CheckRunCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCollaboratorsList registers the implementation of "collaborators_list".
func OnCollaboratorsList(h plugin.Host, fn func(plugin.Ctx, *CollaboratorsListIn) (*CollaboratorsListOut, error)) {
	h.Register(contract.OperationOf(&schema.CollaboratorsList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CollaboratorsListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCommitStatusCreate registers the implementation of "commit_status_create".
func OnCommitStatusCreate(h plugin.Host, fn func(plugin.Ctx, *CommitStatusCreateIn) (*CommitStatusCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.CommitStatusCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CommitStatusCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnCommitsList registers the implementation of "commits_list".
func OnCommitsList(h plugin.Host, fn func(plugin.Ctx, *CommitsListIn) (*CommitsListOut, error)) {
	h.Register(contract.OperationOf(&schema.CommitsList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CommitsListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnFileGet registers the implementation of "file_get".
func OnFileGet(h plugin.Host, fn func(plugin.Ctx, *FileGetIn) (*FileGetOut, error)) {
	h.Register(contract.OperationOf(&schema.FileGet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in FileGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnFileWrite registers the implementation of "file_write".
func OnFileWrite(h plugin.Host, fn func(plugin.Ctx, *FileWriteIn) (*FileWriteOut, error)) {
	h.Register(contract.OperationOf(&schema.FileWrite{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in FileWriteIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIssueAssign registers the implementation of "issue_assign".
func OnIssueAssign(h plugin.Host, fn func(plugin.Ctx, *IssueAssignIn) (*IssueAssignOut, error)) {
	h.Register(contract.OperationOf(&schema.IssueAssign{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IssueAssignIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIssueComment registers the implementation of "issue_comment".
func OnIssueComment(h plugin.Host, fn func(plugin.Ctx, *IssueCommentIn) (*IssueCommentOut, error)) {
	h.Register(contract.OperationOf(&schema.IssueComment{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IssueCommentIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIssueCreate registers the implementation of "issue_create".
func OnIssueCreate(h plugin.Host, fn func(plugin.Ctx, *IssueCreateIn) (*IssueCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.IssueCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IssueCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIssueGet registers the implementation of "issue_get".
func OnIssueGet(h plugin.Host, fn func(plugin.Ctx, *IssueGetIn) (*IssueGetOut, error)) {
	h.Register(contract.OperationOf(&schema.IssueGet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IssueGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIssueLabel registers the implementation of "issue_label".
func OnIssueLabel(h plugin.Host, fn func(plugin.Ctx, *IssueLabelIn) (*IssueLabelOut, error)) {
	h.Register(contract.OperationOf(&schema.IssueLabel{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IssueLabelIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIssueUpdate registers the implementation of "issue_update".
func OnIssueUpdate(h plugin.Host, fn func(plugin.Ctx, *IssueUpdateIn) (*IssueUpdateOut, error)) {
	h.Register(contract.OperationOf(&schema.IssueUpdate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IssueUpdateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIssuesList registers the implementation of "issues_list".
func OnIssuesList(h plugin.Host, fn func(plugin.Ctx, *IssuesListIn) (*IssuesListOut, error)) {
	h.Register(contract.OperationOf(&schema.IssuesList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IssuesListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnJobLog registers the implementation of "job_log".
func OnJobLog(h plugin.Host, fn func(plugin.Ctx, *JobLogIn) (*JobLogOut, error)) {
	h.Register(contract.OperationOf(&schema.JobLog{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in JobLogIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnLabelCreate registers the implementation of "label_create".
func OnLabelCreate(h plugin.Host, fn func(plugin.Ctx, *LabelCreateIn) (*LabelCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.LabelCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in LabelCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnLabelsList registers the implementation of "labels_list".
func OnLabelsList(h plugin.Host, fn func(plugin.Ctx, *LabelsListIn) (*LabelsListOut, error)) {
	h.Register(contract.OperationOf(&schema.LabelsList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in LabelsListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnMilestonesList registers the implementation of "milestones_list".
func OnMilestonesList(h plugin.Host, fn func(plugin.Ctx, *MilestonesListIn) (*MilestonesListOut, error)) {
	h.Register(contract.OperationOf(&schema.MilestonesList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in MilestonesListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPrCreate registers the implementation of "pr_create".
func OnPrCreate(h plugin.Host, fn func(plugin.Ctx, *PrCreateIn) (*PrCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.PrCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PrCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPrFiles registers the implementation of "pr_files".
func OnPrFiles(h plugin.Host, fn func(plugin.Ctx, *PrFilesIn) (*PrFilesOut, error)) {
	h.Register(contract.OperationOf(&schema.PrFiles{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PrFilesIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPrGet registers the implementation of "pr_get".
func OnPrGet(h plugin.Host, fn func(plugin.Ctx, *PrGetIn) (*PrGetOut, error)) {
	h.Register(contract.OperationOf(&schema.PrGet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PrGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPrList registers the implementation of "pr_list".
func OnPrList(h plugin.Host, fn func(plugin.Ctx, *PrListIn) (*PrListOut, error)) {
	h.Register(contract.OperationOf(&schema.PrList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PrListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPrMerge registers the implementation of "pr_merge".
func OnPrMerge(h plugin.Host, fn func(plugin.Ctx, *PrMergeIn) (*PrMergeOut, error)) {
	h.Register(contract.OperationOf(&schema.PrMerge{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PrMergeIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPrRequestReviewers registers the implementation of "pr_request_reviewers".
func OnPrRequestReviewers(h plugin.Host, fn func(plugin.Ctx, *PrRequestReviewersIn) (*PrRequestReviewersOut, error)) {
	h.Register(contract.OperationOf(&schema.PrRequestReviewers{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PrRequestReviewersIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPrReview registers the implementation of "pr_review".
func OnPrReview(h plugin.Host, fn func(plugin.Ctx, *PrReviewIn) (*PrReviewOut, error)) {
	h.Register(contract.OperationOf(&schema.PrReview{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PrReviewIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPrUpdate registers the implementation of "pr_update".
func OnPrUpdate(h plugin.Host, fn func(plugin.Ctx, *PrUpdateIn) (*PrUpdateOut, error)) {
	h.Register(contract.OperationOf(&schema.PrUpdate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PrUpdateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnProjectItemAdd registers the implementation of "project_item_add".
func OnProjectItemAdd(h plugin.Host, fn func(plugin.Ctx, *ProjectItemAddIn) (*ProjectItemAddOut, error)) {
	h.Register(contract.OperationOf(&schema.ProjectItemAdd{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ProjectItemAddIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnProjectItemFieldSet registers the implementation of "project_item_field_set".
func OnProjectItemFieldSet(h plugin.Host, fn func(plugin.Ctx, *ProjectItemFieldSetIn) (*ProjectItemFieldSetOut, error)) {
	h.Register(contract.OperationOf(&schema.ProjectItemFieldSet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ProjectItemFieldSetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnProjectItemsList registers the implementation of "project_items_list".
func OnProjectItemsList(h plugin.Host, fn func(plugin.Ctx, *ProjectItemsListIn) (*ProjectItemsListOut, error)) {
	h.Register(contract.OperationOf(&schema.ProjectItemsList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ProjectItemsListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnProjectsList registers the implementation of "projects_list".
func OnProjectsList(h plugin.Host, fn func(plugin.Ctx, *ProjectsListIn) (*ProjectsListOut, error)) {
	h.Register(contract.OperationOf(&schema.ProjectsList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ProjectsListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnReactionAdd registers the implementation of "reaction_add".
func OnReactionAdd(h plugin.Host, fn func(plugin.Ctx, *ReactionAddIn) (*ReactionAddOut, error)) {
	h.Register(contract.OperationOf(&schema.ReactionAdd{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ReactionAddIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnReleaseCreate registers the implementation of "release_create".
func OnReleaseCreate(h plugin.Host, fn func(plugin.Ctx, *ReleaseCreateIn) (*ReleaseCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.ReleaseCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ReleaseCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnReleasesList registers the implementation of "releases_list".
func OnReleasesList(h plugin.Host, fn func(plugin.Ctx, *ReleasesListIn) (*ReleasesListOut, error)) {
	h.Register(contract.OperationOf(&schema.ReleasesList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ReleasesListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnRepoGet registers the implementation of "repo_get".
func OnRepoGet(h plugin.Host, fn func(plugin.Ctx, *RepoGetIn) (*RepoGetOut, error)) {
	h.Register(contract.OperationOf(&schema.RepoGet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in RepoGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnReposList registers the implementation of "repos_list".
func OnReposList(h plugin.Host, fn func(plugin.Ctx, *ReposListIn) (*ReposListOut, error)) {
	h.Register(contract.OperationOf(&schema.ReposList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ReposListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnRunJobs registers the implementation of "run_jobs".
func OnRunJobs(h plugin.Host, fn func(plugin.Ctx, *RunJobsIn) (*RunJobsOut, error)) {
	h.Register(contract.OperationOf(&schema.RunJobs{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in RunJobsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSearch registers the implementation of "search".
func OnSearch(h plugin.Host, fn func(plugin.Ctx, *SearchIn) (*SearchOut, error)) {
	h.Register(contract.OperationOf(&schema.Search{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SearchIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnWorkflowDispatch registers the implementation of "workflow_dispatch".
func OnWorkflowDispatch(h plugin.Host, fn func(plugin.Ctx, *WorkflowDispatchIn) (*WorkflowDispatchOut, error)) {
	h.Register(contract.OperationOf(&schema.WorkflowDispatch{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in WorkflowDispatchIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnWorkflowRunsList registers the implementation of "workflow_runs_list".
func OnWorkflowRunsList(h plugin.Host, fn func(plugin.Ctx, *WorkflowRunsListIn) (*WorkflowRunsListOut, error)) {
	h.Register(contract.OperationOf(&schema.WorkflowRunsList{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in WorkflowRunsListIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
