// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/github/schema"
)

type BranchCreateIn struct {
	Repo   string `json:"repo" sokel:"repo"`
	Branch string `json:"branch" sokel:"branch"`
	From   string `json:"from" sokel:"from"`
}

type BranchCreateOut struct {
	Branch  string `json:"branch" sokel:"branch"`
	SHA     string `json:"sha" sokel:"sha"`
	Existed bool   `json:"existed" sokel:"existed"`
}

type BranchProtectionGetIn struct {
	Repo   string `json:"repo" sokel:"repo"`
	Branch string `json:"branch" sokel:"branch"`
}

type BranchProtectionGetOut struct {
	Protected              bool     `json:"protected" sokel:"protected"`
	RequiredApprovals      int      `json:"required_approvals" sokel:"required_approvals"`
	DismissStaleReviews    bool     `json:"dismiss_stale_reviews" sokel:"dismiss_stale_reviews"`
	RequireCodeOwnerReview bool     `json:"require_code_owner_review" sokel:"require_code_owner_review"`
	RequiredChecks         []string `json:"required_checks" sokel:"required_checks"`
	EnforceAdmins          bool     `json:"enforce_admins" sokel:"enforce_admins"`
	AllowForcePush         bool     `json:"allow_force_push" sokel:"allow_force_push"`
	RequiredLinearHistory  bool     `json:"required_linear_history" sokel:"required_linear_history"`
}

type BranchesListIn struct {
	Repo string `json:"repo" sokel:"repo"`
	Page int    `json:"page" sokel:"page"`
}

type BranchesListOut struct {
	Branches []schema.Branch `json:"branches" sokel:"branches"`
	Count    int             `json:"count" sokel:"count"`
	HasMore  bool            `json:"has_more" sokel:"has_more"`
}

type CallIn struct {
	Method string            `json:"method" sokel:"method"`
	Path   string            `json:"path" sokel:"path"`
	Body   any               `json:"body" sokel:"body"`
	Query  map[string]string `json:"query" sokel:"query"`
}

type CallOut struct {
	Status  int  `json:"status" sokel:"status"`
	Data    any  `json:"data" sokel:"data"`
	HasMore bool `json:"has_more" sokel:"has_more"`
}

type CheckRunCreateIn struct {
	Repo        string              `json:"repo" sokel:"repo"`
	SHA         string              `json:"sha" sokel:"sha"`
	Name        string              `json:"name" sokel:"name"`
	Conclusion  string              `json:"conclusion" sokel:"conclusion"`
	Title       string              `json:"title" sokel:"title"`
	Summary     string              `json:"summary" sokel:"summary"`
	Details     string              `json:"details" sokel:"details"`
	Annotations []schema.Annotation `json:"annotations" sokel:"annotations"`
	DetailsURL  string              `json:"details_url" sokel:"details_url"`
}

type CheckRunCreateOut struct {
	CheckRunID      int    `json:"check_run_id" sokel:"check_run_id"`
	URL             string `json:"url" sokel:"url"`
	AnnotationsSent int    `json:"annotations_sent" sokel:"annotations_sent"`
}

type CollaboratorsListIn struct {
	Repo       string `json:"repo" sokel:"repo"`
	Permission string `json:"permission" sokel:"permission"`
	Page       int    `json:"page" sokel:"page"`
}

type CollaboratorsListOut struct {
	Collaborators []schema.Collaborator `json:"collaborators" sokel:"collaborators"`
	Count         int                   `json:"count" sokel:"count"`
	HasMore       bool                  `json:"has_more" sokel:"has_more"`
}

type CommitStatusCreateIn struct {
	Repo        string `json:"repo" sokel:"repo"`
	SHA         string `json:"sha" sokel:"sha"`
	State       string `json:"state" sokel:"state"`
	Context     string `json:"context" sokel:"context"`
	Description string `json:"description" sokel:"description"`
	TargetURL   string `json:"target_url" sokel:"target_url"`
}

type CommitStatusCreateOut struct {
	StatusID int    `json:"status_id" sokel:"status_id"`
	Context  string `json:"context" sokel:"context"`
}

type CommitsListIn struct {
	Repo   string `json:"repo" sokel:"repo"`
	Branch string `json:"branch" sokel:"branch"`
	Path   string `json:"path" sokel:"path"`
	Since  string `json:"since" sokel:"since"`
	Page   int    `json:"page" sokel:"page"`
}

type CommitsListOut struct {
	Commits []schema.Commit `json:"commits" sokel:"commits"`
	Count   int             `json:"count" sokel:"count"`
	HasMore bool            `json:"has_more" sokel:"has_more"`
}

type FileGetIn struct {
	Repo string `json:"repo" sokel:"repo"`
	Path string `json:"path" sokel:"path"`
	Ref  string `json:"ref" sokel:"ref"`
}

type FileGetOut struct {
	Content string `json:"content" sokel:"content"`
	SHA     string `json:"sha" sokel:"sha"`
	Size    int    `json:"size" sokel:"size"`
	URL     string `json:"url" sokel:"url"`
}

type FileWriteIn struct {
	Repo    string `json:"repo" sokel:"repo"`
	Path    string `json:"path" sokel:"path"`
	Content string `json:"content" sokel:"content"`
	Message string `json:"message" sokel:"message"`
	Branch  string `json:"branch" sokel:"branch"`
}

type FileWriteOut struct {
	CommitSHA string `json:"commit_sha" sokel:"commit_sha"`
	SHA       string `json:"sha" sokel:"sha"`
	Created   bool   `json:"created" sokel:"created"`
	URL       string `json:"url" sokel:"url"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK            bool     `json:"ok" sokel:"ok"`
	Message       string   `json:"message" sokel:"message"`
	Login         string   `json:"login" sokel:"login"`
	Scopes        []string `json:"scopes" sokel:"scopes"`
	RateRemaining int      `json:"rate_remaining" sokel:"rate_remaining"`
}

type IssueAssignIn struct {
	Repo      string   `json:"repo" sokel:"repo"`
	Number    int      `json:"number" sokel:"number"`
	Mode      string   `json:"mode" sokel:"mode"`
	Assignees []string `json:"assignees" sokel:"assignees"`
}

type IssueAssignOut struct {
	Assignees []string `json:"assignees" sokel:"assignees"`
}

type IssueCommentIn struct {
	Repo   string `json:"repo" sokel:"repo"`
	Number int    `json:"number" sokel:"number"`
	Body   string `json:"body" sokel:"body"`
}

type IssueCommentOut struct {
	CommentID int    `json:"comment_id" sokel:"comment_id"`
	URL       string `json:"url" sokel:"url"`
}

type IssueCreateIn struct {
	Repo      string   `json:"repo" sokel:"repo"`
	Title     string   `json:"title" sokel:"title"`
	Body      string   `json:"body" sokel:"body"`
	Labels    []string `json:"labels" sokel:"labels"`
	Assignees []string `json:"assignees" sokel:"assignees"`
	Milestone string   `json:"milestone" sokel:"milestone"`
}

type IssueCreateOut struct {
	Number int    `json:"number" sokel:"number"`
	URL    string `json:"url" sokel:"url"`
}

type IssueGetIn struct {
	Repo         string `json:"repo" sokel:"repo"`
	Number       int    `json:"number" sokel:"number"`
	WithComments bool   `json:"with_comments" sokel:"with_comments"`
}

type IssueGetOut struct {
	Issue    schema.Issue     `json:"issue" sokel:"issue"`
	Comments []schema.Comment `json:"comments" sokel:"comments"`
}

type IssueLabelIn struct {
	Repo   string   `json:"repo" sokel:"repo"`
	Number int      `json:"number" sokel:"number"`
	Mode   string   `json:"mode" sokel:"mode"`
	Labels []string `json:"labels" sokel:"labels"`
}

type IssueLabelOut struct {
	Labels []string `json:"labels" sokel:"labels"`
}

type IssueUpdateIn struct {
	Repo        string `json:"repo" sokel:"repo"`
	Number      int    `json:"number" sokel:"number"`
	Title       string `json:"title" sokel:"title"`
	Body        string `json:"body" sokel:"body"`
	State       string `json:"state" sokel:"state"`
	StateReason string `json:"state_reason" sokel:"state_reason"`
	Milestone   string `json:"milestone" sokel:"milestone"`
}

type IssueUpdateOut struct {
	Number int    `json:"number" sokel:"number"`
	State  string `json:"state" sokel:"state"`
	URL    string `json:"url" sokel:"url"`
}

type IssuesListIn struct {
	Repo       string   `json:"repo" sokel:"repo"`
	State      string   `json:"state" sokel:"state"`
	Labels     []string `json:"labels" sokel:"labels"`
	Assignee   string   `json:"assignee" sokel:"assignee"`
	Creator    string   `json:"creator" sokel:"creator"`
	Milestone  string   `json:"milestone" sokel:"milestone"`
	Since      string   `json:"since" sokel:"since"`
	Sort       string   `json:"sort" sokel:"sort"`
	Direction  string   `json:"direction" sokel:"direction"`
	IncludePrs bool     `json:"include_prs" sokel:"include_prs"`
	Page       int      `json:"page" sokel:"page"`
}

type IssuesListOut struct {
	Issues     []schema.Issue `json:"issues" sokel:"issues"`
	Count      int            `json:"count" sokel:"count"`
	HasMore    bool           `json:"has_more" sokel:"has_more"`
	DroppedPrs int            `json:"dropped_prs" sokel:"dropped_prs"`
}

type JobLogIn struct {
	Repo  string `json:"repo" sokel:"repo"`
	JobID int    `json:"job_id" sokel:"job_id"`
	Tail  int    `json:"tail" sokel:"tail"`
}

type JobLogOut struct {
	Log       string `json:"log" sokel:"log"`
	Lines     int    `json:"lines" sokel:"lines"`
	Truncated bool   `json:"truncated" sokel:"truncated"`
}

type LabelCreateIn struct {
	Repo        string `json:"repo" sokel:"repo"`
	Name        string `json:"name" sokel:"name"`
	Color       string `json:"color" sokel:"color"`
	Description string `json:"description" sokel:"description"`
}

type LabelCreateOut struct {
	Name    string `json:"name" sokel:"name"`
	Created bool   `json:"created" sokel:"created"`
}

type LabelsListIn struct {
	Repo string `json:"repo" sokel:"repo"`
	Page int    `json:"page" sokel:"page"`
}

type LabelsListOut struct {
	Labels  []schema.Label `json:"labels" sokel:"labels"`
	Count   int            `json:"count" sokel:"count"`
	HasMore bool           `json:"has_more" sokel:"has_more"`
}

type MilestonesListIn struct {
	Repo  string `json:"repo" sokel:"repo"`
	State string `json:"state" sokel:"state"`
}

type MilestonesListOut struct {
	Milestones []schema.Milestone `json:"milestones" sokel:"milestones"`
	Count      int                `json:"count" sokel:"count"`
}

type PrCreateIn struct {
	Repo                string `json:"repo" sokel:"repo"`
	Title               string `json:"title" sokel:"title"`
	Head                string `json:"head" sokel:"head"`
	Base                string `json:"base" sokel:"base"`
	Body                string `json:"body" sokel:"body"`
	Draft               bool   `json:"draft" sokel:"draft"`
	MaintainerCanModify bool   `json:"maintainer_can_modify" sokel:"maintainer_can_modify"`
}

type PrCreateOut struct {
	Number  int    `json:"number" sokel:"number"`
	URL     string `json:"url" sokel:"url"`
	HeadSHA string `json:"head_sha" sokel:"head_sha"`
}

type PrFilesIn struct {
	Repo      string `json:"repo" sokel:"repo"`
	Number    int    `json:"number" sokel:"number"`
	WithPatch bool   `json:"with_patch" sokel:"with_patch"`
	Page      int    `json:"page" sokel:"page"`
}

type PrFilesOut struct {
	Files     []schema.PRFile `json:"files" sokel:"files"`
	Count     int             `json:"count" sokel:"count"`
	HasMore   bool            `json:"has_more" sokel:"has_more"`
	Additions int             `json:"additions" sokel:"additions"`
	Deletions int             `json:"deletions" sokel:"deletions"`
}

type PrGetIn struct {
	Repo   string `json:"repo" sokel:"repo"`
	Number int    `json:"number" sokel:"number"`
}

type PrGetOut struct {
	Pr schema.PR `json:"pr" sokel:"pr"`
}

type PrListIn struct {
	Repo  string `json:"repo" sokel:"repo"`
	State string `json:"state" sokel:"state"`
	Base  string `json:"base" sokel:"base"`
	Head  string `json:"head" sokel:"head"`
	Sort  string `json:"sort" sokel:"sort"`
	Page  int    `json:"page" sokel:"page"`
}

type PrListOut struct {
	Prs     []schema.PR `json:"prs" sokel:"prs"`
	Count   int         `json:"count" sokel:"count"`
	HasMore bool        `json:"has_more" sokel:"has_more"`
}

type PrMergeIn struct {
	Repo      string `json:"repo" sokel:"repo"`
	Number    int    `json:"number" sokel:"number"`
	Method    string `json:"method" sokel:"method"`
	Title     string `json:"title" sokel:"title"`
	Message   string `json:"message" sokel:"message"`
	ExpectSHA string `json:"expect_sha" sokel:"expect_sha"`
}

type PrMergeOut struct {
	Merged  bool   `json:"merged" sokel:"merged"`
	SHA     string `json:"sha" sokel:"sha"`
	Message string `json:"message" sokel:"message"`
}

type PrRequestReviewersIn struct {
	Repo          string   `json:"repo" sokel:"repo"`
	Number        int      `json:"number" sokel:"number"`
	Reviewers     []string `json:"reviewers" sokel:"reviewers"`
	TeamReviewers []string `json:"team_reviewers" sokel:"team_reviewers"`
	Remove        bool     `json:"remove" sokel:"remove"`
}

type PrRequestReviewersOut struct {
	Reviewers []string `json:"reviewers" sokel:"reviewers"`
}

type PrReviewIn struct {
	Repo     string                 `json:"repo" sokel:"repo"`
	Number   int                    `json:"number" sokel:"number"`
	Event    string                 `json:"event" sokel:"event"`
	Body     string                 `json:"body" sokel:"body"`
	Comments []schema.ReviewComment `json:"comments" sokel:"comments"`
}

type PrReviewOut struct {
	ReviewID int    `json:"review_id" sokel:"review_id"`
	State    string `json:"state" sokel:"state"`
	URL      string `json:"url" sokel:"url"`
}

type PrUpdateIn struct {
	Repo           string `json:"repo" sokel:"repo"`
	Number         int    `json:"number" sokel:"number"`
	Title          string `json:"title" sokel:"title"`
	Body           string `json:"body" sokel:"body"`
	Base           string `json:"base" sokel:"base"`
	State          string `json:"state" sokel:"state"`
	ReadyForReview bool   `json:"ready_for_review" sokel:"ready_for_review"`
}

type PrUpdateOut struct {
	Number int    `json:"number" sokel:"number"`
	State  string `json:"state" sokel:"state"`
	Draft  bool   `json:"draft" sokel:"draft"`
	URL    string `json:"url" sokel:"url"`
}

type ProjectItemAddIn struct {
	Owner         string `json:"owner" sokel:"owner"`
	ProjectNumber int    `json:"project_number" sokel:"project_number"`
	Repo          string `json:"repo" sokel:"repo"`
	Number        int    `json:"number" sokel:"number"`
	IsOrg         bool   `json:"is_org" sokel:"is_org"`
}

type ProjectItemAddOut struct {
	ItemID  string `json:"item_id" sokel:"item_id"`
	Already bool   `json:"already" sokel:"already"`
}

type ProjectItemFieldSetIn struct {
	Owner         string `json:"owner" sokel:"owner"`
	ProjectNumber int    `json:"project_number" sokel:"project_number"`
	ItemID        string `json:"item_id" sokel:"item_id"`
	Field         string `json:"field" sokel:"field"`
	Value         string `json:"value" sokel:"value"`
	IsOrg         bool   `json:"is_org" sokel:"is_org"`
}

type ProjectItemFieldSetOut struct {
	Updated bool   `json:"updated" sokel:"updated"`
	Field   string `json:"field" sokel:"field"`
	Value   string `json:"value" sokel:"value"`
}

type ProjectItemsListIn struct {
	Owner  string `json:"owner" sokel:"owner"`
	Number int    `json:"number" sokel:"number"`
	IsOrg  bool   `json:"is_org" sokel:"is_org"`
	Limit  int    `json:"limit" sokel:"limit"`
}

type ProjectItemsListOut struct {
	Items   []schema.ProjectItem `json:"items" sokel:"items"`
	Count   int                  `json:"count" sokel:"count"`
	HasMore bool                 `json:"has_more" sokel:"has_more"`
}

type ProjectsListIn struct {
	Owner string `json:"owner" sokel:"owner"`
	IsOrg bool   `json:"is_org" sokel:"is_org"`
}

type ProjectsListOut struct {
	Projects []schema.Project `json:"projects" sokel:"projects"`
	Count    int              `json:"count" sokel:"count"`
}

type ReactionAddIn struct {
	Repo    string `json:"repo" sokel:"repo"`
	Target  string `json:"target" sokel:"target"`
	ID      int    `json:"id" sokel:"id"`
	Content string `json:"content" sokel:"content"`
}

type ReactionAddOut struct {
	ReactionID int  `json:"reaction_id" sokel:"reaction_id"`
	Already    bool `json:"already" sokel:"already"`
}

type ReleaseCreateIn struct {
	Repo          string `json:"repo" sokel:"repo"`
	Tag           string `json:"tag" sokel:"tag"`
	Target        string `json:"target" sokel:"target"`
	Name          string `json:"name" sokel:"name"`
	Body          string `json:"body" sokel:"body"`
	GenerateNotes bool   `json:"generate_notes" sokel:"generate_notes"`
	Draft         bool   `json:"draft" sokel:"draft"`
	Prerelease    bool   `json:"prerelease" sokel:"prerelease"`
}

type ReleaseCreateOut struct {
	ReleaseID int    `json:"release_id" sokel:"release_id"`
	Tag       string `json:"tag" sokel:"tag"`
	URL       string `json:"url" sokel:"url"`
	Body      string `json:"body" sokel:"body"`
}

type ReleasesListIn struct {
	Repo string `json:"repo" sokel:"repo"`
	Page int    `json:"page" sokel:"page"`
}

type ReleasesListOut struct {
	Releases []schema.Release `json:"releases" sokel:"releases"`
	Count    int              `json:"count" sokel:"count"`
	HasMore  bool             `json:"has_more" sokel:"has_more"`
}

type RepoGetIn struct {
	Repo string `json:"repo" sokel:"repo"`
}

type RepoGetOut struct {
	Repo   schema.Repo `json:"repo" sokel:"repo"`
	Topics []string    `json:"topics" sokel:"topics"`
}

type ReposListIn struct {
	Owner string `json:"owner" sokel:"owner"`
	Type  string `json:"type" sokel:"type"`
	Sort  string `json:"sort" sokel:"sort"`
	Page  int    `json:"page" sokel:"page"`
}

type ReposListOut struct {
	Repos   []schema.Repo `json:"repos" sokel:"repos"`
	Count   int           `json:"count" sokel:"count"`
	HasMore bool          `json:"has_more" sokel:"has_more"`
}

type RunJobsIn struct {
	Repo  string `json:"repo" sokel:"repo"`
	RunID int    `json:"run_id" sokel:"run_id"`
}

type RunJobsOut struct {
	Jobs        []schema.Job `json:"jobs" sokel:"jobs"`
	Count       int          `json:"count" sokel:"count"`
	FailedSteps []string     `json:"failed_steps" sokel:"failed_steps"`
}

type SearchIn struct {
	Type  string `json:"type" sokel:"type"`
	Query string `json:"query" sokel:"query"`
	Limit int    `json:"limit" sokel:"limit"`
}

type SearchOut struct {
	Results    []schema.SearchHit `json:"results" sokel:"results"`
	Count      int                `json:"count" sokel:"count"`
	Total      int                `json:"total" sokel:"total"`
	Incomplete bool               `json:"incomplete" sokel:"incomplete"`
}

type WorkflowDispatchIn struct {
	Repo     string            `json:"repo" sokel:"repo"`
	Workflow string            `json:"workflow" sokel:"workflow"`
	Ref      string            `json:"ref" sokel:"ref"`
	Inputs   map[string]string `json:"inputs" sokel:"inputs"`
}

type WorkflowDispatchOut struct {
	Dispatched bool   `json:"dispatched" sokel:"dispatched"`
	Note       string `json:"note" sokel:"note"`
}

type WorkflowRunsListIn struct {
	Repo     string `json:"repo" sokel:"repo"`
	Workflow string `json:"workflow" sokel:"workflow"`
	Branch   string `json:"branch" sokel:"branch"`
	Status   string `json:"status" sokel:"status"`
	Actor    string `json:"actor" sokel:"actor"`
	Page     int    `json:"page" sokel:"page"`
}

type WorkflowRunsListOut struct {
	Runs    []schema.WorkflowRun `json:"runs" sokel:"runs"`
	Count   int                  `json:"count" sokel:"count"`
	HasMore bool                 `json:"has_more" sokel:"has_more"`
}
