// Code generated by sokel-gen. DO NOT EDIT.
//
// The authentication method is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// authMeta is this plugin's authentication declaration, exactly as declared.
func authMeta() contract.AuthMeta {
	return contract.AuthMeta{
		Kind:     contract.AuthOAuth,
		Provider: "x",
		Scopes:   []string{"tweet.read", "tweet.write", "users.read", "like.read", "like.write", "bookmark.read", "bookmark.write", "follows.read", "follows.write", "list.read", "list.write", "dm.read", "dm.write", "media.write", "offline.access"},
	}
}

// RegisterAuth declares how the credential is obtained and takes the implementation.
// The parameter list follows the declared steps: missing one is a compile error, not a panel
// that silently stalls at runtime.
func RegisterAuth(h plugin.AuthHost) {
	h.SetAuthFlow(authMeta(), plugin.AuthHandlers{})
}
