// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	AccessToken   string `sokel:"access_token,optional" label:"访问令牌（授权注入）" secret:"true"`
	RefreshToken  string `sokel:"refresh_token,optional" label:"刷新令牌（授权注入）" secret:"true"`
	Proxy         string `sokel:"proxy,optional" label:"出站代理"`
	WatchMentions string `sokel:"watch_mentions,optional" label:"监听提及" default:"off"`
	WatchQuery    string `sokel:"watch_query,optional" label:"监听的查询式"`
	PollSeconds   string `sokel:"poll_seconds,optional" label:"轮询间隔（秒）" default:"300"`
	WatchCursor   string `sokel:"watch_cursor,optional" label:"轮询游标"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:  "access_token",
			Label: "访问令牌（授权注入）",
			Type:  contract.ParamType("secret"),
			Desc:  "点「授权」后由平台写入，勿手填",
		},
		{
			Name:  "refresh_token",
			Label: "刷新令牌（授权注入）",
			Type:  contract.ParamType("secret"),
			Desc:  "勿手填",
		},
		{
			Name:  "proxy",
			Label: "出站代理",
			Type:  contract.ParamType("text"),
			Desc:  "如 http://127.0.0.1:7897；部署环境直连不了 x.com 时必填",
		},
		{
			Name:    "watch_mentions",
			Label:   "监听提及",
			Type:    contract.ParamType("select"),
			Default: "off",
			Desc:    "填 on 则有人 @ 授权账号时触发工作流；off = 不监听",
			Options: []contract.Option{{Value: "off", Label: "off"}, {Value: "on", Label: "on"}},
		},
		{
			Name:  "watch_query",
			Label: "监听的查询式",
			Type:  contract.ParamType("text"),
			Desc:  "X 搜索语法（如 `\"我的品牌\" -is:retweet lang:zh`）；留空 = 不监听关键词。**每轮都是一次计费的搜索**，间隔别调太短",
		},
		{
			Name:    "poll_seconds",
			Label:   "轮询间隔（秒）",
			Type:    contract.ParamType("text"),
			Default: "300",
			Desc:    "默认 300。X 的搜索/提及限流是 15 分钟 300 次，但真正的约束是钱——每轮拉回的每条推文都计费",
		},
		{
			Name:  "watch_cursor",
			Label: "轮询游标",
			Type:  contract.ParamType("text"),
			Desc:  "事件源自动维护，勿手填",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
