// Code generated by sokel-gen. DO NOT EDIT.
//
// Event payload types and trigger functions are generated from the schema declaration.
// Change an event there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/x/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// KeywordMatchedEvent is the payload of the "关键词命中" event.
type KeywordMatchedEvent struct {
	PostID         string `json:"post_id" sokel:"post_id"`
	Text           string `json:"text" sokel:"text"`
	AuthorID       string `json:"author_id" sokel:"author_id"`
	AuthorUsername string `json:"author_username" sokel:"author_username"`
	AuthorName     string `json:"author_name" sokel:"author_name"`
	ConversationID string `json:"conversation_id" sokel:"conversation_id"`
	URL            string `json:"url" sokel:"url"`
	CreatedAt      string `json:"created_at" sokel:"created_at"`
	Kind           string `json:"kind" sokel:"kind"`
	MatchedQuery   string `json:"matched_query" sokel:"matched_query"`
}

// MentionReceivedEvent is the payload of the "被提及" event.
type MentionReceivedEvent struct {
	PostID         string `json:"post_id" sokel:"post_id"`
	Text           string `json:"text" sokel:"text"`
	AuthorID       string `json:"author_id" sokel:"author_id"`
	AuthorUsername string `json:"author_username" sokel:"author_username"`
	AuthorName     string `json:"author_name" sokel:"author_name"`
	ConversationID string `json:"conversation_id" sokel:"conversation_id"`
	URL            string `json:"url" sokel:"url"`
	CreatedAt      string `json:"created_at" sokel:"created_at"`
	Kind           string `json:"kind" sokel:"kind"`
	MatchedQuery   string `json:"matched_query" sokel:"matched_query"`
}

// DeclareEvents hands this plugin's event contracts to the host.
//
// Common-field consistency was checked at **generation time** (each one must exist in every
// event with the same type), so this cannot fail here — a real problem showed up at
// go generate.
func DeclareEvents(h plugin.EventHost) {
	events := []contract.Event{
		contract.EventOf(&schema.KeywordMatched{}),
		contract.EventOf(&schema.MentionReceived{}),
	}
	for _, e := range events {
		h.DeclareEvent(e)
	}
	names := []string{"post_id", "text"}
	fields, _ := contract.ValidateCommonFields(events, names)
	h.DeclareEventsCommon(fields, names)
}

// TriggerKeywordMatched pushes one "关键词命中" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerKeywordMatched(ctx plugin.SourceCtx, eventID string, p *KeywordMatchedEvent) error {
	return ctx.Trigger("keyword_matched", eventID, p)
}

// TriggerMentionReceived pushes one "被提及" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerMentionReceived(ctx plugin.SourceCtx, eventID string, p *MentionReceivedEvent) error {
	return ctx.Trigger("mention_received", eventID, p)
}
