// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/x/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXBookmark registers the implementation of "x_bookmark".
func OnXBookmark(h plugin.Host, fn func(plugin.Ctx, *XBookmarkIn) (*XBookmarkOut, error)) {
	h.Register(contract.OperationOf(&schema.Bookmark{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XBookmarkIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXDmEvents registers the implementation of "x_dm_events".
func OnXDmEvents(h plugin.Host, fn func(plugin.Ctx, *XDmEventsIn) (*XDmEventsOut, error)) {
	h.Register(contract.OperationOf(&schema.DMEvents{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XDmEventsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXDmSend registers the implementation of "x_dm_send".
func OnXDmSend(h plugin.Host, fn func(plugin.Ctx, *XDmSendIn) (*XDmSendOut, error)) {
	h.Register(contract.OperationOf(&schema.DMSend{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XDmSendIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXFollow registers the implementation of "x_follow".
func OnXFollow(h plugin.Host, fn func(plugin.Ctx, *XFollowIn) (*XFollowOut, error)) {
	h.Register(contract.OperationOf(&schema.Follow{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XFollowIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXLike registers the implementation of "x_like".
func OnXLike(h plugin.Host, fn func(plugin.Ctx, *XLikeIn) (*XLikeOut, error)) {
	h.Register(contract.OperationOf(&schema.Like{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XLikeIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXListMemberAdd registers the implementation of "x_list_member_add".
func OnXListMemberAdd(h plugin.Host, fn func(plugin.Ctx, *XListMemberAddIn) (*XListMemberAddOut, error)) {
	h.Register(contract.OperationOf(&schema.ListMemberAdd{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XListMemberAddIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXListMemberRemove registers the implementation of "x_list_member_remove".
func OnXListMemberRemove(h plugin.Host, fn func(plugin.Ctx, *XListMemberRemoveIn) (*XListMemberRemoveOut, error)) {
	h.Register(contract.OperationOf(&schema.ListMemberRemove{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XListMemberRemoveIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXListPosts registers the implementation of "x_list_posts".
func OnXListPosts(h plugin.Host, fn func(plugin.Ctx, *XListPostsIn) (*XListPostsOut, error)) {
	h.Register(contract.OperationOf(&schema.ListPosts{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XListPostsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXMediaUpload registers the implementation of "x_media_upload".
func OnXMediaUpload(h plugin.Host, fn func(plugin.Ctx, *XMediaUploadIn) (*XMediaUploadOut, error)) {
	h.Register(contract.OperationOf(&schema.MediaUpload{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XMediaUploadIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXMentions registers the implementation of "x_mentions".
func OnXMentions(h plugin.Host, fn func(plugin.Ctx, *XMentionsIn) (*XMentionsOut, error)) {
	h.Register(contract.OperationOf(&schema.Mentions{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XMentionsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXPostCreate registers the implementation of "x_post_create".
func OnXPostCreate(h plugin.Host, fn func(plugin.Ctx, *XPostCreateIn) (*XPostCreateOut, error)) {
	h.Register(contract.OperationOf(&schema.PostCreate{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XPostCreateIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXPostDelete registers the implementation of "x_post_delete".
func OnXPostDelete(h plugin.Host, fn func(plugin.Ctx, *XPostDeleteIn) (*XPostDeleteOut, error)) {
	h.Register(contract.OperationOf(&schema.PostDelete{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XPostDeleteIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXPostGet registers the implementation of "x_post_get".
func OnXPostGet(h plugin.Host, fn func(plugin.Ctx, *XPostGetIn) (*XPostGetOut, error)) {
	h.Register(contract.OperationOf(&schema.PostGet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XPostGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXPostThread registers the implementation of "x_post_thread".
func OnXPostThread(h plugin.Host, fn func(plugin.Ctx, *XPostThreadIn) (*XPostThreadOut, error)) {
	h.Register(contract.OperationOf(&schema.PostThread{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XPostThreadIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXRepost registers the implementation of "x_repost".
func OnXRepost(h plugin.Host, fn func(plugin.Ctx, *XRepostIn) (*XRepostOut, error)) {
	h.Register(contract.OperationOf(&schema.Repost{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XRepostIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXSearch registers the implementation of "x_search".
func OnXSearch(h plugin.Host, fn func(plugin.Ctx, *XSearchIn) (*XSearchOut, error)) {
	h.Register(contract.OperationOf(&schema.Search{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XSearchIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXUnbookmark registers the implementation of "x_unbookmark".
func OnXUnbookmark(h plugin.Host, fn func(plugin.Ctx, *XUnbookmarkIn) (*XUnbookmarkOut, error)) {
	h.Register(contract.OperationOf(&schema.Unbookmark{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XUnbookmarkIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXUnfollow registers the implementation of "x_unfollow".
func OnXUnfollow(h plugin.Host, fn func(plugin.Ctx, *XUnfollowIn) (*XUnfollowOut, error)) {
	h.Register(contract.OperationOf(&schema.Unfollow{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XUnfollowIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXUnlike registers the implementation of "x_unlike".
func OnXUnlike(h plugin.Host, fn func(plugin.Ctx, *XUnlikeIn) (*XUnlikeOut, error)) {
	h.Register(contract.OperationOf(&schema.Unlike{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XUnlikeIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXUnrepost registers the implementation of "x_unrepost".
func OnXUnrepost(h plugin.Host, fn func(plugin.Ctx, *XUnrepostIn) (*XUnrepostOut, error)) {
	h.Register(contract.OperationOf(&schema.Unrepost{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XUnrepostIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXUserGet registers the implementation of "x_user_get".
func OnXUserGet(h plugin.Host, fn func(plugin.Ctx, *XUserGetIn) (*XUserGetOut, error)) {
	h.Register(contract.OperationOf(&schema.UserGet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XUserGetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnXUserTimeline registers the implementation of "x_user_timeline".
func OnXUserTimeline(h plugin.Host, fn func(plugin.Ctx, *XUserTimelineIn) (*XUserTimelineOut, error)) {
	h.Register(contract.OperationOf(&schema.UserTimeline{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in XUserTimelineIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
