// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/x/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK       bool   `json:"ok" sokel:"ok"`
	Message  string `json:"message" sokel:"message"`
	Username string `json:"username" sokel:"username"`
}

type XBookmarkIn struct {
	PostID string `json:"post_id" sokel:"post_id"`
}

type XBookmarkOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type XDmEventsIn struct {
	ConversationID string `json:"conversation_id" sokel:"conversation_id"`
	Cursor         string `json:"cursor" sokel:"cursor"`
	MaxItems       int    `json:"max_items" sokel:"max_items"`
}

type XDmEventsOut struct {
	Items      []schema.DMEvent `json:"items" sokel:"items"`
	NextCursor string           `json:"next_cursor" sokel:"next_cursor"`
	HasMore    bool             `json:"has_more" sokel:"has_more"`
	Count      int              `json:"count" sokel:"count"`
}

type XDmSendIn struct {
	Text           string   `json:"text" sokel:"text"`
	UserID         string   `json:"user_id" sokel:"user_id"`
	ConversationID string   `json:"conversation_id" sokel:"conversation_id"`
	MediaIDs       []string `json:"media_ids" sokel:"media_ids"`
}

type XDmSendOut struct {
	ConversationID string `json:"conversation_id" sokel:"conversation_id"`
	EventID        string `json:"event_id" sokel:"event_id"`
}

type XFollowIn struct {
	UserID   string `json:"user_id" sokel:"user_id"`
	Username string `json:"username" sokel:"username"`
}

type XFollowOut struct {
	OK      bool `json:"ok" sokel:"ok"`
	Pending bool `json:"pending" sokel:"pending"`
}

type XLikeIn struct {
	PostID string `json:"post_id" sokel:"post_id"`
}

type XLikeOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type XListMemberAddIn struct {
	ListID   string `json:"list_id" sokel:"list_id"`
	UserID   string `json:"user_id" sokel:"user_id"`
	Username string `json:"username" sokel:"username"`
}

type XListMemberAddOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type XListMemberRemoveIn struct {
	ListID   string `json:"list_id" sokel:"list_id"`
	UserID   string `json:"user_id" sokel:"user_id"`
	Username string `json:"username" sokel:"username"`
}

type XListMemberRemoveOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type XListPostsIn struct {
	ListID   string `json:"list_id" sokel:"list_id"`
	Cursor   string `json:"cursor" sokel:"cursor"`
	MaxItems int    `json:"max_items" sokel:"max_items"`
}

type XListPostsOut struct {
	Items      []schema.Post `json:"items" sokel:"items"`
	NextCursor string        `json:"next_cursor" sokel:"next_cursor"`
	HasMore    bool          `json:"has_more" sokel:"has_more"`
	Count      int           `json:"count" sokel:"count"`
}

type XMediaUploadIn struct {
	File    *plugin.File `json:"file" sokel:"file"`
	AltText string       `json:"alt_text" sokel:"alt_text"`
	Purpose string       `json:"purpose" sokel:"purpose"`
}

type XMediaUploadOut struct {
	MediaID  string `json:"media_id" sokel:"media_id"`
	MediaKey string `json:"media_key" sokel:"media_key"`
	Size     int    `json:"size" sokel:"size"`
	State    string `json:"state" sokel:"state"`
}

type XMentionsIn struct {
	Cursor   string `json:"cursor" sokel:"cursor"`
	MaxItems int    `json:"max_items" sokel:"max_items"`
}

type XMentionsOut struct {
	Items      []schema.Post `json:"items" sokel:"items"`
	NextCursor string        `json:"next_cursor" sokel:"next_cursor"`
	HasMore    bool          `json:"has_more" sokel:"has_more"`
	Count      int           `json:"count" sokel:"count"`
}

type XPostCreateIn struct {
	Text                string   `json:"text" sokel:"text"`
	ReplyToID           string   `json:"reply_to_id" sokel:"reply_to_id"`
	QuoteID             string   `json:"quote_id" sokel:"quote_id"`
	MediaIDs            []string `json:"media_ids" sokel:"media_ids"`
	PollOptions         []string `json:"poll_options" sokel:"poll_options"`
	PollDurationMinutes int      `json:"poll_duration_minutes" sokel:"poll_duration_minutes"`
	ReplySettings       string   `json:"reply_settings" sokel:"reply_settings"`
}

type XPostCreateOut struct {
	ID   string `json:"id" sokel:"id"`
	URL  string `json:"url" sokel:"url"`
	Text string `json:"text" sokel:"text"`
}

type XPostDeleteIn struct {
	PostID string `json:"post_id" sokel:"post_id"`
}

type XPostDeleteOut struct {
	Deleted bool `json:"deleted" sokel:"deleted"`
}

type XPostGetIn struct {
	PostIDs []string `json:"post_ids" sokel:"post_ids"`
}

type XPostGetOut struct {
	Items []schema.Post `json:"items" sokel:"items"`
	Count int           `json:"count" sokel:"count"`
}

type XPostThreadIn struct {
	Texts      []string `json:"texts" sokel:"texts"`
	ReplyToID  string   `json:"reply_to_id" sokel:"reply_to_id"`
	MediaIDs   []string `json:"media_ids" sokel:"media_ids"`
	IntervalMs int      `json:"interval_ms" sokel:"interval_ms"`
}

type XPostThreadOut struct {
	IDs     []string `json:"ids" sokel:"ids"`
	RootID  string   `json:"root_id" sokel:"root_id"`
	RootURL string   `json:"root_url" sokel:"root_url"`
	Count   int      `json:"count" sokel:"count"`
}

type XRepostIn struct {
	PostID string `json:"post_id" sokel:"post_id"`
}

type XRepostOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type XSearchIn struct {
	Query    string `json:"query" sokel:"query"`
	Sort     string `json:"sort" sokel:"sort"`
	Cursor   string `json:"cursor" sokel:"cursor"`
	MaxItems int    `json:"max_items" sokel:"max_items"`
}

type XSearchOut struct {
	Items      []schema.Post `json:"items" sokel:"items"`
	NextCursor string        `json:"next_cursor" sokel:"next_cursor"`
	HasMore    bool          `json:"has_more" sokel:"has_more"`
	Count      int           `json:"count" sokel:"count"`
}

type XUnbookmarkIn struct {
	PostID string `json:"post_id" sokel:"post_id"`
}

type XUnbookmarkOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type XUnfollowIn struct {
	UserID   string `json:"user_id" sokel:"user_id"`
	Username string `json:"username" sokel:"username"`
}

type XUnfollowOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type XUnlikeIn struct {
	PostID string `json:"post_id" sokel:"post_id"`
}

type XUnlikeOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type XUnrepostIn struct {
	PostID string `json:"post_id" sokel:"post_id"`
}

type XUnrepostOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type XUserGetIn struct {
	Username string `json:"username" sokel:"username"`
	UserID   string `json:"user_id" sokel:"user_id"`
}

type XUserGetOut struct {
	User  schema.User `json:"user" sokel:"user"`
	Found bool        `json:"found" sokel:"found"`
}

type XUserTimelineIn struct {
	UserID         string `json:"user_id" sokel:"user_id"`
	Username       string `json:"username" sokel:"username"`
	ExcludeReposts bool   `json:"exclude_reposts" sokel:"exclude_reposts"`
	ExcludeReplies bool   `json:"exclude_replies" sokel:"exclude_replies"`
	Cursor         string `json:"cursor" sokel:"cursor"`
	MaxItems       int    `json:"max_items" sokel:"max_items"`
}

type XUserTimelineOut struct {
	Items      []schema.Post `json:"items" sokel:"items"`
	NextCursor string        `json:"next_cursor" sokel:"next_cursor"`
	HasMore    bool          `json:"has_more" sokel:"has_more"`
	Count      int           `json:"count" sokel:"count"`
}
