// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	PgURL     string `sokel:"pg_url" label:"Postgres 连接串"`
	Namespace string `sokel:"namespace,optional" label:"表名前缀" default:"kb"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "pg_url",
			Label:    "Postgres 连接串",
			Type:     contract.ParamType("text"),
			Required: true,
			Desc:     "postgres://user:pass@host:5432/db?sslmode=disable；需已装 vector 与 pg_trgm 扩展",
		},
		{
			Name:    "namespace",
			Label:   "表名前缀",
			Type:    contract.ParamType("text"),
			Default: "kb",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
