// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/kbstore-pgvector/schema"
)

type ChunksBrowseIn struct {
	KbID      string           `json:"kb_id" sokel:"kb_id"`
	K         int              `json:"k" sokel:"k"`
	Offset    int              `json:"offset" sokel:"offset"`
	Filters   []schema.Filter  `json:"filters" sokel:"filters"`
	TimeRange schema.TimeRange `json:"time_range" sokel:"time_range"`
}

type ChunksBrowseOut struct {
	Chunks []schema.Chunk `json:"chunks" sokel:"chunks"`
}

type ChunksUpsertIn struct {
	KbID   string         `json:"kb_id" sokel:"kb_id"`
	DocID  string         `json:"doc_id" sokel:"doc_id"`
	Chunks []schema.Chunk `json:"chunks" sokel:"chunks"`
	Append bool           `json:"append" sokel:"append"`
}

type ChunksUpsertOut struct {
	OK    bool `json:"ok" sokel:"ok"`
	Count int  `json:"count" sokel:"count"`
}

type DocDeleteIn struct {
	KbID  string `json:"kb_id" sokel:"kb_id"`
	DocID string `json:"doc_id" sokel:"doc_id"`
}

type DocDeleteOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK         bool   `json:"ok" sokel:"ok"`
	Version    string `json:"version" sokel:"version"`
	Extensions string `json:"extensions" sokel:"extensions"`
	Message    string `json:"message" sokel:"message"`
}

type KbCreateIn struct {
	KbID   string             `json:"kb_id" sokel:"kb_id"`
	Dims   int                `json:"dims" sokel:"dims"`
	Fields []schema.MetaField `json:"fields" sokel:"fields"`
}

type KbCreateOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type KbDropIn struct {
	KbID   string             `json:"kb_id" sokel:"kb_id"`
	Dims   int                `json:"dims" sokel:"dims"`
	Fields []schema.MetaField `json:"fields" sokel:"fields"`
}

type KbDropOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type KeywordQueryIn struct {
	KbID        string             `json:"kb_id" sokel:"kb_id"`
	Query       string             `json:"query" sokel:"query"`
	K           int                `json:"k" sokel:"k"`
	Filters     []schema.Filter    `json:"filters" sokel:"filters"`
	TimeRange   schema.TimeRange   `json:"time_range" sokel:"time_range"`
	FieldBoosts map[string]float64 `json:"field_boosts" sokel:"field_boosts"`
	Recency     schema.Recency     `json:"recency" sokel:"recency"`
}

type KeywordQueryOut struct {
	Hits []schema.Hit `json:"hits" sokel:"hits"`
}

type MgetIn struct {
	KbID string   `json:"kb_id" sokel:"kb_id"`
	IDs  []string `json:"ids" sokel:"ids"`
}

type MgetOut struct {
	Chunks []schema.Chunk `json:"chunks" sokel:"chunks"`
}

type VectorQueryIn struct {
	KbID      string           `json:"kb_id" sokel:"kb_id"`
	Embedding []float64        `json:"embedding" sokel:"embedding"`
	K         int              `json:"k" sokel:"k"`
	Filters   []schema.Filter  `json:"filters" sokel:"filters"`
	TimeRange schema.TimeRange `json:"time_range" sokel:"time_range"`
}

type VectorQueryOut struct {
	Hits []schema.Hit `json:"hits" sokel:"hits"`
}
