// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	AccessToken  string `sokel:"access_token,optional" label:"访问令牌（平台注入）" secret:"true"`
	RefreshToken string `sokel:"refresh_token,optional" label:"刷新令牌（授权获取）" secret:"true"`
	HistoryID    string `sokel:"history_id,optional" label:"轮询游标"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:  "access_token",
			Label: "访问令牌（平台注入）",
			Type:  contract.ParamType("secret"),
			Desc:  "授权后由平台自动换取，勿手填",
		},
		{
			Name:  "refresh_token",
			Label: "刷新令牌（授权获取）",
			Type:  contract.ParamType("secret"),
			Desc:  "点凭证行的「授权」获取，勿手填",
		},
		{
			Name:  "history_id",
			Label: "轮询游标",
			Type:  contract.ParamType("text"),
			Desc:  "新邮件事件源自动维护，勿手填",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
