// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/gmail/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

type GmailAttachmentIn struct {
	MessageID    string `json:"message_id" sokel:"message_id"`
	AttachmentID string `json:"attachment_id" sokel:"attachment_id"`
	Filename     string `json:"filename" sokel:"filename"`
}

type GmailAttachmentOut struct {
	File *plugin.File `json:"file" sokel:"file"`
}

type GmailGetIn struct {
	MessageID string `json:"message_id" sokel:"message_id"`
}

type GmailGetOut struct {
	ID          string                 `json:"id" sokel:"id"`
	ThreadID    string                 `json:"thread_id" sokel:"thread_id"`
	Subject     string                 `json:"subject" sokel:"subject"`
	From        string                 `json:"from" sokel:"from"`
	To          string                 `json:"to" sokel:"to"`
	Date        string                 `json:"date" sokel:"date"`
	Text        string                 `json:"text" sokel:"text"`
	HTML        string                 `json:"html" sokel:"html"`
	Snippet     string                 `json:"snippet" sokel:"snippet"`
	Attachments []schema.AttachmentRef `json:"attachments" sokel:"attachments"`
	LabelIDs    []string               `json:"label_ids" sokel:"label_ids"`
}

type GmailListIn struct {
	Query      string `json:"query" sokel:"query"`
	LabelIDs   string `json:"label_ids" sokel:"label_ids"`
	MaxResults int    `json:"max_results" sokel:"max_results"`
	WithDetail bool   `json:"with_detail" sokel:"with_detail"`
}

type GmailListOut struct {
	Messages      []schema.MessageItem `json:"messages" sokel:"messages"`
	Count         int                  `json:"count" sokel:"count"`
	NextPageToken string               `json:"next_page_token" sokel:"next_page_token"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK            bool   `json:"ok" sokel:"ok"`
	Email         string `json:"email" sokel:"email"`
	MessagesTotal int    `json:"messages_total" sokel:"messages_total"`
	Message       string `json:"message" sokel:"message"`
}
