package main

// Event sources: Redis has two consumption paths, and whichever the credential fills in is the one that
// starts (neither filled in means no event source, while normal operations keep working as usual).
//
//   - **Pub/Sub** (watch_channels): real-time, not retained, no message id. Messages sent while the
//     plugin was disconnected **are simply not received** — it's a signal, not a queue.
//   - **Stream** (watch_streams): retained, can be replayed, message ids are unique and increasing,
//     naturally suited to being a queue. Reading starts from "$" (the moment it connects), with no
//     history replay — the same convention as feed/gitlab not flooding history on the first run.
//
// Both paths run in their own goroutine, and both wind down together when ctx is canceled.

import (
	"fmt"
	"log"
	"strings"
	"sync/atomic"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
	"github.com/sokel-dev/sokel-plugin-sdk/sokel"
)

// pubsub messages have no id, so the event id can only be generated by numbering them within this
// process.
//
// **Can't use a content hash**: sending the same message twice in a row on one channel is legitimate
// (e.g. "tick", "reload"), and deduplicating by content would swallow the second one. The cost is that
// numbering resets on process restart — but Pub/Sub never redelivers anyway, there's no such thing as
// "replay after restart", so the cost is zero.
var psSeq atomic.Int64

func runEvents(ctx plugin.SourceCtx) error {
	cred := sokel.SourceCredentialAs[Cred](ctx)
	channels := splitList(cred.WatchChannels)
	streams := splitList(cred.WatchStreams)
	if len(channels) == 0 && len(streams) == 0 {
		return fmt.Errorf("凭证没填「事件盯哪些频道」或「事件盯哪些 Stream」，事件源不启动（普通操作不受影响）")
	}
	cli, err := clientOf(cred)
	if err != nil {
		return err
	}
	if err := cli.Ping(ctx).Err(); err != nil {
		return fmt.Errorf("连不上 Redis: %w", err)
	}

	var what []string
	if len(channels) > 0 {
		what = append(what, fmt.Sprintf("%d 个频道", len(channels)))
		go consumeChannels(ctx, cli, channels)
	}
	if len(streams) > 0 {
		what = append(what, fmt.Sprintf("%d 个 Stream", len(streams)))
		go consumeStreams(ctx, cli, streams)
	}
	ctx.ReportStatus("ok", "监听 "+strings.Join(what, " + "))

	<-ctx.Done()
	return nil
}

// consumeChannels does the Pub/Sub subscription. Channels with wildcards go through PSUBSCRIBE, the rest
// through SUBSCRIBE — kept separate so the pattern output field only has a value when it was actually
// subscribed by wildcard (otherwise every message would carry a "pattern" equal to the channel name,
// looking like a wildcard match when it isn't one).
func consumeChannels(ctx plugin.SourceCtx, cli *redis.Client, channels []string) {
	var exact, patterns []string
	for _, c := range channels {
		if strings.ContainsAny(c, "*?[") {
			patterns = append(patterns, c)
		} else {
			exact = append(exact, c)
		}
	}
	if len(exact) > 0 {
		sub := cli.Subscribe(ctx, exact...)
		defer sub.Close()
		go pumpMessages(ctx, sub.Channel())
	}
	if len(patterns) > 0 {
		psub := cli.PSubscribe(ctx, patterns...)
		defer psub.Close()
		go pumpMessages(ctx, psub.Channel())
	}
	<-ctx.Done()
}

func pumpMessages(ctx plugin.SourceCtx, ch <-chan *redis.Message) {
	for {
		select {
		case <-ctx.Done():
			return
		case msg, ok := <-ch:
			if !ok {
				return
			}
			id := fmt.Sprintf("ps:%d:%d", time.Now().UnixNano(), psSeq.Add(1))
			if err := TriggerMessageReceived(ctx, id, &MessageReceivedEvent{
				Key: msg.Channel, Payload: msg.Payload, Pattern: msg.Pattern,
			}); err != nil {
				log.Printf("[redis] 推送频道消息失败(%s): %v", msg.Channel, err)
			}
		}
	}
}

// consumeStreams does a blocking XREAD. BLOCK is set to 5 seconds rather than 0 (forever): when ctx is
// canceled, it waits at most one more round and the process exits cleanly; a permanently blocked
// connection would only wake up when the connection itself is closed.
func consumeStreams(ctx plugin.SourceCtx, cli *redis.Client, streams []string) {
	last := make(map[string]string, len(streams))
	for _, s := range streams {
		last[s] = "$" // only read new messages from the moment it connects, no history replay
	}
	for {
		select {
		case <-ctx.Done():
			return
		default:
		}
		args := make([]string, 0, len(streams)*2)
		args = append(args, streams...)
		for _, s := range streams {
			args = append(args, last[s])
		}
		res, err := cli.XRead(ctx, &redis.XReadArgs{Streams: args, Block: 5 * time.Second, Count: 100}).Result()
		if err == redis.Nil {
			continue // no new messages this round
		}
		if err != nil {
			if ctx.Err() != nil {
				return
			}
			ctx.ReportStatus("error", fmt.Sprintf("读 Stream 失败：%v（5 秒后重试）", err))
			select {
			case <-ctx.Done():
				return
			case <-time.After(5 * time.Second):
			}
			continue
		}
		for _, st := range res {
			for _, m := range st.Messages {
				last[st.Stream] = m.ID
				fields := make(map[string]any, len(m.Values))
				for k, v := range m.Values {
					fields[k] = asString(v)
				}
				// The event id is Stream name + message id: XADD's id is unique and increasing, so
				// even if it's re-read after a restart, the platform will dedupe it by the same id.
				if err := TriggerStreamMessage(ctx, st.Stream+":"+m.ID, &StreamMessageEvent{
					Key: st.Stream, ID: m.ID, Fields: fields,
				}); err != nil {
					log.Printf("[redis] 推送 Stream 消息失败(%s %s): %v", st.Stream, m.ID, err)
				}
			}
		}
	}
}
