// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	Addr          string `sokel:"addr" label:"地址"`
	Username      string `sokel:"username,optional" label:"用户名"`
	Password      string `sokel:"password,optional" label:"密码" secret:"true"`
	DB            string `sokel:"db,optional" label:"库号"`
	TLS           string `sokel:"tls,optional" label:"TLS"`
	WatchChannels string `sokel:"watch_channels,optional" label:"事件盯哪些频道"`
	WatchStreams  string `sokel:"watch_streams,optional" label:"事件盯哪些 Stream"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "addr",
			Label:    "地址",
			Type:     contract.ParamType("text"),
			Required: true,
			Desc:     "host:port，如 redis.internal:6379。**插件进程要能连到它**——云托管实例记得放行来源 IP",
		},
		{
			Name:  "username",
			Label: "用户名",
			Type:  contract.ParamType("text"),
			Desc:  "Redis 6+ 的 ACL 用户；用传统 requirepass 密码就留空",
		},
		{
			Name:  "password",
			Label: "密码",
			Type:  contract.ParamType("secret"),
			Desc:  "没设密码就留空",
		},
		{
			Name:  "db",
			Label: "库号",
			Type:  contract.ParamType("text"),
			Desc:  "默认 0。集群模式只有 0 号库",
		},
		{
			Name:    "tls",
			Label:   "TLS",
			Type:    contract.ParamType("select"),
			Desc:    "off 明文（默认，内网常见）/ on 走 TLS / on_insecure 走 TLS 但不校验证书（自签证书用）",
			Options: []contract.Option{{Value: "off", Label: "off"}, {Value: "on", Label: "on"}, {Value: "on_insecure", Label: "on_insecure"}},
		},
		{
			Name:  "watch_channels",
			Label: "事件盯哪些频道",
			Type:  contract.ParamType("text"),
			Desc:  "Pub/Sub 频道，逗号分隔，支持通配（如 orders.*）。**填了才启动事件源**：每条消息触发一次工作流。实时但不留存——插件没连着的那段时间收不到",
		},
		{
			Name:  "watch_streams",
			Label: "事件盯哪些 Stream",
			Type:  contract.ParamType("text"),
			Desc:  "Stream 名，逗号分隔。**填了才启动事件源**：从接上的那一刻开始读新消息，消息 id 唯一，重启不会重放",
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
