// Code generated by sokel-gen. DO NOT EDIT.
//
// Event payload types and trigger functions are generated from the schema declaration.
// Change an event there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/redis/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// MessageReceivedEvent is the payload of the "收到频道消息" event.
type MessageReceivedEvent struct {
	Key     string `json:"key" sokel:"key"`
	Payload string `json:"payload" sokel:"payload"`
	Pattern string `json:"pattern" sokel:"pattern"`
}

// StreamMessageEvent is the payload of the "收到 Stream 消息" event.
type StreamMessageEvent struct {
	Key    string         `json:"key" sokel:"key"`
	ID     string         `json:"id" sokel:"id"`
	Fields map[string]any `json:"fields" sokel:"fields"`
}

// DeclareEvents hands this plugin's event contracts to the host.
//
// Common-field consistency was checked at **generation time** (each one must exist in every
// event with the same type), so this cannot fail here — a real problem showed up at
// go generate.
func DeclareEvents(h plugin.EventHost) {
	events := []contract.Event{
		contract.EventOf(&schema.MessageReceived{}),
		contract.EventOf(&schema.StreamMessage{}),
	}
	for _, e := range events {
		h.DeclareEvent(e)
	}
	names := []string{"key"}
	fields, _ := contract.ValidateCommonFields(events, names)
	h.DeclareEventsCommon(fields, names)
}

// TriggerMessageReceived pushes one "收到频道消息" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerMessageReceived(ctx plugin.SourceCtx, eventID string, p *MessageReceivedEvent) error {
	return ctx.Trigger("message_received", eventID, p)
}

// TriggerStreamMessage pushes one "收到 Stream 消息" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerStreamMessage(ctx plugin.SourceCtx, eventID string, p *StreamMessageEvent) error {
	return ctx.Trigger("stream_message", eventID, p)
}
