// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-official-plugins/redis/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnCall registers the implementation of "call".
func OnCall(h plugin.Host, fn func(plugin.Ctx, *CallIn) (*CallOut, error)) {
	h.Register(contract.OperationOf(&schema.Call{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in CallIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnDel registers the implementation of "del".
func OnDel(h plugin.Host, fn func(plugin.Ctx, *DelIn) (*DelOut, error)) {
	h.Register(contract.OperationOf(&schema.Del{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in DelIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnExists registers the implementation of "exists".
func OnExists(h plugin.Host, fn func(plugin.Ctx, *ExistsIn) (*ExistsOut, error)) {
	h.Register(contract.OperationOf(&schema.Exists{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ExistsIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnExpire registers the implementation of "expire".
func OnExpire(h plugin.Host, fn func(plugin.Ctx, *ExpireIn) (*ExpireOut, error)) {
	h.Register(contract.OperationOf(&schema.Expire{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ExpireIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnGet registers the implementation of "get".
func OnGet(h plugin.Host, fn func(plugin.Ctx, *GetIn) (*GetOut, error)) {
	h.Register(contract.OperationOf(&schema.Get{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in GetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHashDel registers the implementation of "hash_del".
func OnHashDel(h plugin.Host, fn func(plugin.Ctx, *HashDelIn) (*HashDelOut, error)) {
	h.Register(contract.OperationOf(&schema.HashDel{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HashDelIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHashGetAll registers the implementation of "hash_get_all".
func OnHashGetAll(h plugin.Host, fn func(plugin.Ctx, *HashGetAllIn) (*HashGetAllOut, error)) {
	h.Register(contract.OperationOf(&schema.HashGetAll{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HashGetAllIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHashSet registers the implementation of "hash_set".
func OnHashSet(h plugin.Host, fn func(plugin.Ctx, *HashSetIn) (*HashSetOut, error)) {
	h.Register(contract.OperationOf(&schema.HashSet{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HashSetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnHealthCheck registers the implementation of "health_check".
func OnHealthCheck(h plugin.Host, fn func(plugin.Ctx, *HealthCheckIn) (*HealthCheckOut, error)) {
	h.Register(contract.OperationOf(&schema.HealthCheck{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in HealthCheckIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnIncr registers the implementation of "incr".
func OnIncr(h plugin.Host, fn func(plugin.Ctx, *IncrIn) (*IncrOut, error)) {
	h.Register(contract.OperationOf(&schema.Incr{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in IncrIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnListPop registers the implementation of "list_pop".
func OnListPop(h plugin.Host, fn func(plugin.Ctx, *ListPopIn) (*ListPopOut, error)) {
	h.Register(contract.OperationOf(&schema.ListPop{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ListPopIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnListPush registers the implementation of "list_push".
func OnListPush(h plugin.Host, fn func(plugin.Ctx, *ListPushIn) (*ListPushOut, error)) {
	h.Register(contract.OperationOf(&schema.ListPush{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ListPushIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnListRange registers the implementation of "list_range".
func OnListRange(h plugin.Host, fn func(plugin.Ctx, *ListRangeIn) (*ListRangeOut, error)) {
	h.Register(contract.OperationOf(&schema.ListRange{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ListRangeIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnPublish registers the implementation of "publish".
func OnPublish(h plugin.Host, fn func(plugin.Ctx, *PublishIn) (*PublishOut, error)) {
	h.Register(contract.OperationOf(&schema.Publish{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in PublishIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnScan registers the implementation of "scan".
func OnScan(h plugin.Host, fn func(plugin.Ctx, *ScanIn) (*ScanOut, error)) {
	h.Register(contract.OperationOf(&schema.Scan{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ScanIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSet registers the implementation of "set".
func OnSet(h plugin.Host, fn func(plugin.Ctx, *SetIn) (*SetOut, error)) {
	h.Register(contract.OperationOf(&schema.Set{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SetIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSetAdd registers the implementation of "set_add".
func OnSetAdd(h plugin.Host, fn func(plugin.Ctx, *SetAddIn) (*SetAddOut, error)) {
	h.Register(contract.OperationOf(&schema.SetAdd{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SetAddIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSetMembers registers the implementation of "set_members".
func OnSetMembers(h plugin.Host, fn func(plugin.Ctx, *SetMembersIn) (*SetMembersOut, error)) {
	h.Register(contract.OperationOf(&schema.SetMembers{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SetMembersIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSetRemove registers the implementation of "set_remove".
func OnSetRemove(h plugin.Host, fn func(plugin.Ctx, *SetRemoveIn) (*SetRemoveOut, error)) {
	h.Register(contract.OperationOf(&schema.SetRemove{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SetRemoveIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnStreamAdd registers the implementation of "stream_add".
func OnStreamAdd(h plugin.Host, fn func(plugin.Ctx, *StreamAddIn) (*StreamAddOut, error)) {
	h.Register(contract.OperationOf(&schema.StreamAdd{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in StreamAddIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnTTL registers the implementation of "ttl".
func OnTTL(h plugin.Host, fn func(plugin.Ctx, *TTLIn) (*TTLOut, error)) {
	h.Register(contract.OperationOf(&schema.TTL{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in TTLIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnZsetAdd registers the implementation of "zset_add".
func OnZsetAdd(h plugin.Host, fn func(plugin.Ctx, *ZsetAddIn) (*ZsetAddOut, error)) {
	h.Register(contract.OperationOf(&schema.ZsetAdd{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ZsetAddIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnZsetRange registers the implementation of "zset_range".
func OnZsetRange(h plugin.Host, fn func(plugin.Ctx, *ZsetRangeIn) (*ZsetRangeOut, error)) {
	h.Register(contract.OperationOf(&schema.ZsetRange{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in ZsetRangeIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
