// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-official-plugins/redis/schema"
)

type CallIn struct {
	Command string   `json:"command" sokel:"command"`
	Args    []string `json:"args" sokel:"args"`
}

type CallOut struct {
	Result any `json:"result" sokel:"result"`
}

type DelIn struct {
	Keys []string `json:"keys" sokel:"keys"`
}

type DelOut struct {
	Deleted int `json:"deleted" sokel:"deleted"`
}

type ExistsIn struct {
	Key string `json:"key" sokel:"key"`
}

type ExistsOut struct {
	Exists bool `json:"exists" sokel:"exists"`
}

type ExpireIn struct {
	Key     string `json:"key" sokel:"key"`
	Seconds int    `json:"seconds" sokel:"seconds"`
}

type ExpireOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type GetIn struct {
	Key string `json:"key" sokel:"key"`
}

type GetOut struct {
	Value  string `json:"value" sokel:"value"`
	Exists bool   `json:"exists" sokel:"exists"`
}

type HashDelIn struct {
	Key    string   `json:"key" sokel:"key"`
	Fields []string `json:"fields" sokel:"fields"`
}

type HashDelOut struct {
	Deleted int `json:"deleted" sokel:"deleted"`
}

type HashGetAllIn struct {
	Key string `json:"key" sokel:"key"`
}

type HashGetAllOut struct {
	Fields map[string]any `json:"fields" sokel:"fields"`
	Count  int            `json:"count" sokel:"count"`
}

type HashSetIn struct {
	Key    string         `json:"key" sokel:"key"`
	Fields map[string]any `json:"fields" sokel:"fields"`
}

type HashSetOut struct {
	Added int `json:"added" sokel:"added"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK         bool   `json:"ok" sokel:"ok"`
	Version    string `json:"version" sokel:"version"`
	Mode       string `json:"mode" sokel:"mode"`
	UsedMemory string `json:"used_memory" sokel:"used_memory"`
	Keys       int    `json:"keys" sokel:"keys"`
	LatencyMs  int    `json:"latency_ms" sokel:"latency_ms"`
	Message    string `json:"message" sokel:"message"`
}

type IncrIn struct {
	Key string `json:"key" sokel:"key"`
	By  int    `json:"by" sokel:"by"`
}

type IncrOut struct {
	Value int `json:"value" sokel:"value"`
}

type ListPopIn struct {
	Key   string `json:"key" sokel:"key"`
	Count int    `json:"count" sokel:"count"`
	Side  string `json:"side" sokel:"side"`
}

type ListPopOut struct {
	Values []string `json:"values" sokel:"values"`
	Count  int      `json:"count" sokel:"count"`
}

type ListPushIn struct {
	Key    string   `json:"key" sokel:"key"`
	Values []string `json:"values" sokel:"values"`
	Side   string   `json:"side" sokel:"side"`
}

type ListPushOut struct {
	Length int `json:"length" sokel:"length"`
}

type ListRangeIn struct {
	Key   string `json:"key" sokel:"key"`
	Start int    `json:"start" sokel:"start"`
	Count int    `json:"count" sokel:"count"`
}

type ListRangeOut struct {
	Values []string `json:"values" sokel:"values"`
	Count  int      `json:"count" sokel:"count"`
}

type PublishIn struct {
	Channel string `json:"channel" sokel:"channel"`
	Message string `json:"message" sokel:"message"`
}

type PublishOut struct {
	Receivers int `json:"receivers" sokel:"receivers"`
}

type ScanIn struct {
	Pattern string `json:"pattern" sokel:"pattern"`
	Cursor  int    `json:"cursor" sokel:"cursor"`
	Count   int    `json:"count" sokel:"count"`
}

type ScanOut struct {
	Keys   []string `json:"keys" sokel:"keys"`
	Cursor int      `json:"cursor" sokel:"cursor"`
	Done   bool     `json:"done" sokel:"done"`
}

type SetIn struct {
	Key        string `json:"key" sokel:"key"`
	Value      string `json:"value" sokel:"value"`
	TTLSeconds int    `json:"ttl_seconds" sokel:"ttl_seconds"`
	Mode       string `json:"mode" sokel:"mode"`
}

type SetOut struct {
	OK bool `json:"ok" sokel:"ok"`
}

type SetAddIn struct {
	Key     string   `json:"key" sokel:"key"`
	Members []string `json:"members" sokel:"members"`
}

type SetAddOut struct {
	Added int `json:"added" sokel:"added"`
}

type SetMembersIn struct {
	Key string `json:"key" sokel:"key"`
}

type SetMembersOut struct {
	Members []string `json:"members" sokel:"members"`
	Count   int      `json:"count" sokel:"count"`
}

type SetRemoveIn struct {
	Key     string   `json:"key" sokel:"key"`
	Members []string `json:"members" sokel:"members"`
}

type SetRemoveOut struct {
	Removed int `json:"removed" sokel:"removed"`
}

type StreamAddIn struct {
	Stream string         `json:"stream" sokel:"stream"`
	Fields map[string]any `json:"fields" sokel:"fields"`
	MaxLen int            `json:"max_len" sokel:"max_len"`
}

type StreamAddOut struct {
	ID string `json:"id" sokel:"id"`
}

type TTLIn struct {
	Key string `json:"key" sokel:"key"`
}

type TTLOut struct {
	Seconds int    `json:"seconds" sokel:"seconds"`
	State   string `json:"state" sokel:"state"`
}

type ZsetAddIn struct {
	Key    string  `json:"key" sokel:"key"`
	Member string  `json:"member" sokel:"member"`
	Score  float64 `json:"score" sokel:"score"`
}

type ZsetAddOut struct {
	Added int `json:"added" sokel:"added"`
}

type ZsetRangeIn struct {
	Key   string `json:"key" sokel:"key"`
	Start int    `json:"start" sokel:"start"`
	Count int    `json:"count" sokel:"count"`
	Desc  bool   `json:"desc" sokel:"desc"`
}

type ZsetRangeOut struct {
	Items []schema.ZItem `json:"items" sokel:"items"`
	Count int            `json:"count" sokel:"count"`
}
